### ISSUE TITLE
[BUG] Form fails to display tables correctly.

### ISSUE THREAD

**Issue by Defying00** [evennia/evennia#2308] opened 2021-01-27 18:56 UTC
#### Describe the bug
Seems like a problem with the form injection code. Two tables seem to fail to render together correctly

#### To Reproduce
![table_code](https://user-images.githubusercontent.com/65582797/106039231-1ba39b80-6096-11eb-95a1-d08b02109071.jpg)

![table_form](https://user-images.githubusercontent.com/65582797/106039409-53124800-6096-11eb-92be-40d590701dbc.jpg)

![render_error](https://user-images.githubusercontent.com/65582797/106039472-64f3eb00-6096-11eb-9c21-71d01d76f400.jpg)

If you change the position of the 3 (the table label) then it changes the render output as well

![form_label_diff](https://user-images.githubusercontent.com/65582797/106039596-86ed6d80-6096-11eb-842c-0e8a89a8f794.jpg)

![new_form_render](https://user-images.githubusercontent.com/65582797/106039663-9bca0100-6096-11eb-8cd4-d74baf966d89.jpg)

#### Expected behavior
I guess expected behavior is for the tables and forms to display as intended, not overlay extra values.

#### Environment, Evennia version, OS etc
Windows 10
Current release version (not dev version)

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by Griatch** [comment] 2021-01-27 19:25
Thanks for the report!

**Comment by Defying00** [comment] 2021-01-27 19:26
No problem! Is there any documentation on how the forms works? If so I can dive in and see what the issue is.

**Comment by Defying00** [comment] 2021-01-27 21:06
<img width="908" alt="bug_2" src="https://user-images.githubusercontent.com/65582797/106054067-c624ba00-60a8-11eb-99a4-c0d649e15273.PNG">

bug is most def happening with tables that that have cells on the same line. It seems like its trying to draw the lines over the top of each other multiple times.

**Comment by Griatch** [comment] 2021-09-16 18:31
@Defying00 Thanks for the bug report! In the future though, please don't supply your error as an image, but instead paste it as text. Because now I must manually type all this to replicate your example instead of being able to copy&paste it. :sweat_smile:

**Comment by Griatch** [comment] 2021-09-16 22:50
@Defying00 I can't reproduce this behavior. Do you still see it?

**Comment by Griatch** [comment] 2022-02-13 22:00
Can't reproduce this, and since there has been no further updates, I'm closing this.

**Closed by Griatch** 2022-02-13 22:00 UTC
Labels: bug, branch-develop, more info needed
