### ISSUE TITLE
Recursive Calling to Script Validate

### ISSUE THREAD

**Issue by cluebyte** [evennia/evennia#765] opened 2015-06-23 21:10 UTC
I've had an interesting error which causes the entire server to sputter and hang (using up 97.4% of my droplet's CPU), which seems to originate from the way script validation is handled. Investigating further, the traceback appears to be as so, repeating indefinitely:

2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/commands/cmdhandler.py", line 394, in _run_command
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     yield cmd.obj.scripts.validate()
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/scripts/scripthandler.py", line 151, in validate
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     ScriptDB.objects.validate(obj=self.obj, init_mode=init_mode)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/scripts/manager.py", line 201, in validate
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     scripts = self.get_all_scripts_on_obj(obj, key=key)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/typeclasses/managers.py", line 27, in func
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     result = method(self, *args, **kwargs)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/evennia/evennia/scripts/manager.py", line 69, in get_all_scripts_on_obj
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.filter(db_obj=obj)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     return getattr(self.get_queryset(), name)(*args, **kwargs)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     return self._filter_or_exclude(False, *args, **kwargs)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     clone.query.add_q(Q(*args, **kwargs))
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1304, in add_q
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     clause, require_inner = self._add_q(where_part, self.used_aliases)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in _add_q
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     current_negated=current_negated, connector=connector, allow_joins=allow_joins)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1194, in build_filter
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     lookups, value)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1740, in get_lookup_constraint
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     lookup_class(target.get_col(alias, source), val), AND)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 96, in __init__
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     self.rhs = self.get_prep_lookup()
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 134, in get_prep_lookup
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/utils/functional.py", line 60, in __get__
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     res = instance.__dict__[self.name] = self.func(instance)
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/opt/pyenv/local/lib/python2.7/site-packages/django/db/models/expressions.py", line 221, in output_field
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::]     if self._output_field_or_none is None:
2015-06-23 20:48:27+0000 [AMPProtocol,0,127.0.0.1] [::] RuntimeError: maximum recursion depth exceeded

28576 root      20   0  531m 472m 7388 R  97.2 23.7  20:33.57 twistd

I haven't done anything crazy with scripts yet, so I'm actually unsure of what's causing such an error. It appears like the yield isn't working for validate, and twistd is intensively taking up resources. This appeared to happen randomly (no one was doing anything on the game at the time before it started to hang).

**Comment by whitenoiseoss** [comment] 2015-06-23 21:20
Would you be able to provide your Script, and perhaps where you are calling it? Just so we can have the full picture of the environment this happened in?

**Comment by cluebyte** [comment] 2015-06-25 04:15
First, I'll apologize. This apparently happened due to a bungle on my part, where I repeatedly recursively called execute_cmd. However, I think this traceback can be misleading, so I won't close it just yet in case we'd like to address how we might give a more informational traceback when we have recursive calls like this that hang the server.

**Comment by Griatch** [comment] 2015-06-25 05:05
@Cluebyte

Without knowing what you did or how to reproduce this, it's impossible to know if the error medsage is unreasonably weird or not.

How do you suggest one would catch this and how would the error message look instead? 
.
Griatch

**Comment by cluebyte** [comment] 2015-06-25 06:41
This occurred while I was attempting to ensure that when another player "follows" another, that when the leader of the group moves to another room, the follower does so also. I did this with the execute_cmd method, where the follower will enter in the same exit command that the leader does.

However, I forgot to check to make sure only the leader is telling all their followers to execute the command, so it went into an infinite recursive loop where the leader would call the follower to execute the exit command, and then the follower would cause the leader to execute the exit command also. 

eg. Player A and Player B are in a group together. Player B is following Player A. Player A moves west to another room. Player A moves, and in doing so, Player B executes the same exit command. But there is no check for only the leader to make the call for grouped members, so each member in the group will make a call to everyone else to do that exit command, leading into an infinite loop.

This is beyond my realm of expertise at the moment in offering a comprehensive solution, but perhaps some throttling involved with execute_cmd might help, or a max number of times the same exact command might be called using execute_cmd. I can think of few cases besides a major booboo where the server is calling an object to perform a task an exceedingly high number of times.

**Comment by Griatch** [comment] 2015-08-24 11:58
After some consideration I don't think infinite loops should be caught by Evennia - if your code calls itself indefinitely it's an error in your design and there *should* be a traceback so you can fix your  code. 

I keep this open since the error was not all that helpful though, maybe one can raise the traceback in a position to make it clearer just what the heck happened rather than let the script initialization catch it.

**Comment by Griatch** [comment] 2015-09-27 11:48
@cluebyte 

The latest revision adds a nesting counter to the cmdhandler that will raise a clean RuntimeException if the same caller is trying to nest-call commands more than 10 levels deep. I'm not sure if your particular issue (different objects triggering command-calls on each other) is really possible to track, but at least self-referencing or looping-style nesting should be handled by this change.  

Closing.

**Closed by Griatch** 2015-09-27 11:48 UTC
Labels: bug
