### ISSUE TITLE
Untrapped error when using look command with any parameter while OOC

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#921] opened 2016-02-08 04:33 UTC
Among the errors I have been able to generate, this is the most common:
'NoneType' object is not iterable.

In this case, it occurs in evennia/commands/cmdhandler.py line 435
There may be other factors to reproduce this one. Tag if you need more information.

**Comment by kaihuang201** [comment] 2016-02-09 20:13
Could you please post the complete stack trace?

**Comment by BlauFeuer** [comment] 2016-02-09 20:37
You'd have to explain what a stack trace is, I can reproduce it in stock Evennia + tutorial, but there might be factors that you are missing if you can't get the error, yourself. I didn't notice it occurring until after I set MULTISESSION_MODE = 2, for example.

**Comment by strikaco** [comment] 2016-02-09 20:53
The stack trace is the debug information that a program usually spits out along with the untrapped error you're seeing. It's what told you the problem is on line 435..they're just asking for all of the information rather than just that piece.

**Comment by kaihuang201** [comment] 2016-02-09 21:15
Okay I am able reproduce the error by using "look" command OOC, in a default game with "MULTISESSION_MODE = 2" added to <game_name>/server/conf/settings.py

Here's the stack trace I got:
```
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/kh/evennia/evennia/evennia/commands/cmdhandler.py", line 435, in _run_command
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]     ret = yield cmd.func()
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/kh/evennia/evennia/evennia/commands/default/player.py", line 104, in func
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]     self.msg(self.player.at_look(target=self.playable, session=self.session))
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]   File "/home/kh/evennia/evennia/evennia/players/players.py", line 799, in at_look
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::]     characters = list(target)
2016-02-09 21:00:32+0000 [AMPProtocol,0,127.0.0.1] [::] TypeError: 'NoneType' object is not iterable
```

**Comment by BlauFeuer** [comment] 2016-02-11 11:23
> Griatch@#evennia: ****: Are you getting any tracebacks in your logs?

The Traceback in the log is where I saw the reference to the line number and file, now I understand that the full output may lead more directly to the problem.  I thought "stack trace" was some fancy thing I didn't have access to.  I just hand-typed the information since I have no cut/paste from that viewport into the console.  Next time I'll dig into the log file for the information to be more specific. Thanks for the explanation!

Though when this bug is fixed, it will probably prevent some of the others I saw, so I'll hang on for awhile before making reports that are similar.

**Comment by Griatch** [comment] 2016-04-11 18:20
I am not able to reproduce this on the latest master, with a fresh game folder, `MULTISESSION_MODE=2 ` and being OOC. I can use look just fine while seeing the character list menu. 

@BlauFeuer, @kaihuang201 
Could either of you test to see if you still see this in the latest master, and if so, exactly recount the steps for reproducing the error?

**Comment by Griatch** [comment] 2016-04-11 21:16
Resolved in devel.

**Closed** 2016-05-22 20:28 UTC
Labels: bug, devel, implemented
