### ISSUE TITLE
[BUG] Creating a dummy in the Tutorial fails validate_slot_usage

### ISSUE THREAD

**Issue by morgurth** [evennia/evennia#3243] opened 2023-07-27 13:37 UTC
#### Describe the bug
When running the command "create/drop dummy puppet;dummy:evadventure.npcs.EvAdventureNPC", the object fails because all objects created by an EvAdventureCharacter is ran through "at_object_receive" on creation.

#### To Reproduce

1. Create files in tutorial
2. Start Evennia
3. Log in to Evennia
4. Run "batchcmd evadventure.batchscripts.twitch_combat_demo"

#### Expected behavior
A "dummy puppet" NPC is created with a description and HP set.

#### Environment, Evennia version, OS etc
    Evennia 2.1.0
    OS: Ubuntu
    Python: 3.11.3
    Twisted: 22.10.0
    Django: 4.1.9

#### Additional context
I added the following to "characters.py" to bypass this. It does create the dummy but it is in my inventory and can't be dropped.

```
from evennia.utils.utils import lazy_property, inherits_from
from .objects import EvAdventureObject

    def at_object_receive(self, moved_object, source_location, **kwargs): 
        """ 
        Called by Evennia when an object arrives 'in' the character.
        
        """
        if inherits_from(moved_object, EvAdventureObject):
            self.equipment.add(moved_object)

**Comment by morgurth** [comment] 2023-07-28 11:40
If you reorder the creation, you can get the dummy puppet created, but attacking is failing. Possibly "is_hit" in objects.py is never "True"?

```
# Evadventure combat demo 

# start from limbo

tel #2

# dig a combat arena

dig arena:evadventure.rooms.EvAdventureRoom = arena,back

# go to arena

arena

# allow combat in this room

set here/allow_combat = True

# create a dummy enemy to hit on

create/drop dummy puppet;dummy:evtutorial.npcs.EvAdventureNPC

# describe the dummy

desc dummy = This is is an ugly training dummy made out of hay and wood.

# make the dummy crazy tough

set dummy/hp_max = 1000

# 

set dummy/hp = 1000

# turn ourselves into a evadventure-character

type self = evadventure.characters.EvAdventureCharacter

# assign us the twitch combat cmdset (requires superuser/developer perms)

py self.cmdset.add("evtutorial.combat_twitch.TwitchCombatCmdSet", persistent=True)

# Create a weapon in our inventory (using all defaults)

create sword:evadventure.objects.EvAdventureWeapon

# create a consumable to use

create potion:evadventure.objects.EvAdventureConsumable
```

**Comment by Griatch** [comment] 2023-08-06 20:03
I can't reproduce this; there is a[try...except in the default EvAdventureCharacter](https://github.com/evennia/evennia/blob/main/evennia/contrib/tutorials/evadventure/characters.py#L215-L229) that avoids this problem - you get a traceback in the log to let you know you are dealing with a non-evadventure object, but everything works otherwise. Could you be working with an old version of the evadventure code? 

I'm closing this, if you find you still have trouble, feel free to comment here and I can open again.

**Closed by Griatch** 2023-08-06 20:03 UTC
Labels: bug, needs-triage
