### ISSUE TITLE
Small issue with case sensitivity in cmdparser

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#974] opened 2016-05-14 04:24 UTC
#### Brief summary of issue / Description of requested feature:

I had to comment out the following lines in cmdparser in order to have some custom exit commands work in a way players expected:

    if len(matches) > 1:
        # See if it helps to analyze the match with preserved case but only if
        # it leaves at least one match.
        trimmed = [match for match in matches
                     if raw_string.startswith(match[0])]
        if trimmed:
            matches = trimmed

To explain, I had commands that let people lock/unlock/pass through exits, derived from the exit names/aliases, in the same manner that exits do. However, what happens when an exit is named something like 'Plaza (PL)' with 'PL' as an alias? aliases and keys are made lower() by the command meta class, but then the above attempts to trim results based on case sensitivity. So all works fine if a player does 'pass pl', for example, but if they do 'pass PL', the case sensitivity check will eliminate that choice, and instead match 'p' for page.

**Comment by Griatch** [comment] 2016-05-14 14:59
@TehomCD 

The parser tries to do all its available data to weed out multi-matches, but you make a good point that it's shooting itself in the foot due to the lower-case treatment of the meta class. I'm not sure if removing this check will lead to some other edge case working badly though, will need to consider that a bit.

**Comment by Griatch** [comment] 2016-05-21 14:33
This is on hold until wclient branch merges.

**Comment by Griatch** [comment] 2016-05-25 11:29
Marking as a bug for now, still not sure if removing the check it is a good idea or not.

**Comment by Griatch** [comment] 2016-06-24 21:34
@TehomCD 

I cannot reproduce the given issue even without touching the relevant section of the cmdparser. I dug a new room with `@dig Plaza = Plaza;PL` - that is, a new room with an exit "Plaza" with an alias "PL" leading to it. This is a vanilla setup, so "page" is available to me as well. I can now use "pl", "PL", "Pl" and any other combination thereof and will end up in the Plaza room every time without any mix-up with the `page` command. 

So I'm closing this - either this has been resolved by other, later changes or I'm testing it wrong. If the latter, don't hesitate to reply here and request this be re-opened.

**Closed by Griatch** 2016-06-24 21:34 UTC
Labels: bug

**Comment by TehomCD** [comment] 2016-06-26 02:08
If I remember right, the issue might be if the command contained case-sensitive characters at the end rather than the beginning. The example command I gave was 'pass PL', and the quoted text checks starts_with for trimming matches, which may have been what caused the mismatch for me. You might have to create an exit or command that's more than one word with uppercase at the end to duplicate it. Does the vanilla exit command allow for multiple words in it? If so, you might be able to create something like 'plaza CAPS' as a test case or something.
