### ISSUE TITLE
Bug: Delcom with aliases raises exception

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1062] opened 2016-09-14 04:04 UTC
#### Brief summary of issue / Description of requested feature:
When using delcom on a channel that has aliases, the loop that deletes the channel's nicknames throws the following exception:

Traceback (most recent call last):
  File "c:\arx\evennia\evennia\commands\cmdhandler.py", line 464, in _run_command
    ret = yield cmd.func()
  File "c:\arx\evennia\evennia\commands\default\comms.py", line 167, in func
    nick.delete()
  File "c:\arx\evennia\evennia\utils\idmapper\models.py", line 351, in delete
    super(SharedMemoryModel, self).delete(*args, **kwargs)
  File "C:\arx\Lib\site-packages\django\db\models\base.py", line 865, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: Attribute object can't be deleted because its id attribute is set to None.

#### Steps to reproduce the issue / Reasons for adding feature:

1. addcom foo=public
2. delcom public

**Comment by Griatch** [comment] 2016-09-14 05:20
I cannot reproduce this; but I added a check for `.pk` in the nick-delete loop that should avoid this case should it happen at this point in the command. So closing.

**Closed by Griatch** 2016-09-14 05:20 UTC
