### ISSUE TITLE
[BUG]When using Hangul, the columns in the table do not match.

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#2166] opened 2020-07-15 15:59 UTC
#### Describe the bug
You suffer a lot.
If EvTable uses Hangul, etc., the columns do not match.
So I am temporarily using https://github.com/Robpol86/terminaltables, can it be improved?

who
Accounts:
+--------------+--------+------+-----------+-------+------+----------+--------------+
| Account Name | On for | Idle | Puppeting | Room  | Cmds | Protocol | Host         |
+~~~~~~~~~~~~~~+~~~~~~~~+~~~~~~+~~~~~~~~~~~+~~~~~~~+~~~~~~+~~~~~~~~~~+~~~~~~~~~~~~~~+
| amro(#1)     | 01:18  | 4s   | 암로(#1)    | 광장    | 9    | telnet   | 172.30.1.30  |
| angel        | 16:58  | 11s  | 천사        | 19_57 | 5980 | telnet   | 172.30.1.254 |
| devil        | 16:57  | 11s  | 악마        | 19_57 | 6664 | telnet   | 172.30.1.254 |
| lucifer      | 16:57  | 11s  | 루시퍼       | 19_57 | 6657 | telnet   | 172.30.1.254 |
| michael      | 16:58  | 11s  | 미카엘       | 19_57 | 5612 | telnet   | 172.30.1.254 |
| neo          | 01:39  | 0s   | 네오        | 19_57 | 6791 | telnet   | 172.30.1.254 |
| oracle       | 16:58  | 11s  | 오라클       | 19_57 | 5898 | telnet   | 172.30.1.254 |
| saby         | 01:41  | 2s   | 사비        | 7_46  | 6214 | telnet   | 172.30.1.254 |
| tintin       | 16:58  | 3s   | 틴틴        | 7_46  | 8094 | telnet   | 172.30.1.254 |
| tree         | 16:58  | 3s   | 트리        | 7_46  | 7202 | telnet   | 172.30.1.254 |
| wizard       | 16:58  | 3s   | 마법사       | 7_46  | 7122 | telnet   | 172.30.1.254 |
| zeze         | 16:58  | 3s   | 제제        | 7_46  | 8088 | telnet   | 172.30.1.254 |
+--------------+--------+------+-----------+-------+------+----------+--------------+
12 unique accounts logged in.
tickers
Active tickers:
+--------------+---------------+-----------------+----------+----+
| interval (s) | object        | path/methodname | idstring | db |
+~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~+~~~~~~~~~~+~~~~+
| 1            | 오라클 (#97300)  | every_second_do | cha      | *  |
| 1            | 미카엘 (#97304)  | every_second_do | cha      | *  |
| 1            | 틴틴 (#47733)   | every_second_do | cha      | *  |
| 1            | 천사 (#56724)   | every_second_do | cha      | *  |
| 1            | 제제 (#47734)   | every_second_do | cha      | *  |
| 1            | 마법사 (#47736)  | every_second_do | cha      | *  |
| 1            | 트리 (#47735)   | every_second_do | cha      | *  |
| 1            | 악마 (#56722)   | every_second_do | cha      | *  |
| 1            | 루시퍼 (#97305)  | every_second_do | cha      | *  |
| 1            | 사비 (#47732)   | every_second_do | cha      | *  |
| 1            | 네오 (#97301)   | every_second_do | cha      | *  |
| 1            | 암로 (#1)       | every_second_do | cha      | *  |
| 1            | 버서커 (#113259) | do_attack       | mob      | *  |
| 1            | 버서커 (#113236) | do_patrol       | mob      | *  |
| 1            | 버서커 (#113240) | do_patrol       | mob      | *  |
| 1            | 듀라한 (#113205) | do_patrol       | mob      | *  |
| 1            | 버서커 (#113257) | do_patrol       | mob      | *  |
| 1            | 버서커 (#113241) | do_patrol       | mob      | *  |
| 1            | 듀라한 (#113235) | do_patrol       | mob      | *  |
| 28           | 버서커 (#113258) | set_alive       | mob      | *  |
+--------------+---------------+-----------------+----------+----+

**Comment by Griatch** [comment] 2020-07-15 16:13
You table doesn't appear to match up even for the parts outside of the unicode characters which is kinda strange. 
As far as I know, these kinds of characters have no internal description of their "visual width", but there could be some other cause for this particular display issue.

**Comment by aceamro** [comment] 2020-07-15 16:23
Thanks for the quick answer.
It didn't work for every environment I tested, whether on the web, on tintin++, or on mobile.
In the game you are testing, change the name to hangul and test it.
copy&paste name: 한글

**Comment by Griatch** [comment] 2020-07-15 17:19
The issue is, the way that I understand it, that 

    len("한글") == 2

but in the same way, 

    len("aa") == 2

Just by comparing the two visually:

    한글
    aa

it's clear that the hangul letters are _visually_ much wider (its `len()==2` is actually more than 3 `a`s  wide). Since `EvTable` works with `len()`, it correctly calculates the width, but visually it's still off. 

As far as I know there is no way for Evennia to know the 'visual' width of the character set and to compensate for this. To make this look right you must switch to a monospace font built specifically for use with this type of alphabet. Are you saying `terminaltables` can display it correctly using the same font/encoding?

**Comment by aceamro** [comment] 2020-07-15 17:25
If I use the terminaltables library it looks right.
The store purchase item is using the terminaltables library.

**Comment by Griatch** [comment] 2020-07-15 17:27
To be clear - it looks correct when using `terminaltables` library  _in game_?

**Comment by aceamro** [comment] 2020-07-15 17:27
Yes, it is.

**Comment by Griatch** [comment] 2020-07-15 17:29
Can you give a screenshot of that, would be interesting to see how it compensates.

**Comment by aceamro** [comment] 2020-07-15 17:29
I will send it by email.

**Comment by Griatch** [comment] 2020-07-15 17:30
You can just attach it here :)

**Comment by aceamro** [comment] 2020-07-15 17:32
<img width="780" alt="스크린샷 2020-07-16 오전 2 31 22" src="https://user-images.githubusercontent.com/3595071/87576518-7b46e480-c70c-11ea-8bee-c6b952cb6dba.png">
Can you see it?

**Comment by Griatch** [comment] 2020-07-15 17:34
Cool, yes I can see it. Is this using `terminaltables.SingleTable`?

**Comment by aceamro** [comment] 2020-07-15 17:37
This is the part I am using.



`
    from world.terminaltables.ascii_table import AsciiTable

    def return_appearance(self, looker, **kwargs):
        if not looker:
            return ""

        if not _quest(looker, trigger_obj=self, trigger_msg=None, trigger_action=None):
            return

        if self.db.desc:
            """|/구입방법: |G구입|n 품명, |G구입|n 품명 갯수|/"""
            string = self.db.desc + "\n"
        else:
            string = "\n"

        if len(self.contents) == 0:
            string += "재고가 없습니다."
            return string

        item_list = (con for con in self.contents if con.db.item_class and (con.attributes.has("gold_price") or con.attributes.has("silver_price") or con.attributes.has("bronze_price")))
        weapons, armors, potions, things = [], [], [], []

        for item in item_list:
            """가격"""
            gold_price, silver_price, bronze_price = "", "", ""

            if item.db.gold_price:
                gold_price = format(item.db.gold_price, ',') + "골드"
            if item.db.silver_price:
                silver_price = format(item.db.silver_price, ',') + "실버"
            if item.db.bronze_price:
                bronze_price = format(item.db.bronze_price, ',') + "브론즈"

            price = gold_price + silver_price + bronze_price

            """효과"""
            info = []
            if item.db.DI:
                info.append("파괴력:+%s" % item.db.DI)
            if item.db.magic_DI:
                info.append("마법파괴력:+%s" % item.db.magic_DI)
            if item.db.DR:
                info.append("방어력:+%s" % item.db.DR)
            if item.db.magic_DR:
                info.append("마법방어력:+%s" % item.db.magic_DR)
            if item.db.hp_up_time:
                info.append("HP회복강화:+%s초" % item.db.hp_up_time)
            if item.db.fp_up_time:
                info.append("FP회복강화:+%s초" % item.db.fp_up_time)
            if item.db.hp_up:
                info.append("HP회복량:+%s" % item.db.hp_up)
            if item.db.fp_up:
                info.append("FP회복량:+%s" % item.db.fp_up)
            if item.db.stun_success_rate_up:
                info.append("부가효과:스턴")
            if item.db.item_class == "return_scroll":
                info.append("사용시 " + item.db.send_defeated_to + " 귀환")
            if item.db.item_class == "upgrade_scroll":
                info.append(item.key.split("강화주문서")[0] + " 강화")
            if item.db.two_hand:
                info.append("양손무기")
            if item.db.noup:
                info.append("강화:불가")
            if item.db.safe_upgrade:
                info.append("안전강화:+%s" % item.db.safe_upgrade)
            if item.db.notrade:
                info.append("거래:불가")
            if item.db.item_class == "bullet":
                info.append("%s개 묶음" % item.db.bullet_quantity)
            join_info = ', '.join(info)

            weight = "%skg" % item.db.weight

            if item.db.item_class.find("weapon") != -1:
                weapons.append([item.key, join_info, weight, str(price)])
            elif item.db.item_class.find("armor") != -1:
                armors.append([item.key, join_info, weight, str(price)])
            elif item.db.item_class.find("potion") != -1:
                potions.append([item.key, join_info, weight, str(price)])
            else:
                things.append([item.key, join_info, weight, str(price)])

        table_data = [["품  목", "효  과", "무  게", "가  격"]]
        table_data += weapons + armors + potions + things
        table = AsciiTable(table_data)
        table.justify_columns[0] = 'center'
        table.justify_columns[1] = 'center'
        table.justify_columns[2] = 'center'
        table.justify_columns[3] = 'center'

        string += table.table

        return string`

**Comment by Griatch** [comment] 2020-07-15 17:49
Interesting. Thanks for the example.

**Comment by aceamro** [comment] 2020-07-15 17:52
Thank you for your interest.

For reference, this is my game video.
Action RPG
https://youtu.be/zKrlFPtmTtg

evennia is awesome.

**Comment by Griatch** [comment] 2020-07-15 21:24
@aceamro I learned something new :) Looking at `terminaltables` for reference, it turns out there is indeed a separate way to estimate the width of asian unicode characters. I have added this now and EvTables looks fine with a sample of characters. Check it out! 

I'm closing this now, but can open again should there be any lingering issues. Thanks for the feedback and I'm glad you enjoy Evennia!

**Closed by Griatch** 2020-07-15 21:24 UTC
Labels: bug

**Comment by aceamro** [comment] 2020-07-16 01:10
WOW
I checked that it was applied nicely.
thank you very much. :)
