### ISSUE TITLE
Locks on bots (CmdLock not able to affect bot account)

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1417] opened 2017-09-04 10:48 UTC
### Brief summary of issue / Description of requested feature:
The solution to #701 requires `@lock` to add `no_idle_disconnect:true()` (or any non-False lock, it seems), but I was not able to use `CmdLock` to do this. 

### Steps to reproduce the issue / Reasons for adding feature:

1. As super-user, use `@irc2chan` to create a bot account.
2. As super-user, use `@lock` to add a lock to the bot account. 

### Error output / Expected result of feature
> [MudInfo] [MudInfo, 2017-09-04(03:42)]: ircbot-PM disconnected (idle timeout exceeded)

`> @py self.account.search('#14')`
self.account.search('`#14`')
ircbot-PM(account 14)  **Expected result - account exists**

`> @find *#14`
Match(`#1`-`#1224`):
    No match found.  **Unable to `@find` account 14**

`> @find *ircbot-PM`
Match(`#1`-`#1224`):
   No match found. **Unable to `@find` account 14 by name**

`> @lock/view *ircbot-PM/`
Could not find 'ircbot-PM'.
Could not find '*ircbot-PM'. **Unable to `@lock` account 14 by name**

`> @lock/view *blaufeuer/`
boot:perm(Admin);delete:perm(Admin);edit:perm(Admin);examine:perm(Admin);msg:all()
**Expected result - account exists and has locks**

`> @lock/view *#14/`
Could not find '`#14`'.
Could not find '*`#14`'. **Unable to `@lock` account 14 by number**

`> @lock/view *#3/`
Could not find '`#3`'.
Could not find '*`#3`'. **Unable to `@lock` account 3 by number**

`> @lock/view *Vincent/`
boot:perm(Admin);delete:perm(Admin);edit:perm(Admin);examine:perm(Admin);msg:all()
**Expected result - account exists and has locks**

`> @lock *ircbot-PM/no_idle_disconnect`
Could not find 'ircbot-PM'.
Could not find '*ircbot-PM'.
**Unable to view a specific `@lock` on an account 14 by name**

`> @lock *ircbot-PM=no_idle_disconnect:true()`
Could not find 'ircbot-PM'.
Could not find '*ircbot-PM'.  **Unable to set `@lock` on account 14 by name**

`> @lock *#14=no_idle_disconnect:true()`
Could not find '`#14`'.
Could not find '*`#14`'.  **Unable to set `@lock` on account 14 by number**

### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Latest revision, evennia repo, devel branch, any OS

**Comment by Griatch** [comment] 2017-09-09 13:30
`@lock` deals with Players and objects, while bots are, well Bots. Bots are OOC entities usually manipulated with `@py` or directly in code. So it's correct behavior that you cannot do this with the normal `@lock` - querying for bot `#dbrefs` with normal commands will lead to trouble. This should really be added on that bot typeclass (I thought it already was but maybe not).

**Comment by BlauFeuer** [comment] 2017-09-09 13:41
@Griatch  "Players" (now "Accounts") are OOC entities, too, just like bots.  Either I'm confused by the nomenclature, the semantics, or you're saying that even `@lock` and `@find` only deal with a certain typeclass of Accounts.

If it's not a bug, then please consider this a feature request to be able to set these locks.

**Comment by Griatch** [comment] 2017-09-09 13:47
Nah, you are right, it's me that mix it up with previous incarnations of bots. :) As you say, bots are regular Players these days and are in the same `#dbref` space as Players/Accounts. The issue is likely that the `@lock` command is not properly reacting to the `*` flag or somesuch.

**Comment by Griatch** [comment] 2017-09-10 15:57
Resolved in devel; will close when devel merges.

**Closed** 2017-09-20 19:58 UTC
Labels: bug, devel, implemented
