### ISSUE TITLE
Stopping a global script with script/stop

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1878] opened 2019-07-29 12:33 UTC
#### Brief summary of issue / Description of requested feature:

It seems stopping global scripts using the command `script/stop` doesn't work.  If so, it might be good to fix that.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a global script, no tie to any object.
2. Try to stop it with `script/stop`.  You might use two different usages:
    - `script/stop script key`: the script can't be found.  The parameter before the equal sign is the object, so it might not be too strange.
    - `script/stop = script key`: one can't use `script/stop` with global scripts (specifying no object left of the equal sign).

#### Error output / Expected result of feature

The second syntax, I think, would actually make sense:

`script/stop = script key`

It makes sense regarding the command documentation, although I would suggest this would be clearly stated in the command help.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- Evennia master.

**Comment by Griatch** [comment] 2019-08-14 15:55
Also worth to check in on this: https://github.com/evennia/evennia/issues/1715

**Comment by Griatch** [comment] 2019-08-28 21:44
Reviewing this - this is not actually a bug - the `script` command is _specifically_ for on-object scripts, not for global scripts. You use the `scripts/stop #id` to stop a global script. The `scripts` command is analogous to the `objects` command in the sense that it operates on every entity. That was at least the original design of it. I agree it's pretty confusing though and from a time when a global script was not really provisioned for very much. It's not a bug though; merging all the functionality into one command would rather be a feature request. Closing.

**Closed by Griatch** 2019-08-28 21:44 UTC
Labels: bug, master-branch
