### ISSUE TITLE
Spawn command has numerous critical issues (/update broken; wrong item locations; /list stops working requiring a full shutdown and restart).

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1879] opened 2019-08-01 19:23 UTC
The spawn command when used to spawn from prototype dicts stored inside modules has a number of severe issues:

1. The /update switch asks for confirmation but does not actually update the relevant objects. I tried changing a single integer attribute on the prototype inside the module - attempted the /update feature both after and before a reload.

2. Spawning multiples of the same prototype does so in the same location the caller was in when spawning that prototype for the first time instead of in the current location of the caller. After a reload a prototype can be spawned correctly in the callers current location and then will again lock to only being spawned in that location. /noloc does not seem to do anything.

3. While trying to further test this behaviour out I tried the /show switch but that returned nothing afterwhich /list also returned nothing. The spawn command would not work at all after that point even after a reload. It was available again after a full shutdown and startup however.

4. Trying to use some of the other switches (possibly incorrectly due to the docstring shown by the help command being innacurate) sometimes resulted with tracebacks (suggesting that possibly something odd is happening with how the args are parsed?).

Steps to reproduce would involve creating a couple of modules with prototypes, each with one parent and one child (the child pointing to the parent rather than listing a typeclass) and trying to spawn the child prototypes, updating them etc. as explained above.

**Comment by BP-Santo** [comment] 2019-08-02 04:13
Went through the prototypes modules trying to figure how it all works and eventually decided to refactor the spawn command locally and managed to fix problem no 2. by changing the new object spawn code at the end (also added a "here" switch which seemed necessary):

```
        # deserialise the prototype to avoid None or caller location persisting untill next reload
        deserialised_prototype = dict(prototype)
        if "noloc" not in self.switches and ("location" not in prototype or "here" in self.switches):
            deserialised_prototype["location"] = self.caller.location
        elif "noloc" in self.switches:
            deserialised_prototype["location"] = None
        # proceed to spawning
        try:
            for obj in spawner.spawn(deserialised_prototype):
                self.caller.msg(f"Spawned {obj.get_display_name(self.caller)}!")
        except RuntimeError as err:
            caller.msg(err)
```

I also noticed two unresolved references to simply "key" which is not even used as a var name untill the end of that module (not sure about the impact of that however).

I tried to figure out how to make the update switch work and managed to gather as much:
Updating only manages to do anything with spawned objects if the spawner.batch_update_objects_with_prototype is given an complete dictionary to work with and not simply a correct key. Trying to get that prototype using the various methods utilised in the spawn command makes the above mentioned method at best update the object to only have the attributes from the prototype (without the attributes from the typeclass, breaking the obejct in effect).
I would imagine someone who understands the spawn/prototype system would be able to use the existing methods to properly get a complete dict like when spawning a brand new object so it can be passed to spawner.batch_update_objects_with_prototype.

**Comment by BP-Santo** [comment] 2019-08-05 06:40
Adding my local refactor of the command in case it comes in handy:

```
from commands.default_mux_command import DefaultMuxCommand
from evennia.utils import utils
from evennia.utils.evmore import EvMore
from evennia.prototypes import spawner, prototypes as protlib, menus as olc_menus
from ast import literal_eval as _LITERAL_EVAL


class Spawn(DefaultMuxCommand):
    """
    Spawn objects from prototype
    Usage:
      spawn[/noloc][/here] <prototype_key>
      spawn[/noloc][/here] <prototype_dict>
      spawn/search [prototype_key][;tag[,tag]]
      spawn/list [tag, tag, ...]
      spawn/show <prototype_key>
      spawn/update <prototype_key>
      spawn/save <prototype_dict>
      spawn/menu <prototype_key>

    Switches:
      noloc   - forces location as none
      here    - forces location to caller.location
                if no location set in prototype this is default behaviour!
      search  - search available prototypes by name or tags.
      list    - list available prototypes, optionally limit by tags.
      examine - inspect prototype by key. If not given, acts like list.
      save    - save a prototype dict to the database. It will be listable by /list.
      delete  - remove a prototype from database, if allowed to.
      update  - find existing objects with the same prototype_key and update
                them with latest version of given prototype. If used as part of /save,
                will auto-update all objects with the old version of the prototype
                without asking first.
      menu    - create/manipulate prototypes in a comprehensive menu interface.

    Dictionary keys:
      |wprototype_parent  |n - name of parent prototype to use. Required if typeclass is
                        not set. Can be a path or a list for multiple inheritance (inherits
                        left to right). If set one of the parents must have a typeclass.
      |wtypeclass  |n - string. Required if prototype_parent is not set.
      |wkey        |n - string, the main object identifier
      |wlocation   |n - this should be a valid object or #dbref
      |whome       |n - valid object or #dbref
      |wdestination|n - only valid for exits (object or dbref)
      |wpermissions|n - string or list of permission strings
      |wlocks      |n - a lock-string
      |waliases    |n - string or list of strings.
      |wprototype_key|n   - name of this prototype. Unique. Used to store/retrieve from db
                            and update existing prototyped objects if desired.
      |wprototype_desc|n  - desc of this prototype. Used in listings
      |wprototype_locks|n - locks of this prototype. Limits who may use prototype
      |wprototype_tags|n  - tags of this prototype. Used to find prototype
      any other keywords are interpreted as Attributes and their values.

    The available prototypes are defined globally in modules set in
    settings.PROTOTYPE_MODULES.
    """

    key = "spawn"
    switch_options = ("noloc", "here", "search", "list", "examine", "save", "delete", "menu", "update")
    locks = "cmd:perm(spawn) or perm(Builder)"
    help_category = "Building"

    def func(self):
        """Implements the spawner"""

        def _parse_prototype(inp, expect=dict):
            error_parse = None
            prototype_parse = None
            try:
                prototype_parse = _LITERAL_EVAL(inp)
            except (SyntaxError, ValueError) as error_parse:
                # treat as string
                prototype_parse = utils.to_str(inp)
            finally:
                if not isinstance(prototype_parse, expect):
                    if error_parse:
                        msg_string = (f"{error_parse}\n|RCritical Python syntax error in argument. Only primitive "
                                      "Python structures are allowed. \nYou also need to use correct "
                                      "Python syntax. Remember especially to put quotes around all "
                                      "strings inside lists and dicts.|n For more advanced uses, embed "
                                      "inline functions in the strings.")
                    else:
                        msg_string = f"Expected {expect}, got {type(prototype_parse)}."
                    self.caller.msg(msg_string)
                    return None
            if expect == dict:
                # an actual prototype. We need to make sure it's safe. Don't allow exec
                if "exec" in prototype_parse and not self.caller.check_permstring("Developer"):
                    self.caller.msg("Spawn aborted: You are not allowed to "
                                    "use the 'exec' prototype key.")
                    return None
                try:
                    # we homogenize first, to be more lenient
                    protlib.validate_prototype(protlib.homogenize_prototype(prototype_parse))
                except RuntimeError as error_parse:
                    self.caller.msg(str(error_parse))
                    return
            return prototype_parse

        def _search_show_prototype(query, prototypes_search=None):
            # prototype detail
            if not prototypes_search:
                prototypes_search = protlib.search_prototype(key=query)
            if prototypes_search:
                return "\n".join(protlib.prototype_to_str(prototype_show) for prototype_show in prototypes_search)
            else:
                return False

        caller = self.caller

        if 'menu' in self.switches:
            # OLC menu mode
            prototype = None
            if self.lhs:
                key = self.lhs
                prototype = protlib.search_prototype(key=key)
                if len(prototype) > 1:
                    caller.msg("More than one match for {}:\n{}".format(
                        key, "\n".join(proto.get('prototype_key', '') for proto in prototype)))
                    return
                elif prototype:
                    # one match
                    prototype = prototype[0]
                else:
                    # no match
                    caller.msg(f"No prototype '{key}' was found.")
                    return
            olc_menus.start_olc(caller, session=self.session, prototype=prototype)
            return

        if 'search' in self.switches:
            # query for a key match
            if not self.args:
                self.switches.append("list")
                return
            else:
                key, tags = self.args.strip(), None
                if ';' in self.args:
                    key, tags = (part.strip().lower() for part in self.args.split(";", 1))
                    tags = [tag.strip() for tag in tags.split(",")] if tags else None
                EvMore(caller, str(protlib.list_prototypes(caller, key=key, tags=tags)),
                       exit_on_lastpage=True)
                return

        if 'examine' in self.switches:
            # the argument is a key in this case (may be a partial key)
            if not self.args:
                self.switches.append('list')
                return
            else:
                match_string = _search_show_prototype(self.args)
                if match_string:
                    caller.msg(match_string)
                else:
                    caller.msg(f"No prototype '{self.args}' was found.")
                return

        if 'list' in self.switches:
            # for list, all optional arguments are tags
            # import pudb; pudb.set_trace()

            EvMore(caller, str(protlib.list_prototypes(caller, tags=self.lhslist)), exit_on_lastpage=True)
            return

        if 'save' in self.switches:
            # store a prototype to the database store
            if not self.args:
                caller.msg(
                    "Usage: spawn/save <key>[;desc[;tag,tag[,...][;lockstring]]] = <prototype_dict>")
                return

            # handle rhs:
            prototype = _parse_prototype(self.lhs.strip())
            if not prototype:
                return

            # present prototype to save
            new_match_string = _search_show_prototype("", prototypes_search=[prototype])
            string = f"|yCreating new prototype:|n\n{new_match_string}"
            question = "\nDo you want to continue saving? [Y]/N"

            prototype_key = prototype.get("prototype_key")
            if not prototype_key:
                caller.msg("\n|yTo save a prototype it must have the 'prototype_key' set.")
                return

            # check for existing prototype,
            old_match_string = _search_show_prototype(prototype_key)

            if old_match_string:
                string += f"\n|yExisting saved prototype found:|n\n{old_match_string}"
                question = "\n|yDo you want to replace the existing prototype?|n [Y]/N"

            answer = yield(string + question)
            if answer.lower() in ["n", "no"]:
                caller.msg("|rSave cancelled.|n")
                return

            # all seems ok. Try to save.
            try:
                prot = protlib.save_prototype(prototype)
                if not prot:
                    caller.msg(f"|rError saving:|R {prototype_key}.|n")
                    return
            except protlib.PermissionError as err:
                caller.msg(f"|rError saving:|R {err}|n")
                return
            caller.msg(f"|gSaved prototype:|n {prototype_key}")

            # check if we want to update existing objects
            existing_objects = protlib.search_objects_with_prototype(prototype_key)
            if existing_objects:
                if 'update' not in self.switches:
                    n_existing = len(existing_objects)
                    slow = " (note that this may be slow)" if n_existing > 10 else ""
                    string = (f"There are {n_existing} objects already created with an older version "
                              f"of prototype {prototype_key}. Should it be re-applied to them{slow}? [Y]/N")
                    answer = yield(string)
                    if answer.lower() in ["n", "no"]:
                        caller.msg("|rNo update was done of existing objects. "
                                   "Use spawn/update <key> to apply later as needed.|n")
                        return
                n_updated = spawner.batch_update_objects_with_prototype(existing_objects, prototype_key)
                caller.msg(f"{n_updated} objects were updated.")
            return

        if not self.args:
            ncount = len(protlib.search_prototype())
            caller.msg("Usage: spawn <prototype-key> or {{key: value, ...}}"
                       f"\n ({ncount} existing prototypes. Use /list to inspect)")
            return

        if 'delete' in self.switches:
            # remove db-based prototype
            match_string = _search_show_prototype(self.args)
            success = None
            if match_string:
                string = f"|rDeleting prototype:|n\n{match_string}"
                question = "\nDo you want to continue deleting? [Y]/N"
                answer = yield(string + question)
                if answer.lower() in ["n", "no"]:
                    caller.msg("|rDeletion cancelled.|n")
                    return
                try:
                    success = protlib.delete_prototype(self.args)
                except protlib.PermissionError as err:
                    caller.msg(f"|rError deleting:|R {err}|n")
                caller.msg("Deletion {}.".format(
                    'successful' if success else 'failed (does the prototype exist?)'))
                return
            else:
                caller.msg(f"Could not find prototype '{self.args}'")
                return

        if 'update' in self.switches:
            # update existing prototypes
            key = self.args.strip().lower()
            existing_objects = protlib.search_objects_with_prototype(key)
            if existing_objects:
                n_existing = len(existing_objects)
                slow = " (note that this may be slow)" if n_existing > 10 else ""
                string = (f"There are {n_existing} objects already created with an older version "
                          f"of prototype {key}. Should it be re-applied to them{slow}? [Y]/N")
                answer = yield(string)
                if answer.lower() in ["n", "no"]:
                    caller.msg("|rUpdate cancelled.")
                    return
                else:
                    n_updated = spawner.batch_update_objects_with_prototype(key, objects=existing_objects)
                    caller.msg(f"{n_updated} objects were updated.")
                    return
            else:
                caller.msg(f"Could not find prototype '{key}'!")
                return

        # A direct creation of an object from a given prototype
        prototype = _parse_prototype(self.args, expect=dict if self.args.strip().startswith("{") else str)
        if not prototype:
            # this will only let through dicts or strings
            return

        if isinstance(prototype, str):
            # A prototype key we are looking to apply
            prototypes = protlib.search_prototype(prototype)
            nprots = len(prototypes)
            if not prototypes:
                caller.msg(f"No prototype named {prototype}.")
                return
            elif nprots > 1:
                caller.msg("Found {} prototypes matching '{}':\n  {}".format(
                    nprots, prototype, ", ".join(proto.get('prototype_key', '')
                                                 for proto in prototypes)))
                return
            # we have a prototype, check access
            prototype = prototypes[0]
            if not caller.locks.check_lockstring(
                    caller, prototype.get('prototype_locks', ''), access_type='spawn', default=True):
                caller.msg("You don't have access to use this prototype.")
                return

        # deserialise the prototype to avoid None or caller location persisting untill next reload
        deserialised_prototype = dict(prototype)
        if "noloc" not in self.switches and ("location" not in prototype or "here" in self.switches):
            deserialised_prototype["location"] = self.caller.location
        elif "noloc" in self.switches:
            deserialised_prototype["location"] = None
        # proceed to spawning
        try:
            for obj in spawner.spawn(deserialised_prototype):
                self.caller.msg(f"Spawned {obj.get_display_name(self.caller)}!")
        except RuntimeError as err:
            caller.msg(err)

```

**Comment by GulliblePsychologist** [comment] 2019-12-22 21:19
See also: #2005

**Comment by GulliblePsychologist** [comment] 2019-12-23 14:49
I had to copy the entire "prototypes" folder to my own project and override the entire prototype spawn menu because I wanted to add a custom property to my objects. (I suspect this will remain because I also have code in there that hides attributes that start with an underscore: I'm using these as private/internal attributes in my code, as I found it difficult to create my own custom fields without throwing myself at Django, which I'm not as familiar with.)

In doing so, I encountered several issues that I thought were caused by me but were actually part of this issue.

* [Line 2412](https://github.com/evennia/evennia/blob/3cc5701f661fcec90ddbec0612e5fb35dd03edc9/evennia/prototypes/menus.py#L2412) of `evennia/prototypes/menus.py` is missing `prototypes=prototypes` as a named parameter to the function `_format_diff_text_and_options` which is causing an error if you try to preserve any values when updating objects.

* The tag with the "from_prototype" category gets erased when you update a prototype. After updating it the first time, the object becomes unique. I added a piece of code that removes the tag with the same name as the "prototype_key".

* Apparently, you can't set tags with the same name in different categories. This seems inconsistent with how tags behave elsewhere. (_Please_ tell me that the unique constraint of tags is based on name+category and not just name. I'm using tags for a custom coordinate system now which supports multiple regions/zones where coordinates may overlap, and this uses the tag system for quicker lookups as recommended on the Evennia wiki.)

* The aforementioned issues with `CmdSpawn`. I've had to apply the same fixes on my own before I found this issue.

**Comment by Griatch** [comment] 2020-01-07 10:49
> Apparently, you can't set tags with the same name in different categories. This seems inconsistent with how tags behave elsewhere. (Please tell me that the unique constraint of tags is based on name+category and not just name. I'm using tags for a custom coordinate system now which supports multiple regions/zones where coordinates may overlap, and this uses the tag system for quicker lookups as recommended on the Evennia wiki.)

Yes, the unique restraint is `tagname + category`. This means that `tagname + None` ("no" category) is also a unique combination. The limitation of setting tags with different categories is likely more a matter of a parsing issue in the OLC than a limit in the tags themselves.

**Comment by Griatch** [comment] 2020-03-28 23:16
All the points have been addressed. The `spawn` command was heavily refactored and cleaned up with a lot of bug fixes throughout. You can use `spawn/raw protfunc` to get the full dict so you can edit and feed it back manually. It will now also differentiate between something being unset and explicitly set to `None` (most commonly for the `location`. 
Closing this, if there are further issues, they belong in new issues.

**Closed by Griatch** 2020-03-28 23:16 UTC
Labels: branch-master, bug
