### ISSUE TITLE
Upgrade to Evennia .7 issues

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#1441] opened 2017-09-21 18:47 UTC
#### Brief summary of issue / Description of requested feature:
Traceback on following the steps on migrating to evennia .7 
Under the header "I have custom code in my game dir and/or a database with important data in it"

#### Steps to reproduce the issue / Reasons for adding feature:
1. Step 9 fails on the process with the traceback below.

#### Error output / Expected result of feature
`Apply all migrations: accounts, admin, auth, comms, contenttypes, flatpages, help, objects, players, scripts, server, sessions, sites, typeclasses
Running migrations:
  Applying typeclasses.0001_initial...Traceback (most recent call last):
  File "/home/evennia/pyenv/bin/evennia", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/evennia/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/evennia/evennia/evennia/server/evennia_launcher.py", line 1336, in main
    django.core.management.call_command(*args, **kwargs)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 303, in create_model
    self.execute(sql, params or None)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1050, "Table 'typeclasses_attribute' already exists")`

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Ubuntu 16.04.2 LTS
MySQL 5.7.19-0ubuntu0.16.04.1

**Comment by Tirit** [comment] 2017-09-22 00:05
So I wiped the db and game, did a full --init again. Got this traceback
`Traceback (most recent call last):
  File "/home/evennia/pyenv/bin/evennia", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/evennia/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/evennia/evennia/evennia/server/evennia_launcher.py", line 1338, in main
    django.core.management.call_command(*args, **kwargs)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 114, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/evennia/evennia/evennia/objects/migrations/0009_remove_objectdb_db_player.py", line 19, in <module>
    class Migration(migrations.Migration):
  File "/home/evennia/evennia/evennia/objects/migrations/0009_remove_objectdb_db_player.py", line 27, in Migration
    if not _table_exists(db_cursor, "objectdb_db_player"):
  File "/home/evennia/evennia/evennia/objects/migrations/0009_remove_objectdb_db_player.py", line 13, in _table_exists
    db_cursor.execute(sql_check_exists)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'evennia_main.objectdb_db_player' doesn't exist")`

**Comment by chainsol** [comment] 2017-09-22 00:22
I'll test this with MySQL on Ubuntu locally, just to see if I can replicate. Tried just now with SQLite and had no problems.

**Comment by chainsol** [comment] 2017-09-22 01:18
Sorry to double post, but this issue seems easy to solve.
It's caused by _table_exists in the various migrations using it - my suggestion is to
A. Move _table_exists to some sort of utils module - it's repeated through many migrations.
B. Catch ProgrammingError in _table_exists - we already catch OperationalError, which is what Sqlite will raise if that SELECT statement fails
OR
C. Change _table_exists to use "return table_name in connection.introspection.table_names()", because this won't raise an exception no matter what.

**Comment by Griatch** [comment] 2017-09-22 08:21
Looks like this will need to be a two-pronged fix:
1.  Fixing the `_table_exists` exception handling (thanks @chainsol, this looks like the culprit)
2. Supply a patch that people can apply at the right place in the git/migration history. 

I'll look at this in the weekend.

**Comment by chainsol** [comment] 2017-09-23 09:42
I tried patching the _table_exists function in the way I suggested, and the migrations worked correctly, on MySQL and SQLite.

**Comment by Griatch** [comment] 2017-09-23 09:51
@tirit, @chainsol : I just pushed a patch file for use with MySQL and PostgreSQL. Due to how the migration works, this must be applied at the right point in the git history, so I updated the install instructions (in the forum post) with extra optional steps for MySQL/PostgreSQL users. Unfortunately I have no easily accessible postgres/mysql master data to migrate so I'm leaving this open until you have a chance to try it out.

**Comment by Griatch** [comment] 2017-09-23 09:52
@chainsol As it turns out your suggestion to use `return table_name in connection.introspection.table_names()` turned out to be important to use with PostgreSQL, nice one!

**Comment by Tirit** [comment] 2017-09-24 03:32
Okay so I'm following the new instructions. When I get to step 7 in the new instructions I do the 'git checkout player-account-step1' and run 'git apply player-account-step1.patch'. 

It gives me a 'fatal: can't open patch 'player-account-step1.patch': No such file or directory'

so I go into my game directory (sense earlier instructions say to copy the file) and run it, and gives me 
error: evennia/comms/migrations/0015_auto_20170706_2041.py: No such file or directory
error: evennia/objects/migrations/0007_objectdb_db_account.py: No such file or directory
error: evennia/objects/migrations/0009_remove_objectdb_db_player.py: No such file or directory
error: evennia/scripts/migrations/0009_scriptdb_db_account.py: No such file or directory
error: evennia/scripts/migrations/0011_remove_scriptdb_db_player.py: No such file or directory

**Comment by Griatch** [comment] 2017-09-24 07:13
You seem to have missed that you should copy the patch to the top of your **evennia** directory, not to the top of the **game** directory. This is why you don't find it when you first try to run it in step 7.

**Comment by Tirit** [comment] 2017-09-24 15:17
I did, I apologize. It was late last night when I tried to do it. 
It worked all the way up to Step 9. The last 'evennia migrate' command gave me this trace back.

`  File "/home/evennia/pyenv/bin/evennia", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/evennia/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/evennia/evennia/evennia/server/evennia_launcher.py", line 1338, in main
    django.core.management.call_command(*args, **kwargs)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/evennia/evennia/evennia/typeclasses/migrations/0010_delete_old_player_tables.py", line 21, in drop_tables
    _drop_table(db_cursor, "players_playerdb")
  File "/home/evennia/evennia/evennia/typeclasses/migrations/0010_delete_old_player_tables.py", line 16, in _drop_table
    db_cursor.execute(sql_drop)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/evennia/pyenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
django.db.utils.IntegrityError: (1217, 'Cannot delete or update a parent row: a foreign key constraint fails')`

**Comment by Griatch** [comment] 2017-09-24 16:29
@Tirit Hm, I take it this is with an existing database and not with a wiped one? Do you think it would be possible for me to take a look at the database you are having trouble with? Because I don't see this error here. I'll make sure to delete the copy once finished testing. :)

**Comment by Tirit** [comment] 2017-09-25 00:40
Page me where I can send a tar.gz of it. 
Also, if it helps I'm getting the following on the command line when someone connects. 

`[twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.
2017-09-25T00:38:38+0000 [twisted.logger._global#warn] /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'.`

**Comment by Griatch** [comment] 2017-09-25 05:05
That is a strange error I don't see here. Which Django version are you using? 
You can send the file to my email, you can see it with the default `about` command.

**Comment by Tirit** [comment] 2017-09-25 14:03
Evennia 0.7.0 (rev b3c6e9d) (rev b3c6e9d)
OS: posix
Python: 2.7.12
Twisted: 17.9.0
Django: 1.11.5
Evennia MUD/MUX/MU* development system

**Comment by Griatch** [comment] 2017-09-25 16:18
Ok, that looks like ok versions. Thanks for the database, I'll take a look as soon as possible. 

The `say` command has no known issues, just tried it and it works fine for me here at least:

    say hello
    You say, "hello"

It's probably unrelated, maybe you modified it somehow in your game dir?

**Comment by Tirit** [comment] 2017-09-25 20:29
Yes. I found the error, completely unrelated.

**Comment by Griatch** [comment] 2017-09-27 20:41
@Tirit I don't know if you saw my e-mail reply but - I got your mail and as far as I could see it didn't actually contain any database file.

**Comment by Tirit** [comment] 2017-09-28 16:14
Whoops...I actually sent it now...this time....

**Comment by Griatch** [comment] 2017-09-30 14:54
@Tirit With the latest version of `master` I can now migrate your database all the way as per the instructions for MySQL. So things should work ok now. Thanks for your patience! I'm closing this now, let me know if any further issues arise. :)

**Closed by Griatch** 2017-09-30 14:54 UTC
Labels: bug, master-branch, ongoing
