### ISSUE TITLE
[BUG] Bug in executing script

### ISSUE THREAD

**Issue by finalcn** [evennia/evennia#2061] opened 2020-02-20 19:19 UTC
Bug in executing script

#### Steps to reproduce the issue / Reasons for adding feature:

1. Bug 1
```python
class BugScript(DoNothing):
    def at_script_creation(self):
        self.interval=1
    def at_repeat(self):
        self.stop()
```
run script self=script.test.BugScript
```
at_repeat()  ''NoneType' object has no attribute 'callcount''
```
2. Bug 2
```python
class BugScript(DoNothing):
    def at_script_creation(self):
        self.interval=1
        self.start_delay=3
    def at_repeat(self):
        pass
```
run script self=script.test.BugScript
```
django.core.exceptions.ValidationError: ["'3' value must be either True or False."]
```

         Evennia version: 0.9.0
         OS: nt
         Python: 3.8.0
         Twisted: 19.7.0
         Django: 2.2.9

**Comment by Griatch** [comment] 2020-02-29 11:27
@finalcn 
- The first script error is caused by the `self.stop()` in the `at_repeat`. I have now fixed so that the system handles that. Note that this particular example could just as well been a function - it will run once and then stop. 
- The second error is not a bug, you are using the wrong type. `start_delay` is (as the error indicates) a boolean that indicates if we should wait `interval` seconds before doing the first repeat or not. See https://github.com/evennia/evennia/wiki/Scripts#properties-and-functions-defined-on-scripts

**Closed** 2020-02-29 11:27 UTC
Labels: bug
