### ISSUE TITLE
Strategy for gradual loading of Objects into memory after reload?

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1033] opened 2016-09-02 01:39 UTC
#### Brief summary of issue / Description of requested feature:
So I have a @roster command, which lists the Character objects of characters, along with various
attributes and so on. The problem I'm running into is that loading all these characters into memory
all at once after a server reload is an extremely expensive operation. On my home PC where I'm running
the old version of Evennia, I'd expect it to take a good 6-8 seconds after a server reload - kind of annoying, but I could deal with that as a once-per-reload deal. But on a digital ocean server I'm spinning up with the new version of Evennia, it's upwards of 30+ seconds. Is there any sort of strategy I could have for gradually loading tagged objects into memory at every server reload? Like some Tag I'd put in them that'd mark that I'd want to get them loaded, even if I don't do it all at once? I'm trying to think of some good way to spread it out so that it's not some crippling operation that locks the database for 30 seconds at a time that continues to spiral up if we get more characters on our roster.

Alternately, maybe having some way of using pagination in commands? It seems strange to use it for a text command, but maybe it'd work for this - like using django.core.paginator and storing it/the current page in an ndb, but I'm not sure what the most elegant way of having players hitting z to continue a scroll or q to cancel it would be from a command's output.

**Comment by Griatch** [comment] 2016-09-02 14:18
@TehomCD 

Hm, that does sound very expensive indeed. How many characters are we talking about, and how do their typeclasses look? Normally, handlers on a typeclass are not actually initialized when it's loaded just for the sake of minimizing upstart (lazy loading). Do you have any expensive at_init or __init__ calls on them maybe? 

My first thought is wondering why you need to load all characters all at once, but I suppose the `@roster` is intended to show all characters all over the server? 

As a first test you could start evennia with `evennia --profiler start`. Let it run so your characters are loaded (try to run as empty a server as possible so only the loading dominates the profile), then call `evennia stop` (you mustn't kill it with a signal or the profiler will balk). You will now have a file `mygame/server/logs/server.prof`. Put that online somewhere I can get to it or email it to me (you find my email using the `@about` command) so I can take a look.

**Comment by TehomCD** [comment] 2016-09-02 19:00
Thanks so much, Griatch! I sent you an email with the server.prof file for executing the @roster command. Intuitively, I'd think some form of limiting the evaluation of the queryset to something smaller (like slices of 25 at a time) might be the best solution since players might appreciate some implementation that doesn't throw hundreds of rows in a table at them all at once anyway, but I'd definitely appreciate any suggestions on how to implement some cmdset that allows players to scroll through a table of a paginated queryset.

**Comment by Griatch** [comment] 2016-09-02 22:58
I've not had time to look at the profile yet, but please answer as to how many characters you are trying to view when you get that 30s delay. Also, how are you viewing them - are you building a list, an Evtable...? How many Attributes are you fetching and displaying per character? Just so I have an idea.

**Comment by TehomCD** [comment] 2016-09-03 07:48
I believe it's 141 characters in the active roster. I have different rosters (available, unavailable, incomplete), and the delay seemed proportional for the number of characters on them (29, 22, and 50, respectively). I didn't have Evtable when I wrote this, so it was a prettytable (I imagine I'll slowly go through and convert anything that's still a prettytable to Evtable eventually), but I believe the delay is entirely from building the model instances - the delay is negligible on subsequent times I enter the command after the objects are already in memory, and the mirror to this command is a view on the webpage that displays the roster as a table, with a similar delay the first time the page is loaded after a server reload, then no delay at all at subsequent views. I believe it's around 5 attributes per character for the other columns.


________________________________

**Comment by Griatch** [comment] 2016-09-03 07:57
Thanks. As an experiment, could you set `settings.TYPECLASS_AGGRESSIVE_CACHE` to `False`. Does that in any way affect the perceived slowdown? Please also send me the profile of this as before if you may.

**Comment by TehomCD** [comment] 2016-09-03 08:15
Here's the newest profile:


________________________________

**Comment by Griatch** [comment] 2016-09-03 08:35
So (as discussed in IRC) this revealed an issue with `settings.TYPECLASS_AGGRESSIVE_CACHE=False` rather than offering any solution. :) 

The profile (with cache on) is dominated by waiting for I/O but there is also an aspect of the attribute caching done on first access. So I'll look into that to see if I can make the aggressive cache a little smarter. That said, it's still pretty useless to load all characters if you can't fit them on the same screen anyway.

You yourself already mentioned the use of the paginator for queries. That's a good start. Evennia offers the `evennia.utils.evmore.EvMore` utility for splitting output into multiple pages. But EvMore requires the full text beforehand as far as I remember, which is not what you want - you want to be able to load just the bits you want as you flip pages. Maybe you can look at EvMore and see if you can add a more gradual loader to it?

**Comment by TehomCD** [comment] 2016-09-03 08:51
Thank you for pointing out EvMore - the structure of the command is what I had in mind, so maybe I can write something to extend it where it'll accept a paginator object (or just a queryset or iterable and number for how many should be per page?) and a callable to generate the text display for a given page.

**Comment by Griatch** [comment] 2016-09-03 10:33
Being sure just where slowdown happens in an asynchronous environment is not trivial. To test the database performance and caching I made a simple test. And I *can't* replicate this slowdown behavior you see. Here is the test I performed:

```python
# in mygame/typeclasses/objects.py
[...]

class TestObject(Object):
    def at_object_creation(self):
        self.db.test1 = "A"
        self.db.test2 = "B"
        self.db.test3 = "C"
        self.db.test4 = "D"
        self.db.test5 = "E"

# in mygame/commands/command.py

class CmdViewTestObject(default_cmds.MuxCommand):
    key = "viewtestobj"
    def func(self):
        from typeclasses.objects import TestObject
        objects = TestObject.objects.all()
        string = ""
        for obj in list(objects):
            string += "\n%s: %s, %s, %s, %s, %s" % (obj.key, obj.db.test1, obj.db.test2,
                                                    obj.db.test3, obj.db.test4, obj.db.test5)
        self.caller.msg(string)
```

So a simple object with the simplest possible command to view all such objects and all its attributes. 

I then added the `viewtestobj` command to the default cmdset and went into the game and created 200 `TestObjects` in `None` locations (so they are not cached when the location I'm in loads):

```
    @py [evennia.create_object("typeclasses.objects.TestObject", key="test%i" % i) for i in range(200)]
```

I then `@reload` ed the game to clear all caches and ran 

```
@py/time self.execute_cmd("viewtestobj")
```

(I use `@py/time` in order to get timings). The result is that list of 200 objects, each listing five attributes, takes 1100 ms (1.1s) to display the first time and 50ms thereafter. So it's a slight hickup the first time but nothing too troublesome since it only happens the first call. So this at least seems to suggest the database access is not necessarily the critical factor. 

Could you maybe try the same test, see if you see the same performance? If you do, you could then try the same simple thing but load one of your custom typeclasses, see where things start to hog down.

**Comment by Griatch** [comment] 2016-09-03 10:49
Update: Using the same code as above I let each of the 200 objects get 50 random attributes instead of just four. 
With the same procedure I now get that the first display of 5 attributes takes 9700ms (9.7s) which is a lot more noticeable. It's now loading and caching 10 000 rows from the database at once, so it's maybe not too surprising ... but it's still not near @TehomCD 's 30+ seconds.

**Comment by TehomCD** [comment] 2016-09-03 11:23
For the first test, 1932ms for the initial load, then 50ms thereafter. Out of curiosity, I did timings on retrieving the queryset for my roster without evaluation (34 ms), evaluating it by casting it to list() (71 ms), and then retrieving an attribute from each object in the queryset: 28000 when fresh, 138ms for subsequent calls. Doing a ", ".join(ob.key for ob in queryset) is 30ms, while ", ".join(ob.db.attr for ob in queryset) is 900 or so times that. Doing ", ".join(str(ob.db.foo) for ob in queryset) took 22917ms, for searching an attribute that doesn't exist.

**Comment by Griatch** [comment] 2016-09-03 11:26
@TehomCD 

How many attributes do you have per object in your roster?

**Comment by TehomCD** [comment] 2016-09-03 11:31
Iterating through them all and adding up the len(ob.attributes.all()) gave me 9013 attributes.

**Comment by Griatch** [comment] 2016-09-03 11:35
Hm that's still in the ballpark of my test where I assign 200 x 50 = 10000 Attributes and still see a timing of about 10 seconds for displaying them rather than 30. That difference must be due to some other initialization you are doing somewhere but I can't really say for sure. 

The cause for the difference between displaying .key and .db.attrname is due to the AttributeHandler creating its cache on first access. This means it's currently retrieving *all* attributes attached to this object and caching them. This is the reason subsequent access is so much faster. #1034 will explore if this caching can be done more gradually.

**Comment by TehomCD** [comment] 2016-09-03 11:39
If the attributes point to other objects, would that cause additional loading? Probably a good number of attributes inside characters point to other typeclasses for some operation or another, and wasn't sure if they're just saved as IDs or what in the attributes.

**Comment by Griatch** [comment] 2016-09-03 11:42
No, that should not matter for the cache. What is loaded into the AttributeHandler cache is the Attribute object itself, not its value - so a stored database object would only be loaded once the value of that Attribute was actually accessed.

**Comment by Griatch** [comment] 2016-09-03 11:50
Just to test if the number of Attributes/obj was the bottleneck, Imade 200 objects each with 80 attributes. Displaying the list takes me 15 seconds which seems to be roughly to scale and still a lot faster than what you see.

**Comment by Griatch** [comment] 2016-09-03 18:07
@TehomCD 

So I experimented with an alternative caching strategy for for Attributes and pushed this scheme onto master just recently. 
With this gradual caching scheme I can load and view 200 objects, each with 80 attributes, in 2.1 seconds (down from 15s previously) while still retaining the same speed after that. I would be interested in seeing if it helps your case.

**Comment by Griatch** [comment] 2016-09-03 20:13
What do you mean by exit aliases not working? I just tested `@dig kitchen = north;n,south;s and the aliases s/n works just fine? Can you give an example?

**Comment by TehomCD** [comment] 2016-09-03 20:17
Any pre-existing room that I enter won't have aliases for the exits work for the exit commands, only the exit's key. For example, I enter a room with 'north, south, southeast, east', etc, and I can use any of those, but 'n', 's', 'se', 'e', etc, all fail. The game owner/head builder established a convention where he also abbreviates exits, so something might be, 'Palace Main Entrance <PE>', and while I could do 'plaza main entrance <pe>', I can't use the alias 'pe' that's built into it.

**Comment by Griatch** [comment] 2016-09-03 20:21
Are you sure you have properly restarted the server after upgrading? This is just a caching change - caching is per definition not stored in the database so it should not matter if you created the room before or after this change.

**Comment by TehomCD** [comment] 2016-09-03 20:26
This is very odd. For a test case, one of the first exits we made was off from Limbo going to our staff lounge, with the alias 'sl'. I can 'look sl', and 'examine sl', but 'sl' isn't available as an alias to its exit command. Examining the exit doesn't show any aliases, but I can use them for look/examine. I wonder if I made an error in converting over aliases from my old database or something.

**Comment by Griatch** [comment] 2016-09-03 21:58
The alias issue turned out to be an issue with the tag.category after a conversion from an older version, and was unrelated to the caching changes. While paging of a large number of objects is still relevant, I think the speedup from the caching makes things a lot more manageable. So closing this.

**Closed by Griatch** 2016-09-03 21:58 UTC
Labels: ongoing
