### ISSUE TITLE
Webclient sends commands prematurely 

### ISSUE THREAD

**Issue by DauntlessAutumn** [evennia/evennia#894] opened 2015-12-05 09:26 UTC
The webclient is sending commands at an unknown interval. Approximately every minute or two.

This happens in Chrome and Opera (both recently updated) on Windows 10. It happens regardless of whether or not the command line has focus (while I'm typing, while the window is minimised, or when another window or tab has focus). 

This is frustrating, especially with admin commands. @desc's get cut off halfway through, then I need to @desc/edit and append the ending. 

I noticed this issue nearly immediately after install, before any changes were made to code, and I haven't changed any settings. 

This doesn't happen in other applications, or other Web apps. 

I'm hoping this is just a setting I couldn't see. 

Thanks in advance!

**Comment by Griatch** [comment] 2015-12-05 11:59
Hm, I can see it too ... no there is no setting since it's not intended behavior :) Not sure why it suddenly does that, will need to investigate closer.

**Comment by Griatch** [comment] 2015-12-16 15:51
Delaying this for now, awaiting a generally revamped webclient infrastructure.

**Comment by Griatch** [comment] 2016-02-24 14:27
This will be resolved when the `wclient` devel branch merges.

**Comment by Griatch** [comment] 2016-05-22 20:31
Closed as wclient branch has merged.

**Closed by Griatch** 2016-05-22 20:31 UTC
Labels: bug, devel, implemented
