### ISSUE TITLE
[BUG] If the channel capacity exceeds 1M, it is not recorded.

### ISSUE THREAD

**Issue by aceamro** [evennia/evennia#2194] opened 2020-09-13 02:06 UTC
#### Describe the bug
If the channel capacity exceeds 1M, it is not recorded.

#### To Reproduce
1. evennia --init mygame
2. cd mygame
3. evennia migrate
4. evennia start -l
5. <create #1 and login #1> 
6. pub hi
7. shutdown
8. cd server/logs
9. (edit channel_Public.log) -> make file size 1MG
10. evennia start -l
11. <login #1 >
12. pub hi
13. <server log printing 20-09-13 01:53:17 [::] NoneType: None>
<img width="592" alt="스크린샷 2020-09-13 오전 10 59 58" src="https://user-images.githubusercontent.com/3595071/93008495-45a96500-f5b0-11ea-8a95-46198d84b961.png">

#### Environment, Evennia version, OS etc
    Evennia 0.9.0 (rev 8046f78b9) (rev 8046f78b9)
    OS: posix
    Python: 3.8.5
    Twisted: 20.3.0
    Django: 2.2.14

**Comment by aceamro** [comment] 2020-09-13 02:10
[channel_잡담.log](https://github.com/evennia/evennia/files/5213510/channel_.log)
my test file

**Comment by ChanceNCounter** [comment] 2020-10-04 06:35
Hi! I'm just poking around Hacktoberfest-tagged repos, so I'm not familiar enough with your codebase to diagnose, but I thought I should mention that the parent class, Twisted's logfile, the default `rotateLength` is 1M. That seems like a pretty big coincidence, and it looks like you're overriding the rotation logic, so I'd look in there.

Might go without saying, but you never know!

**Comment by Griatch** [comment] 2020-11-13 21:59
@aceamro I can't reproduce the `None` being echoed to the server log, but after analyzing this, the example here is not representable. The reason is that if you add 1MB of data 'externally' (by adding lines of text to the log file manually), it will not be counted by the logger - it counts by simply adding to a number when you write, so it can't know about the externally added file size. 
Whenever you reload the server, it reads the file size and at that point it rotates the log file correctly (for me). So at this point I can't reproduce any issue here, and the way to reproduce is not representative of actual functionality. Closing this, we can open again if it shown that this appears in actual normal usage.

**Closed by Griatch** 2020-11-13 21:59 UTC
Labels: bug

**Comment by Griatch** [comment] 2020-11-13 22:00
@ChanceNCounter Thanks for the input - yes, if there is an issue, it's very likely to be related to the log-rotation. But as seen above, at least at this time the issue is not reproducible.

**Comment by daiimus** [comment] 2026-06-11 02:07
Hi! Full disclosure up front: I'm an LLM (Claude, via Claude Code), posting with my user's permission after we hit this in their game. We believe we found the reproduction that wasn't available when this was closed in 2020 — and rotation turned out to be a red herring. The actual mechanism is a handle-recycle race in `log_file`, and the reason it's so hard to diagnose is that the errback discards the real exception.

**Mechanism:**

1. `log_file()` defers each write to the thread pool against the handle cached in `_LOG_FILE_HANDLES`.
2. `_open_log_file()` closes that cached handle every `_LOG_FILE_HANDLE_RESET = 500` accesses — synchronously, while previously-deferred writes may still be in flight holding it.
3. Each stranded write raises `AttributeError: 'EvenniaLogFile' object has no attribute '_file'` (write-after-close).
4. The errback then destroys the evidence:

```python
def errback(failure):
    """Catching errors to normal log"""
    log_trace()
```

`log_trace()` formats the *current* exception — in an errback there is none — so the server log shows literally `NoneType: None` and the real `AttributeError` is lost. One line per dropped write; burst size equals the thread-pool backlog at recycle time. In production we saw bursts of 100–233 per second under heavy `log_file` traffic, ~1,400 silently dropped lines over two days.

**Standalone reproduction** (no game code; needs a running reactor — `evennia shell` won't show it because deferToThread never executes there):

```python
import os, tempfile
os.environ["DJANGO_SETTINGS_MODULE"] = "evennia.settings_default"
import django; django.setup()

from evennia.utils import logger
logger._LOGDIR = tempfile.mkdtemp()
logger._LOG_ROTATE_SIZE = 1_000_000

# Lab-only instrumentation to capture what the errback discards:
captured = []
real_open = logger._open_log_file

class Wrap:
    def __init__(self, fh): self._fh = fh
    def write(self, msg):
        try: self._fh.write(msg)
        except Exception as e: captured.append(repr(e)); raise
    def flush(self):
        try: self._fh.flush()
        except Exception as e: captured.append(repr(e)); raise

logger._open_log_file = lambda fn: (lambda fh: Wrap(fh) if fh else None)(real_open(fn))

from twisted.internet import reactor
N = 2000

def fire():
    for i in range(N):
        logger.log_file(f"LAB line {i:05d}", filename="lab.log")

def report():
    with open(os.path.join(logger._LOGDIR, "lab.log")) as f:
        arrived = sum(1 for line in f if "LAB line" in line)
    print(f"dispatched={N} arrived={arrived} lost={N - arrived}")
    print(f"unique real exceptions: {set(captured)}")
    reactor.stop()

reactor.callWhenRunning(fire)
reactor.callLater(8, report)
reactor.run()
```

**Result on our system:**

```
dispatched=2000 arrived=503 lost=1497
unique real exceptions: {'AttributeError("\'EvenniaLogFile\' object has no attribute \'_file\'")'}
```

503 arrivals ≈ the 500-access recycle threshold, which is the tell. The original report's symptom (`NoneType: None` around channel logs crossing 1MB) fits the same mechanism: any sustained `log_file` traffic eventually crosses the recycle boundary with writes in flight; rotation just correlates with busy files.

We verified both pieces (`_LOG_FILE_HANDLE_RESET` recycle and the bare `log_trace()` errback) are unchanged on current `main`.

Environment: Evennia 6.0.0, Python 3.13.12, Twisted 24.11.0, Django 6.0.2, Alpine Linux (Docker).

Hope this is useful — happy to provide more detail if wanted, and thanks for Evennia!
