### ISSUE TITLE
[BUG - Develop] Prototype spawner breaks on "unknown parsed function"

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2769] opened 2022-06-16 04:08 UTC
#### Describe the bug
I'm trying to spawn objects that have funcparser $funcs in an attribute string, in order to use that string in use emotes later. However, the prototype spawner crashes and burns hard whenever it encounters one of those in a string.

For example:
```
    File "./mods/shops/vendors.py", line 147, in _spawn
      obj = spawn(proto)[0]
    File "./evennia/evennia/prototypes/spawner.py", line 1022, in spawn
      init_spawn_value(value, caller=caller, prototype=prototype),
    File "./evennia/evennia/prototypes/prototypes.py", line 1133, in init_spawn_value
      result = protfunc_parser(value, caller=caller, prototype=prototype)
    File "./evennia/evennia/prototypes/prototypes.py", line 962, in protfunc_parser
      result = FUNC_PARSER.parse(value, raise_errors=True, return_str=False, caller=caller, **kwargs)
    File "./evennia/evennia/utils/funcparser.py", line 511, in parse
      exec_return = self.execute(
    File "./evennia/evennia/utils/funcparser.py", line 244, in execute
      raise ParsingError(
  evennia.utils.funcparser.ParsingError: Unknown parsed function '$gp(their)' (available: 'protkey', 'eval', 'add', 'sub', 'mult', 'div', 'round', 'toint', 'random', 'randint', 'choice', 'pad', 'crop', 'just', 'ljust', 'rjust', 'cjust', 'justify', 'justify_left', 'justify_right', 'justify_center', 'space', 'clr', 'search', 'obj', 'objlist', 'dbref')
```
In this case, `$gp` is a custom funcparser I've added, which works perfectly well in all of the others contexts I'm using it. None of the other caller/receiver functions are there (of course) so I would expect they would break it the same way, e.g. `$conj(throw)`

#### Expected behavior
I'd expect it to work the same way the funcparser does in other contexts.

#### Develop-branch commit
6edf9064c

#### Additional context
Based on this bit:
```py
result = FUNC_PARSER.parse(value, raise_errors=True, return_str=False, caller=caller, **kwargs)
```
It looks like it's explicitly set to raise errors instead of ignoring invalid functions? Maybe we could have that as a kwarg option on `spawn` that gets passed along, instead of hardcoded? I could see the issue I'm having coming up again, once more people are using the new funcparser utility.

Barring that: the initial solution which I looked for was actually some way to escape the functions, so that they would just be parsed from the escaped version to `$func` after the spawner was done with it and before it was applied to the object.

**Comment by Henddher** [comment] 2022-10-16 21:38
Hi folks,

Is anyone working on a PR for this issue? If not, I can take a stab at it although I am not familiar with prototype functions. 

It seems like there are multiple "issues" at play here? e.g. kwargs to opt-in/out exceptions, escaping, time when the function is "executed"?

What should the expected behavior be and under which conditions? I.e. what are the use-cases?

**Comment by InspectorCaracal** [comment] 2022-10-17 01:34
I came up with a workaround so I wasn't tracking this, I'll re-check the situation and let you know

**Comment by Griatch** [comment] 2022-10-23 09:37
Closing this. Protfuncs must not be unknown and it makes sense to property catch errors for them. For funcparser methods to be avaliable to the prototype spawner, they must be added to `settings.PROT_FUNC_MODULES`, which is a separate thing from the body of `FUNC_PARSER_*` settings.

**Closed by Griatch** 2022-10-23 09:37 UTC
Labels: bug, branch-develop

**Comment by Griatch** [comment] 2022-10-23 09:55
I added `protfunc_raise_errors`, but to be  clear, this was not a bug.
