### ISSUE TITLE
Develop: A blocking error on startup will create an infinite loop in the launcher

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1600] opened 2018-03-29 08:07 UTC
#### Brief summary of issue / Description of requested feature:

When there's a SyntaxError, NameError, or another exception that prevents the game from loading, the launcher just sits and no error appears.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a new empty game structure with `evennia --init mygame`, `evennia migrate` and a first `evennia start / stop`.
2. Change a file so it will create a blocking error like a SyntaxError.
3. Launch Evennia with `evennia start`.

#### Error output / Expected result of feature

None.  The server is still loading and it keeps on trying.

    Server starting  ...

The console doesn't return.  Worse, nothing appears in any of the log files.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- Evennia develop.

**Comment by Griatch** [comment] 2018-08-19 09:11
@vlegoff  I can't reproduce this. All syntax errors I introduce in the game dir will lead to normal tracebacks in the log or when I connect. Could you check if you can still reproduce this and if so give me an example where you see this infinite-loop behavior?

**Comment by vlegoff** [comment] 2018-08-19 12:05
@griatch: I do see the error in log (if I introduce a syntax error in `conf/server/at_server_startstop.py` for instance, I get the exception in `server/logs/server.log`).  However in the console, the launcher never responds and `evennia start` seems to "block" from the user point of view without returning any error:

```
(pyenv) C:\Users\Vincent\mygame>evennia start
Portal starting ...
... Portal started.
Server starting  ...
```

One has to kill the launcher with `CTRL + C`.  It might be a desirable behavior, I'm not sure.

**Comment by Griatch** [comment] 2018-08-19 13:41
This is unavoidable since the launcher is waiting for a response from the process, but said process has crashed and will not be returning anythin.That you need to look into the log for the cause is standard, expected behavior. Closing.

**Closed by Griatch** 2018-08-19 13:41 UTC
Labels: bug, develop-branch, more info needed
