### ISSUE TITLE
Usage Error Post Fresh Installation

### ISSUE THREAD

**Issue by ccubed** [evennia/evennia#1743] opened 2018-11-10 14:44 UTC
#### Brief summary of issue / Description of requested feature:

I've installed Evennia on Arch Linux and I'm encountering issues attempting to add any kind of thing through the web interface. I receive some variation of the error: NoReverseMatch. The specifics change slightly depending on the subtype of object.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Install fresh evennia on arch
2. Init new game
3. Migrate, start
4. Attempt to make a room, object 
5. Error

#### Error output / Expected result of feature

https://imgur.com/a/pAPhgVc

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Branch: latest git as per git clone https://github.com/evennia/evennia.git
OS: Linux Vertinext 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

**Comment by strikaco** [comment] 2018-11-13 00:29
Interesting. This can be reproduced on the dev branch. I tried creating a generic object "toilet" and dropping it in Limbo and it yields the same error.

**Comment by chainsol** [comment] 2018-11-13 01:06
Looks like a reverse URL mistake, didn't we change that recently so typeclasses were meant to support get_url?

**Comment by strikaco** [comment] 2018-11-13 17:37
I've reproduced the same issue on the current master build. Same workflow-- creating a generic object and setting location to Limbo via admin panel yields NoReverseMatch.

This seems to only impact typeclassed objects; Help entries can still be created without issue.

**Comment by ccubed** [comment] 2018-11-13 17:41
@chainsol Yes, master. Sorry about the wait in reply.

**Comment by strikaco** [comment] 2018-11-14 22:35
There seems to be an inconsistency between the update/create workflows for typeclassed objects. When an object is created, `obj.set_class_from_typeclass(typeclass_path=obj.db_typeclass_path)` [[source](https://github.com/evennia/evennia/blob/40e4a6a59fe9abae864545cb99b40d1ca14deec1/evennia/objects/admin.py#L158)] is called on the new object which sets the object app label to something that ends up being not routable by the url handler.

```
# (create object)
>>> obj._meta.label
u'objects.ObjectDB'
>>> obj.set_class_from_typeclass(typeclass_path=obj.db_typeclass_path)
>>> obj._meta.label
u'typeclasses.Object'
```

By default, Django admin routing breaks a string like `objects.ObjectDB` into a path:action format, like `objects_objectdb_change`. But given the string `typeclasses.Object` as set by the above function, `typeclasses_object_change` will not get routed since 'typeclasses' is not a valid application.

While possible, I don't think the above function is entirely at fault though-- I believe the problem manifests itself when we inconsistently override Django's behavior [later on](https://github.com/evennia/evennia/blob/40e4a6a59fe9abae864545cb99b40d1ca14deec1/evennia/objects/admin.py#L164).

```
    def response_add(self, request, obj, post_url_continue=None):
        if '_continue' in request.POST:
            from django.http import HttpResponseRedirect
            from django.core.urlresolvers import reverse
            return HttpResponseRedirect(reverse("admin:objects_objectdb_change", args=[obj.id]))
        return super(ObjectDBAdmin, self).response_add(request, obj, post_url_continue)
```

When objects are updated, they get the `HttpResponseRedirect` result-- this ignores what Django wants to do with `typeclasses_object_change` and always routes to `objects_objectdb_change`.

But when objects are created, they get the *parent's* `response_add` result, which incorrectly tries to reverse `typeclasses_object_change`.

Applying a fix is where I'm less sure of myself. One can work around the issue by getting rid of the `if` condition and making all responses return the HttpResponseRedirect result-- this solves the problem and allows new objects to be created, but returns the user to the change page without any messages or anything. I also don't know what other impact this has on anything, or if the `set_class_from_typeclass` thing also needs to be addressed.

**Comment by Griatch** [comment] 2019-06-10 05:49
I examined the change suggested by @strikaco and could not find any issues with the typeclassed entitiy created this way. Thanks for the detailed analysis! Sped up resolving this a lot. Also made the same change to the other typeclasses. 

Resolved in `develop` branch, will close once it merges to master.

**Closed** 2019-06-29 16:49 UTC
Labels: bug, develop-branch, implemented, master-branch, web
