### ISSUE TITLE
Bug: The server cannot be shut down properly in interactive mode (Win/Mac only)

### ISSUE THREAD

**Issue by luyijun** [evennia/evennia#1191] opened 2017-02-03 13:21 UTC
#### Brief summary of issue / Description of requested feature:
I created a new game and started the server in interactive mode with the -i flag, then I pressed ctrl-c to stop the server. The server process cannot not be shut down properly. But if I start the server in normal mode or the second time I start the server in interactive mode, the server works right and can be shut down properly.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use evennia --init game to create a new game.
2. Use evennia migrate and use evennia -i start to start the game.
3. Use ctrl-c to stop the server.

#### Error output / Expected result of feature
Use ps -ef|grep evennia, you can see the server process is still running.

**Comment by Griatch** [comment] 2017-02-03 14:00
Which OS is this?

**Comment by luyijun** [comment] 2017-02-03 14:11
I use Mac and one of my friends uses Win10. We both got this problem.

**Comment by Griatch** [comment] 2017-02-04 11:26
Hm, this works perfectly on Linux.

**Comment by CloudKeeper1** [comment] 2017-02-08 08:17
I can confirm the issue on Windows 8: https://www.irccloud.com/pastebin/8zPM7Xwh/
It just hangs, I never get the command line back to even check whether the process is running.
The repeating messages at the end is where pressing enter stops working and pressing CTRL-C repeats the message.

**Comment by luyijun** [comment] 2017-02-08 14:27
I tried on a linux server and could not see this bug. But I tried on my macbook(OS X 10.10.5) and could see this bug again.

**Comment by vlegoff** [comment] 2017-03-31 01:52
On Windows 10, I don't seem to get the issue, though I need to use `CTRL + C` several times.  Here's the output I get when the server is in interactive mode and I press `CTRL + C`:

```
2017-03-30T18:46:24-0700 [-] Received SIGINT, shutting down.
2017-03-30T18:46:24-0700 [-] (TCP Port 5001 Closed)
2017-03-30T18:46:24-0700 [-] (TCP Port 5000 Closed)
2017-03-30T18:46:24-0700 [-] Main loop terminated.
2017-03-30T18:46:24-0700 [-] Server Shut Down.
2017-03-30T18:46:24-0700 [twisted.application.app.AppLogger#info] Server Shut Do
wn.
Terminate batch job (Y/N)? Terminate batch job (Y/N)?
^C^C
^C(Obs: You can use a single Ctrl-C to skip Windows' annoying 'Terminate batch j
ob (Y/N)?' prompts.)
Evennia: The Portal does not seem to be running.

    STOP: Caught keyboard interrupt while in interactive mode.

Terminate batch job (Y/N)?
^C
C:\...> 
```

It seems to me the messages are in the wrong order.  Notice that I didn't press `y` when asked if I wanted to terminate batch job.  This is a weird Windows message that occurs when pressing `CTRL + C` and answering `yes` seems to upset Evennia for some reason.  The same thing happens in Evennia server in "normal" mode.

**Comment by Griatch** [comment] 2018-01-27 14:41
The interactive mode is going away in `develop` branch. So this issue will not be addressed.

**Comment by Griatch** [comment] 2019-03-31 19:41
This is long overdue for closing since the interactive mode works very differently now.

**Closed by Griatch** 2019-03-31 19:41 UTC
Labels: OS/DB-dependent, bug, master-branch, on hold
