### ISSUE TITLE
[BUG] "@examine" an object with an .ndb of None produces no output and logs an error

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3622] opened 2024-09-23 16:15 UTC
#### Describe the bug
If an object has an .ndb attribute with a value of None, '@examine' breaks.

#### To Reproduce
1. `py self.ndb.test=None`
2. `@examine self`
3. See error

#### Expected behavior
.ndb attributes should be able to be set to None and not have any issues.

#### Environment, Evennia version, OS etc
         Evennia version: 4.3.0 (rev f2a5c5a85a)
         OS: posix
         Python: 3.11.9
         Twisted: 23.10.0
         Django: 4.2.13

#### Additional context
Server log:

```
2024-09-23 14:56:47 [!!] Unhandled error in Deferred:
2024-09-23 14:56:47 [!!] 
	Traceback (most recent call last):
	  File "/Users/redacted/evennia/commands/cmdhandler.py", line 629, in _run_command
	    ret = cmd.func()
	  File "/Users/redacted/evennia/commands/default/building.py", line 3172, in func
	    ).addCallback(_get_cmdset_callback)
	  File "/Users/I561397/Desktop/muddev/evenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 620, in addCallback
	    return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
	  File "/Users/I561397/Desktop/muddev/evenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 533, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/I561397/Desktop/muddev/evenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
	    current.result = callback(  # type: ignore[misc]
	  File "/Users/redacted/evennia/commands/default/building.py", line 3160, in _get_cmdset_callback
	    self.msg(self.format_output(obj, current_cmdset).strip())
	  File "/Users/redacted/evennia/commands/default/building.py", line 3005, in format_output
	    objdata = self.get_formatted_obj_data(obj, current_cmdset)
	  File "/Users/redacted/evennia/commands/default/building.py", line 2989, in get_formatted_obj_data
	    objdata["Non-Persistent Attributes"] = self.format_nattributes(obj)
	  File "/Users/redacted/evennia/commands/default/building.py", line 2882, in format_nattributes
	    sorted(self.format_single_attribute(attr) for attr in ndb_attr)
	  File "/Users/redacted/evennia/commands/default/building.py", line 2882, in <genexpr>
	    sorted(self.format_single_attribute(attr) for attr in ndb_attr)
	  File "/Users/redacted/evennia/commands/default/building.py", line 2853, in format_single_attribute
	    if value is None and attr.strvalue is not None:
	  File "/Users/redacted/evennia/typeclasses/attributes.py", line 65, in <lambda>
	    strvalue = property(lambda self: self.db_strvalue)
	builtins.AttributeError: 'InMemoryAttribute' object has no attribute 'db_strvalue'
```

**Comment by InspectorCaracal** [comment] 2024-09-23 16:18
Looks like the cause behind #3602

**Comment by aMiss-aWry** [comment] 2024-09-23 16:26
I stuck an `self.db_strvalue = None` around https://github.com/evennia/evennia/blob/f2a5c5a85a7858b24141b8ddbb79ff16eb390308/evennia/typeclasses/attributes.py#L138

and it fixed my problem. I'm not knowledgable enough to know if that has negative implications down the line, though.

**Comment by aMiss-aWry** [comment] 2024-09-23 16:30
Actually, I think I have a better solution:
`        if value is None and attr.strvalue is not None:` -> `        if value is None and hasattr(attr, "strvalue") and attr.strvalue is not None:
`
as it feels a bit less funky than setting strvalue to None by default. I'll submit a PR.

**Comment by InspectorCaracal** [comment] 2024-09-23 16:35
Maybe `if value is None and getattr(attr, "strvalue", None) is not None:` to be a little more concise? 🤔

**Comment by Griatch** [comment] 2024-09-29 08:25
Merged and fixed.

**Closed by Griatch** 2024-09-29 08:25 UTC
Labels: bug, needs-triage
