### ISSUE TITLE
[BUG - Develop] Whitespace is collapsed when `FuncParser` input raises error and returns "unparsed" string

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2927] opened 2022-10-10 22:03 UTC
#### Describe the bug
The intended behavior of FuncParser is to return an input string verbatim if `raise_errors=False` and there is an exception when parsing. However, currently whitespace is collapsed in multi-argument function calls.

#### To Reproduce
Test that demonstrates this issue:

```
    def test_parse_whitespace_preserved(self):
        string = "The answer is $add(1, x)"
        ret = self.parser.parse(string)
        self.assertEqual("The answer is $add(1, x)", ret)
```

Failure message

```
======================================================================
FAIL: test_parse_whitespace_preserved (evennia.utils.tests.test_funcparser.TestFuncParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tmoney/code/evennia/evennia/utils/tests/test_funcparser.py", line 258, in test_parse_whitespace_preserved
    self.assertEqual("The answer is $add(1, x)", ret)
AssertionError: 'The answer is $add(1, x)' != 'The answer is $add(1,x)'
- The answer is $add(1, x)
?                      -
+ The answer is $add(1,x)
```

#### Expected behavior
The test passes.

#### Develop-branch commit
b0f24f9975e14fddeabef06a19b5b61575957b1c

#### Additional context
This was discovered when writing tests in https://github.com/evennia/evennia/pull/2918

**Comment by Griatch** [comment] 2022-10-23 10:34
While this is technically working as intended, I can agree it breaks the promise of returning the input verbatim, so it can look strange and confuse the user. So while the whitespace should remain compressed for the sake of execution, we need to preserve the original for the verbatim output.

**Comment by Griatch** [comment] 2022-11-06 15:40
This was a lot tricker to resolve than expected; there are a lot of edge cases to this, such as not properly closing a function list, but starting a second (valid) function within that list - trying to preserve whitespace becomes pretty tricky for those cases. But it should be working as advertised now.

**Closed by Griatch** 2022-11-06 15:40 UTC
Labels: bug, branch-develop
