### ISSUE TITLE
[BUG] Restarting script with interval 0 yields ZeroDivisionError

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2039] opened 2020-01-27 20:57 UTC
#### Describe the bug
Calling `self.restart(interval=0, repeats=0, start_delay=False)` on a script seems to be resulting in a ZeroDivisionError.

#### Environment, Evennia version, OS etc
```
Evennia version: 0.9.0 (rev a27a8c3d)
         OS: posix
         Python: 3.7.6
         Twisted: 19.10.0
         Django: 2.2.9
```
#### Additional context
```
20-01-27 20:45:33 Unhandled error in Deferred:
20-01-27 20:45:33 Unhandled Error
        Traceback (most recent call last):
          File "/home/ubuntu/CLOWN/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/home/ubuntu/workspace/evennia/evennia/server/amp_client.py", line 236, in server_receive_adminportal2server
            server_sessionhandler.server.shutdown(mode="reload")
          File "/home/ubuntu/CLOWN/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/ubuntu/CLOWN/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/ubuntu/CLOWN/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/ubuntu/workspace/evennia/evennia/server/server.py", line 418, in shutdown
            for s in ScriptDB.get_all_cached_instances()
          File "/home/ubuntu/workspace/evennia/evennia/server/server.py", line 419, in <listcomp>
            if s.is_active or s.attributes.has("_manual_pause")
          File "/home/ubuntu/workspace/evennia/evennia/scripts/scripts.py", line 517, in pause
            self.db._paused_time = task.next_call_time()
          File "/home/ubuntu/workspace/evennia/evennia/scripts/scripts.py", line 141, in next_call_time
            return interval - (total_runtime % self.interval)
        builtins.ZeroDivisionError: float modulo
```

**Comment by Oscuro87** [comment] 2020-01-28 14:47
Hello.

Basically, from what I read in the source, it accepts 0 in the `restart` function, stores it into the ExtendedLoopingCall (ELC) instance, as `self.interval`.
But then another function in ELC, called `next_call_time`, reads `self.interval` and uses it in a modulo (%), as the divisor part, hence the bug.

You can try a quick fix by going into evennia/evennia/scripts.py, then after the line 141, reading:
```python
interval = self.start_delay or self.interval
```

Add:
```python
if self.interval == 0:
                self.interval = 1
```

But I'm not sure if any side effect will arise from this (yet) :thinking: 

Or, you can pass 1 :rocket:

**Comment by Griatch** [comment] 2020-01-28 14:51
0 means turning off the interval, so setting it to 1 (1s interval) does sound like a pretty bad idea. Rather the whole next_call_time should be disabled in this case. 
This is a regression btw; 0 is a better value for this  than -1, but clearly a bug snuck in.

**Comment by Oscuro87** [comment] 2020-01-28 15:04
Ok, then another proposal would be (in next_call_time):
```python
if self.running and self.interval > 0:
            total_runtime = self.clock.seconds() - self.starttime
            interval = self.start_delay or self.interval
            return interval - (total_runtime % self.interval)
return None
```

And disable values below 0 for the `interval` parameter in the `restart` function

**Comment by Griatch** [comment] 2020-01-28 15:09
@Oscuro87 Since -1 has been mentioned in docs in the past, -1 needs to be accepted as a setting, but converted to 0 internally (this is where the problem was introduced). Something like the above sounds like a good solution, but I haven't time to look into the details right now. Are you considering making a PR?

**Comment by Oscuro87** [comment] 2020-01-28 15:12
Oh right, I'll adapt to the -1 situation, and yes, I'll do a PR in the next few minutes!

**Comment by Griatch** [comment] 2020-01-29 10:15
Closed in https://github.com/evennia/evennia/pull/2042.

**Closed by Griatch** 2020-01-29 10:15 UTC
Labels: bug

**Comment by strikaco** [comment] 2020-01-29 17:12
@Oscuro87 Thanks for the quick fix!
