### ISSUE TITLE
Bug: 'contents cache failed for ' <player>

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1064] opened 2016-09-14 20:45 UTC
#### Brief summary of issue / Description of requested feature:
A character in game is continually throwing errors for her contents cache with a newly created object, which is just a typeclass of 'Bauble', essentially a duplicate of DefaultObject. Here's the very odd thing: although she throws a key error for the bauble's id of 4037 in game for contentscache._idcache[4037], in evennia shell it finds it fine. I have absolutely no idea why _idcache is different in-game than from shell.

**Comment by Griatch** [comment] 2016-09-14 20:49
This is not enough information, what is the traceback, in what way was it created? Please fill in the bug template as much as possible, it helps to clarify one's thoughts when writing an issue. 

The "odd thing" is very natural. If you are launching `evennia shell`, you are studying the data from a different process than Evennia is running in. So the cache (which is in-memory per-process) will always be different. To check things you have to check from inside the process with `@py`.

**Comment by TehomCD** [comment] 2016-09-14 20:53
Sorry about that: there was no traceback. The error is sent by https://github.com/evennia/evennia/blob/master/evennia/objects/models.py#L82 - the KeyError from attempting to look up the keys created by the contentshandler inside the idcache. The object was created by a player with a crafting command, which just uses evennia's create_object utility. The object was created roughly an hour before, the player says, and the error continues after init() is called on the contentshandler, and through the player logging out and in.

**Comment by TehomCD** [comment] 2016-09-14 21:03
Well, I apologize for not trying this first - a server @reload did resolve the issue. I should have tried that before posting. I admit to panicking a bit when seeing an error I was entirely unfamiliar with.

**Comment by Griatch** [comment] 2016-09-14 21:04
Ok, I had already started writing this, so worth to figure out what was going on: 

1. Does this still happen after a `@reload` - in that case we can rule out any more serious issue, like the idmapper cache cleaning itself in some way. Update: Seems like it did
2. If you query the location she's in (or herself) with `@py`, and get `location.contents_cache.get()` manually, does that trigger the error?
3. If so, what is the contents of `contents_cache._pkcache` and `_idcache` respectively?
4. What happens if doing `contents_cache.clear()` ?

**Comment by Griatch** [comment] 2016-09-14 21:08
The contents cache is triggered on calling `object.location = new_location` (this is an important optimization as it turns out). It will *not* work properly if setting the db_location field manually however - such as using `object.db_location = new_location; object.save()`. In that case the content handler of `new_location` must be manually re-initialized to recognize the new contents.

**Comment by Griatch** [comment] 2016-09-16 15:07
@TehomCD 

Was this a one-time thing or something you can reproduce? If it's not reproducible I'll close this.

**Comment by TehomCD** [comment] 2016-09-16 19:38
No luck reproducing it. I'll let you know if it ever happens again and I'm able to figure out how to reproduce it.

**Comment by Griatch** [comment] 2016-09-19 09:05
Ok, leaving this open for a little longer. Will close it eventually if it cannot be reproduced.

**Comment by Griatch** [comment] 2016-09-20 07:00
Ok, I think I can reproduce this along with the general error seen concerning contents not working. This is the process to reproduce: 

1. Login with superuser. 
2. Login with Player2, make sure to be in the same location as superuser.
3. Logoff  Player3 (`@exit`).
4. As superuser, run `@server/flushmem` to force an idmapper cache flush.
5. Login with Player2 again. 
6. Player2 will see superuser but superuser will *not* see Player2. 
7. Henceforth Player2 can logoff/logon as much as they want and will continue to be invisible to superuser until a `@reload` or until Player2 leaves the room and returns.  

So it seems like the idmapper cache flush leaves the contents cache in a state it cannot update from.

**Comment by Griatch** [comment] 2016-10-02 18:51
Found it! This was a tricky one, so I'll try to explain it (partly also for my own benefit). Let's say we have two Characters, Char1 and Char2, both in Limbo. 

There is actually nothing wrong with the `Limbo.contents`  cache, it's rather a ForeignKey desyncing issue. When the memory is flushed, some objects must be preserved because they have NAttributes on them (.ndb) - otherwise the flush would kill those. In our example, both Char1 and Char2 are such flush-safe Objects (they have the `last_cmd" NAttribute on it). Meanwhile Limbo is *not* flush-safe. 

So we start out with Char1 and Char2 both Limbo. `Limbo.contents` is now correctly `[Char1, Char2]`. Now we log out Char2. `Limbo.contents` is now updated to just `[Char1]`. 

Next we flush the idmapper memory cache with `@server/flushmem` (or with the automatic flush mechanic). Now Char1 remains the way it was (since it's flush-safe) while Limbo is flushed. `Limbo.contents` goes away together with Limbo, and is thus ready to re-build without any issues. 

When Char2 logs back in, Limbo is re-built along with its contents cache. This cache is now correctly `[Char1, Char2]`. So Char2 can see Char1 just fine. But Char1 does not see Char2! So what happens? 

The kicker is that Char1 retains a reference to Limbo in the form of `Char1.db_location`. As it turns out, Django caches this ForeignKey relationship. *It is still the pre-flush version of Limbo*. And when Char1 does "look", it determines what's in the room via `Char1.location.contents`, which is *still* `[Char1]` as it was pre-flush. 

As a result Char1 is seeing the "old" Limbo while Char2 is seeing the new, updated Limbo. The even worse thing is that `Char1.location.contents` is a perfectly fine reference to Limbo and *will continue to update independently*. So the duplicates will seem to come back into sync as long as both see the same changes (both will correctly handle a new Character entering, for example). But Char1 will continue to use its own version of Limbo until it leaves Limbo and returns (at which point its reference will update to the "real", new one). Lots of chances for confusion and weird bugs!

So after diving into the flush mechanisms in quite a big way, I've made individual object caches customizable. Default typeclasses will now fully reset all its ForeignKey relationships and other relationships. The result is that `Char1.db_location` will re-acquire the newly flushed Limbo along with its contents cache.

**Closed** 2016-10-02 18:55 UTC
Labels: bug
