### ISSUE TITLE
The data in of table “Typeclasses_tag” is not automatically deleted when tags no longer points to any objects

### ISSUE THREAD

**Issue by 555111** [evennia/evennia#1793] opened 2019-03-07 01:14 UTC
BUG:  The data in of table “Typeclasses_tag” cannot be automatically deleted.

The object has been deleted, but the relevant alias and other data of the object in the database have not been deleted.

So the database table “Typeclasses_tag”'s data is never deleted.

The database table "Typeclasses_tag" gets bigger and bigger.

Hope to solve this problem!

thank you!

**Comment by Griatch** [comment] 2019-03-12 18:05
This is not a bug per se, it's well-known behavior since a given Tag is shared by many objects - it's not always obvious a tag should be deleted when the last object pointed to that tag is deleted - having a Tag category with no objects has its own potential uses. 
I see the argument for optimization reasons though. I'll change this to a 'feature request' for having the tag be deleted when not pointing to any other objects.

**Comment by 555111** [comment] 2019-03-13 03:33
Thanks!

I think it might be better:

If the tag is not in use, it is better to delete it. 
If we need a tag, create it ourselves.

Because sometimes hundreds of logos were created, and related items were later deleted.
Tags that are no longer used waste database space and affect efficiency.
It's also easy to recreate the tag, which is better than the tag left in the spare space.

**Comment by robotfactory** [comment] 2019-06-10 01:30
Here's something weird that I think is related.

I have object #123 with tag "test":"yes". Then I remove the tag from #123. This tag no longer references any objects.

When I add the tag "test" to an object with no category string, it defaults to "yes." So even though I just added the tag, it also gets the category that was last used by the tag.

**Comment by strikaco** [comment] 2019-07-25 22:16
> We don't need "potential uses".
> Because there are too many tags.
> Sometimes hundreds of tags were created, and related items were later deleted.
> Tags that are no longer used waste database space and affect efficiency.

Having so many orphaned tags that performance is a concern does not fit the use-case for the loosely-coupled, reusable and many-to-many nature of Tags. Your data and needs sound like they would be better represented by Attributes, which are meant to store object-specific data and are deleted along with the parent object by design.

> This is not a bug per se, it's well-known behavior since a given Tag is shared by many objects - it's not always obvious a tag should be deleted when the last object pointed to that tag is deleted - having a Tag category with no objects has its own potential uses.
I see the argument for optimization reasons though. I'll change this to a 'feature request' for having the tag be deleted when not pointing to any other objects.

For default behavior, I'd ask that tags continue to *not* be deleted when disassociated-- they are already a highly-optimized, very flexible, abstract data model when used appropriately. I use them extensively for everything from serializing common attributes to storing data for animation and graphics. If delete-on-empty became default it would literally erase most of my database.

**Comment by strikaco** [comment] 2019-07-30 21:43
> (me) Having so many orphaned tags that performance is a concern blah blah
> (@Griatch) This is not a bug per se, it's well-known behavior since a given Tag is shared by many objects

555111 didn't go into much detail on their situation so I presumed user error but upon further thought, it looks like if one spawns dynamic prototypes individually the spawner will generate a *ton* of distinct `from_prototype: prototype-<sha>` tags.

I'm assuming this tag can be used to group/identify bulk-created prototyped objects by batches (like lot numbers?)...but it is true that these tags will long outlive their associated objects and become less useful over time as objects disappear or the chance of hash collisions between existing batch IDs increases.

A new `sparse` tagtype (or some other flag) might be called for...any tag flagged as such could be made subject to deletion if no associated objects remain. The `from_prototype` tag should subscribe to that, as could any other tag a dev does not want persisting beyond all related objects' lifespans. I think that would solve everybody's problems.

**Comment by Griatch** [comment] 2021-08-07 21:54
@strikaco You are not alone in using Tags for for storing data - which is not what they are intended for. Tags are really meant to, well, tag objects with a string and quickly search for groups of such tagged objects.
I wonder if one should instead introduce some new `Link` type model for connecting arbitrary entities with additional data - this seems to be the kind of thing many make use of Tags for.

**Comment by strikaco** [comment] 2021-08-08 22:02
> I wonder if one should instead introduce some new `Link` type model for connecting arbitrary entities with additional data - this seems to be the kind of thing many make use of Tags for.

For arbitrary data, adding a JSONField to the core models would solve these specific needs just the same. I chose to use Tags for this purpose because it's the only model that enforces uniqueness by key.

Being able to associate objects with each other would be really cool though-- and allow for things like associating images with objects, without needing to replicate the content.

**Comment by Griatch** [comment] 2021-08-11 14:49
> For arbitrary data, adding a JSONField to the core models would solve these specific needs just the same. 
I'm pretty sure a JSONField is postgresql specific, so that won't happen. :)

**Comment by Griatch** [comment] 2021-09-15 22:27
@strikaco, @TehomCD I have a prototype for a `Link` model of the following form:
```
Link:
   key   (str)                 <-   key + category is database-unique
   category  (str)
   data  (PickleField)    <- for arbitrary, pickled data
   strdata (str)              <- for arbitrary, string-only data
   autodelete (bool)      <- If True, auto-delete link when no entities link to this (we could do something similar for Tags)
```

The idea is that typeclassed entities would have m2m fields (and a `.links` handler, similarly to Attributes and Tags do). Each `Link` would  in order to connect any combination of typeclassed entities to a Link. This would allow for making arbitrary links between data along with actual arbitrary, shared data on the Link itself.

The `autodelete` field is something that I'd be adding to Tags as well - probably defaulting to `False` for backwards compatibility.

**Comment by strikaco** [comment] 2021-09-16 17:54
> 
> 
> @strikaco, @TehomCD I have a prototype for a `Link` model of the following form:
> 
> ```
> Link:
>    key   (str)                 <-   key + category is database-unique
>    category  (str)
>    data  (PickleField)    <- for arbitrary, pickled data
>    strdata (str)              <- for arbitrary, string-only data
>    autodelete (bool)      <- If True, auto-delete link when no entities link to this (we could do something similar for Tags)
> ```
> 
> The idea is that typeclassed entities would have m2m fields (and a `.links` handler, similarly to Attributes and Tags do). Each `Link` would in order to connect any combination of typeclassed entities to a Link. This would allow for making arbitrary links between data along with actual arbitrary, shared data on the Link itself.
> 
> The `autodelete` field is something that I'd be adding to Tags as well - probably defaulting to `False` for backwards compatibility.

Looks interesting, though a little redundant:

* The model name (`Link`) is a bit confusing-- in most contexts, a link is a unique connector of two things. This seems like it would be better-described as a `Collection`, `Group` or `Bucket`.
* The functionality of it seems similar to both Channels and Messages-- either can be used for one-to-many relationships and storage of arbitrary data (would need a proxy model created for Message though).
* This could also be implemented with one global Script object and a related handler that allows any other object to access the global object's attribute storage. No migrations necessary, uniqueness enforced by DBHandler cache.
* The proposed model closely follows that of Attributes. Why reinvent it under the context of Tags?

I think *this* issue would be solved in the fewest steps and to broadest satisfaction by just adding the autodelete field to the Tag model and periodically purging orphaned tags. How to model custom relationships warrants a much deeper discussion.

**Comment by TehomCD** [comment] 2021-09-16 18:09
It really feels like you could reuse Attributes for this since currently they have the existing M2M relationships anyway. Right now they're differentiated between nicks and data attributes, so it feels like Link would be another type for that.

**Comment by Griatch** [comment] 2021-09-16 18:22
@strikaco Messages and Channels have specific usages. The point here is that `Tags` are _definitely_ not meant for such storage and still you (and others) find it necessary to use `Tags` for far more than what they are intended for. So there appears to be a need here that current models don't fill. You are correct that a Script can already today be linked to Objects and Accounts via m2m mapping. But that's not what you are using. 

@TehomCD (and @strikaco). Maybe I was unclear in my description. The `Link` is not at all like an Attribute, nor a Tag. At least you could not implement this with them without seriously reworking either. The `Link` is globally unique (key + category) like a Tag, but can carry data like an Attribute. Moreover, whereas m2m is used for both (this is what allows you to easily add a new db-model and have it use Attributes/Tags), Attributes are only unique per-instance and Tags are only unique per database table (so you have separate sets of object-tags, script-tags, account-tags etc). This is not something we'd want to modify (and people complain about those tables being overloaded already as it is). 

By comparison the `Link` connects to (and is unique across) all tables whose typeclassed entities have a LinkHandler/m2m field reference. It's a truly globally unique entity for linking entities together with each other and with data.

**Comment by strikaco** [comment] 2021-09-16 21:17
> @strikaco Messages and Channels have specific usages. The point here is that `Tags` are _definitely_ not meant for such storage and still you (and others) find it necessary to use `Tags` for far more than what they are intended for. So there appears to be a need here that current models don't fill. You are correct that a Script can already today be linked to Objects and Accounts via m2m mapping. But that's not what you are using.
> 
> @TehomCD (and @strikaco). Maybe I was unclear in my description. The `Link` is not at all like an Attribute, nor a Tag. At least you could not implement this with them without seriously reworking either. The `Link` is globally unique (key + category) like a Tag, but can carry data like an Attribute. Moreover, whereas m2m is used for both (this is what allows you to easily add a new db-model and have it use Attributes/Tags), Attributes are only unique per-instance and Tags are only unique per database table (so you have separate sets of object-tags, script-tags, account-tags etc). This is not something we'd want to modify (and people complain about those tables being overloaded already as it is).
> 
> By comparison the `Link` connects to (and is unique across) all tables whose typeclassed entities have a LinkHandler/m2m field reference. It's a truly globally unique entity for linking entities together with each other and with data.

You were perfectly clear about it; I'm only poking at the idea to make sure it adds enough value to be worth your time and effort.

* (I stand by my assertion that the name `Link` is iffy though).
* You bring up a good point about the tablespacing of Tags; I had not considered that.
* Would you consider changing the `strvalue` field to a JSONField? (I know I sound like a broken record, sorry. Would love to not have to use custom models for this anymore). If not, a method or property that JSON dumps/loads against the strvalue field or does SaverDict magic would be appreciated.

**Comment by Griatch** [comment] 2021-09-16 21:29
@strikaco 
- I'm open to alternative name suggestions to `Link`, but it's not a `bucket` or `group`. Maybe `Collection` but ... not sure. 
- The idea is to have `.data` be a `PickleField` (same as the `value` field of Attributes). This is a TextField under the hood and can be searched very efficiently for the whole value - but you can't e.g. query for values of a serialized dict of course (so same limitation as Attributes). Whereas JSONField can be searched in the case of postgresql, I don't know how good general support is across all databases (I saw Tehom's link but haven't tested it).
- Using `strdata` would specifically be for simple data - optimized lookups. It'd be a waste to use it to load/dump JSON - much more efficient to use PickleField in that case.

**Comment by strikaco** [comment] 2021-09-17 17:09
Well, I'm sold. Looking forward to it :)

(The biggest advantage of the JSONField over PickleField _is_ the searchability of the data itself-- otherwise one has to iterate the entire object list app-side to look for specific values. This is an existing limitation of both Prototypes and my [ab]use of Tags; searches do not scale.)

**Comment by Griatch** [comment] 2021-09-17 19:02
Yes, I know about the advantage of JSONFields, I use them daily for postgres. Unfortunately, from what I read, you need to compile sqlite3 especially to support Django 3.2's JSONField. And even this is pretty experimental. So this is not something I think we can expect to support at this time. Maybe in the future when it matures, we could add it.

**Comment by strikaco** [comment] 2021-09-17 20:26
DataLink works, or perhaps LinkedData / SharedData?

**Comment by Griatch** [comment] 2022-11-28 18:51
Closing this, as we need to add more linking capabilities so people don't abuse Tags enough for this be an issue.

**Closed by Griatch** 2022-11-28 18:51 UTC
Labels: feature-request, branch-develop, discussion
