### ISSUE TITLE
[BUG] Problem with EvMenu, coloring the desc, and rjust

### ISSUE THREAD

**Issue by kaleara** [evennia/evennia#2485] opened 2021-08-07 04:04 UTC
#### Describe the bug
When using EvMenu, using colors for some of the option descriptions, and rjust to line up the descriptions, the spacing is off by one. I can adjust for this, but it also seems that the spacing for the middle part (when the line is broken into two for length) is also off.

#### To Reproduce
1. Create EvMenu with lots of options
2. Change the color on some of the option descriptions
3. Use rjust to line up all the descriptions
4. Highlighted descriptions are not lined up

#### Expected behavior
The error disappears if I specify a character to fill the empty space (like - but not a space). It also doesn't appear when not using rjust and just changing the color of some words.

#### Environment, Evennia version, OS etc
Windows and Linux

**Comment by Griatch** [comment] 2021-10-01 08:05
@kaleara It would help with a brief example to reproduce this. Nevertheless, it sounds like something for Hacktoberfest.

**Comment by Griatch** [comment] 2022-02-13 22:14
@kaleara Could you provide an small example for reproducing this effect?  Otherwise this will close.

**Comment by kaleara** [comment] 2022-02-16 00:27
This is what it looks like. I will try to make a similar menu that has the same issue later in the week.

![image](https://user-images.githubusercontent.com/38018075/154172371-ebed4572-498f-4ef3-b7c5-9fab4dff1b73.png)

![image](https://user-images.githubusercontent.com/38018075/154172415-f3d2c8d7-24c5-42f2-8135-3d6972b418c5.png)

**Comment by owllex** [comment] 2022-02-16 00:32
FWIW I see this issue in the webclient when I use width-based formatting specifiers like {text:10}, and when it occurs, it's usually an off-by-one spacing error. I don't think it's specific to EvTable.

It might have something do with how the webclient handles spaces when displaying color text. It reproduces reliably, but as soon as you change the width format specifiers (even by just 1), it seems to go away, so it's hard been hard to nail down the cause.

**Comment by owllex** [comment] 2022-02-16 00:35
Here's a screenshot of it from a UI that is not using EvTables:
![localhost_4001_webclient_ (3)](https://user-images.githubusercontent.com/15664651/154173534-d3c4a87a-4b64-4e2c-b30f-040fbe273f86.png)

Both the second and third lines are showing one fewer space than they should. This text is generated simply with regular format strings that are converted to ANSIString before being msg'd.

**Comment by mrseeker** [comment] 2022-02-16 05:06
Related to #2578

**Comment by owllex** [comment] 2022-03-01 18:53
Here's a simple repro case from the @py shell that shows two main problems.
```
>>> me.msg(f" /{ANSIString('one'):9}/")
/one/
>>> me.msg(f"  /{ANSIString('one'):<9}/")
 /one      /
>>> me.msg(f" /{ANSIString('one'):<9}/")
/one      /
```

1) No leading space is printed unless there are at least two spaces (and I think it's still printing N-1 leading spaces)
2) The format specifier length is ignored for ANSIStrings *unless* there is also a justification specifier.

**Comment by Griatch** [comment] 2022-03-01 19:58
@owllex Thanks for the example. It seems to be much simpler to reproduce this than this though; I seem to see this effect with just this (in webclient only): 
```
py me.msg("//")
//
py me.msg(" //")  
//      # <---  no initial space 
py me.msg("  //")
 //     # <--- only one initial space, despite requesting two
```

**Comment by Griatch** [comment] 2022-03-01 20:47
Fixed in text2html pre-parser for develop branch.

**Closed by Griatch** 2022-03-01 20:47 UTC
Labels: bug, more info needed, Hacktoberfest, web
