### ISSUE TITLE
Issue making my server available online

### ISSUE THREAD

**Issue by Mangiang** [evennia/evennia#784] opened 2015-08-17 23:31 UTC
I'm running under windows 8.1
My ports 4000,8000 and 8001 are open ( according to the checker "PortForward Network Utilities" ) in both my firewall and my routeur.

Here is what I added to settings.py :
TELNET_PORTS = [4000]
TELNET_INTERFACES = ['myip']
WEBSERVER_PORTS = [(8000, 5001)]
WEBSERVER_INTERFACES = ['myip']
ALLOWED_HOSTS = ['*']
WEBSOCKET_CLIENT_INTERFACE = 'myip'
WEBSOCKET_CLIENT_URL = "ws://myip"
WEBSOCKET_CLIENT_PORT = 8001
AMP_PORT = 5000

Here is the portal log : 
2015-08-18 01:16:47+0200 [-] Log opened.
2015-08-18 01:16:47+0200 [-] twistd 15.3.0 (C:\Python27\python.exe 2.7.9) starting up.
2015-08-18 01:16:47+0200 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2015-08-18 01:16:47+0200 [-] Traceback (most recent call last):
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\scripts\twistd.py", line 14, in <module>
2015-08-18 01:16:47+0200 [-]     run()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\scripts\twistd.py", line 29, in run
2015-08-18 01:16:47+0200 [-]     app.run(runApp, ServerOptions)
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\application\app.py", line 617, in run
2015-08-18 01:16:47+0200 [-]     runApp(config)
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\scripts\twistd.py", line 25, in runApp
2015-08-18 01:16:47+0200 [-]     _SomeApplicationRunner(config).run()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\application\app.py", line 352, in run
2015-08-18 01:16:47+0200 [-]     self.postApplication()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\scripts\_twistw.py", line 46, in postApplication
2015-08-18 01:16:47+0200 [-]     service.IService(self.application).privilegedStartService()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\application\service.py", line 278, in privilegedStartService
2015-08-18 01:16:47+0200 [-]     service.privilegedStartService()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\application\internet.py", line 106, in privilegedStartService
2015-08-18 01:16:47+0200 [-]     self._port = self._getPort()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\application\internet.py", line 134, in _getPort
2015-08-18 01:16:47+0200 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\internet\posixbase.py", line 478, in listenTCP
2015-08-18 01:16:47+0200 [-]     p.startListening()
2015-08-18 01:16:47+0200 [-]   File "C:\Python27\Lib\site-packages\twisted\internet\tcp.py", line 984, in startListening
2015-08-18 01:16:47+0200 [-]     raise CannotListenError(self.interface, self.port, le)
2015-08-18 01:16:47+0200 [-] twisted.internet.error.CannotListenError: Couldn't listen on **.**.**.**:4000: [Errno 10049] LÆadresse demandÚe nÆest pas valide dans son contexte.

" LÆadresse demandÚe nÆest pas valide dans son contexte." means "The requested address is not valid in its context"

**Comment by Griatch** [comment] 2015-08-18 07:20
It's a CannotListen error which is usually caused by you having a previous instance of Evennia or some other application already using this port, so make sure to check this is not the case. 

If that was not the issue, did you specify your port manually for any reason, the error message may suggest the port or maybe the interface string is malformed somehow.

**Comment by Mangiang** [comment] 2015-08-18 09:21
Thank you for replying this fast.

No other application uses this port.
To set my server, I followed https://github.com/evennia/evennia/wiki/Online-Setup  and I put my external ip instead of "myip" in my settings.py .

**Comment by Griatch** [comment] 2015-08-18 09:24
Try removing (comment out) your custom ip string from settings.py and see if it works then. If so you know your ip string is malformed somehow.

**Comment by Mangiang** [comment] 2015-08-18 09:32
If you mean running it as default with localhost , it works perfectly.
I assume I didn't malform my ip string since I copy-paste it from http://whatismyipaddress.com

**Comment by Antrare** [comment] 2015-08-18 10:18
That ip will not be assigned to an interface on the pc you're running but
the interface of your router. Just leave it as default and it will be fine.

**Comment by Griatch** [comment] 2015-08-18 10:37
If you copy & pasted it, are you sure you did make it a string, with quotes? Also, which setting variable are you using, exactly- some of them requires a list of strings.

**Comment by Mangiang** [comment] 2015-08-18 11:17
Those are my addings to settings.py : 
TELNET_PORTS = [4000]
TELNET_INTERFACES = ['myip']
WEBSERVER_PORTS = [(8000, 5001)]
WEBSERVER_INTERFACES = ['myip']
ALLOWED_HOSTS = ['*']
WEBSOCKET_CLIENT_INTERFACE = 'myip'
WEBSOCKET_CLIENT_URL = "ws://myip"
WEBSOCKET_CLIENT_PORT = 8001
AMP_PORT = 5000

I only added those lines. Also, I wrote my ip instead of my ip and I made them a string.

**Comment by Mangiang** [comment] 2015-08-18 11:20
Antrare, when I leave it as default, I can't connect with my external ip on my server either.

**Comment by Mangiang** [comment] 2015-08-18 11:27
When I leave it as default and go to http://myip:8000 (putting my external ip instead of "myip"), Chrominum says it can't reach the page. But "netstat -p tcp -ano | findstr :8000" says that the connection is "established"

**Comment by Mangiang** [comment] 2015-08-18 11:27
Internet explorer can't reach too

**Comment by Griatch** [comment] 2015-08-18 16:27
It looks okay as far as I can tell. Could it be that your router blocks the port?

**Comment by Mangiang** [comment] 2015-08-18 17:03
Ports 4000, 8000 and 8001 are open

**Comment by Mangiang** [comment] 2015-08-18 23:06
I tried to delete Evennia and install it again but I got this error :

C:\Users\___\Desktop\evennia\game>python manage.py

    Welcome to Evennia!

    This looks like your first startup, so we created a fresh
    game/settings.py file for you. No database has yet been created.
    You may edit the settings file now if you like, but if you just
    want to quickly get started you don't have to touch anything.

    Once you are ready to continue, (re)run
        python manage.py syncdb
    followed by
        python manage.py migrate


C:\Users\___\Desktop\evennia\game>python manage.py syncdb
--------------------------------------------------------------------------------
----------
NOTE: Django %s found. This is newer than Evennia's recommended version. It will

       probably work, but may be new enough not to be fully tested yet. Report a
ny issues.
--------------------------------------------------------------------------------
----------
Traceback (most recent call last):
  File "manage.py", line 140, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
338, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
312, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 86, in create

    module = import_module(entry)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\___\Desktop\evennia\src\players\__init__.py", line 10, in <m
odule>
    from src.players.player import *
  File "C:\Users\___\Desktop\evennia\src\players\player.py", line 17, in <mod
ule>
    from src.comms.models import ChannelDB
  File "C:\Users\___\Desktop\evennia\src\comms\__init__.py", line 11, in <mod
ule>
    from src.comms.models import *
  File "C:\Users\___\Desktop\evennia\src\comms\models.py", line 25, in <modul
e>
    from src.typeclasses.models import TypedObject, TagHandler, AttributeHandler
, AliasHandler
  File "C:\Users\___\Desktop\evennia\src\typeclasses\models.py", line 48, in
<module>
    from src.typeclasses import managers
  File "C:\Users\___\Desktop\evennia\src\typeclasses\managers.py", line 11, i
n <module>
    from src.utils.dbserialize import to_pickle
  File "C:\Users\___\Desktop\evennia\src\utils\dbserialize.py", line 280, in
<module>
    @transaction.autocommit
AttributeError: 'module' object has no attribute 'autocommit'

**Comment by Griatch** [comment] 2015-08-19 07:16
You seem to be using an old evennia install, there is no current django that is "too new". Make sure to pull the latest before continuing, it's hard to help you if you are not using the same version as everyone else.

**Comment by Mangiang** [comment] 2015-08-19 09:37
My bad, I followed the tutorial of code.google and I cloned it from Mercurial I thought github and mercurial had the same version.

**Comment by Griatch** [comment] 2015-08-19 10:11
No the googlecode and its mercurial version has been discontinued for a good while, the mercurial repo is more than 1.5 years old. 
So are things working better for you now?

**Comment by Mangiang** [comment] 2015-08-19 11:03
Unfortunately not, I get the same error : 
2015-08-19 12:59:00+0200 [-] Log opened.
2015-08-19 12:59:00+0200 [-] twistd 15.3.0 (C:\Python27\pyenv\Scripts\python.exe 2.7.9) starting up.
2015-08-19 12:59:00+0200 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2015-08-19 12:59:00+0200 [-] Traceback (most recent call last):
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\scripts\twistd.py", line 14, in <module>
2015-08-19 12:59:00+0200 [-]     run()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\twistd.py", line 29, in run
2015-08-19 12:59:00+0200 [-]     app.run(runApp, ServerOptions)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\app.py", line 617, in run
2015-08-19 12:59:00+0200 [-]     runApp(config)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\twistd.py", line 25, in runApp
2015-08-19 12:59:00+0200 [-]     _SomeApplicationRunner(config).run()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\app.py", line 352, in run
2015-08-19 12:59:00+0200 [-]     self.postApplication()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\scripts\_twistw.py", line 46, in postApplication
2015-08-19 12:59:00+0200 [-]     service.IService(self.application).privilegedStartService()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\service.py", line 278, in privilegedStartService
2015-08-19 12:59:00+0200 [-]     service.privilegedStartService()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\internet.py", line 106, in privilegedStartService
2015-08-19 12:59:00+0200 [-]     self._port = self._getPort()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\application\internet.py", line 134, in _getPort
2015-08-19 12:59:00+0200 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\internet\posixbase.py", line 478, in listenTCP
2015-08-19 12:59:00+0200 [-]     p.startListening()
2015-08-19 12:59:00+0200 [-]   File "C:\Python27\pyenv\Lib\site-packages\twisted\internet\tcp.py", line 984, in startListening
2015-08-19 12:59:00+0200 [-]     raise CannotListenError(self.interface, self.port, le)
2015-08-19 12:59:00+0200 [-] twisted.internet.error.CannotListenError: Couldn't listen on 91.57.239.933:4000: [Errno 10049] LÆadresse demandÚe nÆest pas valide dans son contexte.

(this is a false ip)

**Comment by Griatch** [comment] 2015-08-19 11:45
I don't think this is an Evennia issue per se, my main guess is that it is a Windows issue with your setup and IP forwarding to your router. Doing a search for "twisted + address invalid in this context" gives several matches for Windows having similar issues: 

https://duckduckgo.com/?q=twisted+address+not+valid+in+this+context

For example: 
http://stackoverflow.com/questions/4657347/socket-error-ip-address-not-valid-in-its-context-python
http://serverfault.com/questions/314083/what-does-it-mean-for-an-address-to-be-invalid-in-context-error-code-os-10049

I don't have a Windows machine at hand to test right now, but I know others have working external setups on Windows. Maybe someone else can chip in if they are familiar with this error?

**Comment by Mangiang** [comment] 2015-08-19 11:51
Thank you, I will look this way for a solution :)

**Comment by Griatch** [comment] 2015-08-19 12:10
If you resolve it, make sure to let us know! :)

**Comment by Mangiang** [comment] 2015-08-19 12:10
Sure ! :)

**Comment by Mangiang** [comment] 2015-08-19 14:08
![mud](https://cloud.githubusercontent.com/assets/9913715/9358443/6c65c6c6-468c-11e5-8da7-b3386194fadd.png)

I can reach this page by writing my INTERNAT ip instead of EXTERNAL ip in settings.py 
But I can't reach the play screen. Any guess ?

**Comment by Griatch** [comment] 2015-08-19 14:35
Your internal IP you can reach since, well, you are on the same network. It seems your router is not forwarding correctly if that works but not your external IP. 

As for the page, it looks like you don't have your web media files in the right place either; the css is all wrong. Is this from a directory created with the latest Evennia or are you still using one created with the old version?

For the play screen, it's hard to tell what the issue is without more info.

**Comment by Mangiang** [comment] 2015-08-19 14:41
I wrote my INTERNAL ip in settings.py but I reached this page using my EXTERNAL ip in Internet explorer.

I my routeur configuration : from port 8000 to port 8000 to [my internal ip] 
Is that correct ?

I'm using the lastest Evennia donwloaded by "git clone ..."  with the tutorial of github.com

About the play screen, have you heard about this error ? : 
"Request.finish called on a request after its connection was lost; "
	exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

**Comment by Mangiang** [comment] 2015-08-19 15:05
Also, I found out (thanks to you links )  that I can't write my EXTERNAL ip in settings.py because I can't bind an ip that is not registered or something by my computer. Shorter, I can't write something that isn't shown by "ipconfig". 
"ipconfig" shows only internal ip .

**Comment by Griatch** [comment] 2015-08-19 15:18
Ah, I assumed you meant "internal" being localhost and "external" being the outward facing IP of your computer. If you rather meant "internal" as the local computer and the "external" as the router's outward facing IP, then true, Evennia (or indeed any server) will need to know about the computer it is on, not anything else. Evennia cannot know anything about the router's IP - that's the whole point of firewall point forwarding. This is not really a Windows issue but the way routers work.  It's indeed worth to keep that Windows error message in mind though, it's not very informative. 

There is one exception though, and that is the webclient ws:// IP. This _should_ be the router's outward facing IP since it is used by the remove client to "call home" so to speak. 

Maybe we'll make a little graphic to make these relationships clearer. So have you gotten things to work now then?

**Comment by Mangiang** [comment] 2015-08-19 17:23
Sorry I didn't understand that I should write my internal ( local ) ip in settings with an exception for webclient. 

It takes a lot of time to load the main page (last picture) and I often can't even reach this page.

Still looking on the internet for a solution.

**Comment by Griatch** [comment] 2015-08-19 17:27
Evennia will need your local machines outgoing IPs - the router will then reroute them to whatever IP should be outward facing. The webclient websocket url however is a "callback" - that is, it is triggered by the user's remote client (in the javascript they execute in their browser) in order to find your server. So WEBSOCKET_CLIENT_URL = ws://...  should be set to the outward facing IP (usually your router's) in order for the user's client to find you. 

The page should not take much time to load at all. Have you tried to bypass the router completely as suggested to see if that makes a difference?

**Comment by Mangiang** [comment] 2015-08-19 17:31
My "localhost" and "local ip" work perfectly fine.

**Comment by Mangiang** [comment] 2015-08-19 18:37
I can have the "game page" using telnet BUT when I push a key, the prompt understand that I pushed "enter" right after my key.
I mean if I push "c" [beginning of "connect"], the prompt don't wait for me to push "o", it says "Command 'c' not available"

**Comment by Griatch** [comment] 2015-08-19 19:06
As for the access of the websocket, that appears to be your router blocking you somehow. 

I would recommend you switch your telnet client to line mode (this should be a setting for your client), or - better - to use a third-party mud client which is actually built for muds.

**Comment by Mangiang** [comment] 2015-08-19 19:11
http://www.canyouseeme.org/ says ports 8000,4000,8001 are open
Do I need to open more ports ?

Mush client can connect and play perfectly on my local ip

**Comment by Griatch** [comment] 2015-08-19 19:13
They may be open, but do they actually forward to the right ports on your local machine? Since you say connecting directly to the ports of your local machine works fine then the router must logically be the cause.

**Comment by Mangiang** [comment] 2015-08-19 19:16
What must be forwarding ports ?
I setted up ("internal port" => "external port") : 8000 => 8000 , 8001 => 8001 , 4000=>4000

**Comment by Griatch** [comment] 2015-08-19 19:51
Assuming your local machine (what you call "internal" I presume?) actually has those ports open to the router, then it looks ok. As said, I can only assume your router to be the issue since you say your local machine can be connected to normally.

One issue some routers have is that port forwarding does not actually activate until you have rebooted the router. Worth a try.

**Comment by Mangiang** [comment] 2015-08-19 20:10
Rebooting didn't work...
Do you have any other ideas ?

**Comment by Griatch** [comment] 2015-08-19 20:34
I don't know ... maybe your ISP has issues with you using some of those external ports? Try mapping some other port numbers, see if it makes a difference. 

Sorry, but can't help much more than that - this does not appear to be an Evennia issue but a problem with your router. Can't really say more about that.

**Comment by Mangiang** [comment] 2015-08-19 21:18
Ok thank you anyway

**Comment by Griatch** [comment] 2015-08-24 11:50
Since this was seems to work when taking the router out of the picture I'm closing this as something unrelated to Evennia itself. Re-post and ask to re-open if something else comes to light that suggests otherwise.

**Closed by Griatch** 2015-08-24 11:50 UTC
