### ISSUE TITLE
Bug: Producing 'phantom sessions' with Mushclient's autologin

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1517] opened 2017-11-14 21:34 UTC
#### Brief summary of issue / Description of requested feature:
A player was having connectivity issues, being dropped every so often, and I noticed that she had more sessions connected than seemed typical - usually 3 or so, despite only controlling one character. When  I asked her, she was only aware of one. I noticed that she seemed to have multiple sessions report connecting simultaneously when she was only aware of logging on once, and it seemed related to an autologin/autoreconnect feature. I'm speculating that it attempted to connect quickly enough that it caused some error, and the invalid nature of one of her sessions then would get her booted off before long. Disabling the feature in Mushclient seemed to resolve her issue.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use Mushclient's autoconnect/autoreconnect feature
2. Get multiple sessions somehow

#### Error output / Expected result of feature
Multiple sessions and subsequent connection difficulties.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I didn't see any outright errors reported in server log, though I'll need to see if I can find anything in the portal. A player reported something that sounds very similar using the 'Mudrammer' client, so I wonder if this might be happening with more than one client.

**Comment by Griatch** [comment] 2018-01-08 21:00
I'm limited in testing this since i haven't figured out how to make Mudlet autologin. :) The "autologin this character" block in the connection setting is not working (at least not with vanilla Evennia). Does people set up a trigger or something?

**Comment by Griatch** [comment] 2018-01-08 21:32
@TehomCD I can't reproduce this.  I've tried multiple times to connect with mushclient + autoconnect with latest Evennia without seeing any duplicate sessions appearing. Evennia `master` recently saw some considerable refurbishings in the way sessions are initialized, and also in how the connecting happens so maybe this issue has been resolved as a side effect? I'll leave this open for now, let me know if similar errors show up with the latest code.

**Comment by texdarkstar** [comment] 2018-01-08 21:44
Could this be related to #1075?

**Comment by TehomCD** [comment] 2018-01-09 00:46
I think that was just confusion about display for that issue, @texdarkstar - in this case, which happens very rarely but as recently as a week or two ago, the player definitely has multiple sessions show up in the log even if one of them doesn't appear to be really there: they'll show as one session remaining when they quit, etc. Since it seems to be very rare my theory is that it's some bizarre timing issue, but it could also very well have been resolved by some recent master change too.

**Comment by texdarkstar** [comment] 2018-01-09 01:38
Ahh

**Comment by Griatch** [comment] 2019-03-31 19:39
@TehomCD Since I could not reproduce and this has not been updated for so long, I'm closing this. If the issue re-emerges, let me know and I'll reopen.

**Closed by Griatch** 2019-03-31 19:39 UTC
Labels: bug, master-branch, more info needed
