### ISSUE TITLE
Bug: Session multiplies reloading tab on the webbrowser (not @reload)

### ISSUE THREAD

**Issue by texdarkstar** [evennia/evennia#1075] opened 2016-09-24 02:27 UTC
if i am logged in the game, and i reload the tab, it adds another session to my puppet.
only happens with the websocket that i know of so far. haven't tried with a mud client yet

there is no way to remove these extra sessions except deleting the server\evennia.db3 file and starting over.
i have tried cold restarts, quiting and making sure i was logged out for good, so im not autologged in, shutdowns, etc. nothing seems to work

**Comment by Griatch** [comment] 2016-09-26 08:33
Since Sessions are not persistent in the database there is no way a Session per se can survive a server shutdown. Maybe something gets added up at startup though. Exactly how are you viewing your sessions to see this effect? Could you give an exact sequence of commands for reproducing what you see, it'd help testing.

**Comment by texdarkstar** [comment] 2016-09-26 17:13
update. it also does it in mudlet when i test it on a mud client.and as for cmds all i type is "@type/force/update self" to update the character class of my puppet object, then i @examine myself and see:
"""
Name/key: Texdarkstar (#1)
session(s): 2
Player: Texdarkstar
etc.
"""

**Comment by texdarkstar** [comment] 2016-09-26 17:15
so here is what happens, sorry if i sound confusing. this is confusing me really badly.
1. on the webbrowser, when i reload the tab, it adds a session.
2. whenever i use @type/force/update on myself it also adds a session

maybe its a combination of both

**Comment by texdarkstar** [comment] 2016-09-26 17:28
oookay. it also adds a session if i quit and relog in to my mud.

Name/key: Texdarkstar (#1)
session(s): 5
Player: Texdarkstar

settings.MULTISESSION_MODE is = 0, as default, i havent messed with it.
and apparently shutting ithe mud down does remove these extra sessions, my bad

**Comment by BlauFeuer** [comment] 2016-09-26 17:31
I think it's counting how many sessions you've had.  I have
`session(s): 206`   We should ask for clarification what exactly's being counted there.

**Comment by texdarkstar** [comment] 2016-09-26 18:01
ok, that would explain the reloading tabs, but what about @type/force/update self? it also adds a session.

**Comment by BlauFeuer** [comment] 2016-09-26 18:14
I think what you're seeing is similar to a use count.  Someone knowledgeable like Griatch will come by and enlighten us eventually. Don't panic.

Possibly unrelated, in the database there _is_ a table called django_session with 3 fields: session_key, session_data, and expire_date.  My table has 173 entries in it from about 2 months of use. Expired sessions never seem to be deleted.  I suspect that holds the webclient cookies. I'm not too worried about it because I can manually delete them if the table grows to extreme amounts.

**Comment by texdarkstar** [comment] 2016-09-26 19:04
ok that makes more sense. i thought that line was counting the number of sessions puppeting that obj.
using "@py self.msg(self.sessions.all()[0].sessid" (only has one item in the list) i get an integral, 2, so maybe its a dbref for a session?

**Comment by Griatch** [comment] 2016-10-13 18:26
The number in question is the sessid for the session currently puppeting your character. If you had multiple sessions, you see a list of such session ids returned examine. But I see why it could be interpreted as a session count, so I pushed a fix to make it look less confusing. 

@BlauFeuer The session_key, session_data and expire_date are server side Browser Sessions used by the webclient + webserver to keep the player logged in (the fields and how they are stored is a Django thing). 

Closing.

**Closed by Griatch** 2016-10-13 18:26 UTC
Labels: bug
