### ISSUE TITLE
using attr() as a cmd: lockstring only does "equals" comparisons

### ISSUE THREAD

**Issue by Tegiminis** [evennia/evennia#2150] opened 2020-06-26 01:47 UTC
I set up a command to test lockfuncs like so. I want to restrict a command from being visible/used unless the player has the appropriate attribute. I created it to test a lockfunc I made which works like ``attr()`` except on nested dictionary values. Then I noticed that my comparison was only ever "equals", even when trying to use the ``compare`` kwarg on ``attr()``
```
class CmdPTest(BaseCommand):
    """
    Tests a lock

    Usage:
      ptest

    A debug command to test lockfuncs.
    """

    key = "ptest"
    locks = "cmd:attr(locktest, 80, compare=gt)"
    help_category = "General"

    def parse(self):
        self.target = self.args.strip()

    def func(self):
        caller = self.caller
        caller.msg("Lockfunc assigned to this command works properly.")
```
It checks if the attribute ``locktest`` is on my calling object, and then presumably whatever comparison the kwarg states, or equals if none. Instead it only ever checks if the value is equal to 80, regardless of what value I set compare to.

I've tried ``compare=gt`` and ``{'compare':'gt'}``, with and without ``**`` and various orderings of apostrophes, and neither work. If there's some syntax I'm missing, I understand, would be delighted to figure out what I'm doing wrong, if I am.

I presume this is a limitation of how lockfuncs work - hence why there's ``attr_gt()`` and such - but I'd like confirmation it's part of that limitation and not a bug before I write 5 new lockfuncs.

**Comment by Griatch** [comment] 2020-06-28 10:55
I cannot reproduce your issue. Whereas Evennia's lockfuncs generally don't use kwargs, this is mainly for readability reasons. As far as I can tell kwargs work fine in lockfuncs. Here's what I tried: 

A simple lockfunc in `mygame/server/lockfuncs` that reports its input:
```python
def echolock(accessing_object, accessed_obj, *args, **kwargs):
    print(f"echolock: accessing_object: {accessing_obj}, accessed_obj: {accessed_obj}, args:{args}, kwargs:{kwargs}")
    return True
```
I then created a small test-command to try this lockfunc (in `mygame/commands/command.py`): 
```python
class CmdCheckLock(Command):
    key = "checklock"
    locks = "cmd: echolock(foo, bar, compare=gt, compare2=foo)"
```

Next, in game:

     reload
     quell 
     checklock 

In the log I now have: 

```
echolock: accessing_object: Griatch, accessed_obj: checklockstring, args:('foo', 'bar'), kwargs:{' compare': 'gt', ' compare2': 'foo'}
```

That is, the args/kwargs I gave for the lock string has passed correctly into the lockfunc. Could you do a similiar step-by-step for your code and see where it differs from my example?

**Comment by Tegiminis** [comment] 2020-06-28 12:22
Here's the basic attributes of the command (also above):
```
key = "ptest"
locks = "cmd: attr(locktest, 80, compare=gt)"
```

I call the lockfunc normally to confirm it works and it does. For example:

```
def func(self):
        caller = self.caller
        _str = lockfuncs.attr(self.caller, self.caller, "locktest", "80", compare="gt")
        caller.msg("Attr() returned: %s" % _str)
```
I set my ``locktest`` db attribute to 100 and this returns true when unquelled, like I would expect. But if I quell or try on a different account:

![image](https://user-images.githubusercontent.com/2596300/85947028-2bd77a80-b8fd-11ea-8093-0b405cbd823d.png)

``attr()`` and everything associated with it is unchanged from the definition here: https://github.com/evennia/evennia/blob/master/evennia/locks/lockfuncs.py

I think I fixated on kwargs since they are new to me, but it could also be something to do with the comparison. The compare lambda looks like this:

```
CF_MAPPING = {
    "eq": lambda val1, val2: val1 == val2 or str(val1) == str(val2) or float(val1) == float(val2),
    "gt": lambda val1, val2: float(val1) > float(val2),
    "lt": lambda val1, val2: float(val1) < float(val2),
    "ge": lambda val1, val2: float(val1) >= float(val2),
    "le": lambda val1, val2: float(val1) <= float(val2),
    "ne": lambda val1, val2: float(val1) != float(val2),
    "default": lambda val1, val2: False,
}
```

And it's used here:

```
def valcompare(val1, val2, typ="eq"):
        "compare based on type"
        try:
            return CF_MAPPING.get(typ, CF_MAPPING["default"])(val1, val2)
        except Exception:
            # this might happen if we try to compare two things that
            # cannot be compared
            return False
```

**Comment by Griatch** [comment] 2020-06-28 13:55
At this point this does not appear to be an Evennia issue but rather something you need to figure out in your own code. 

A basic trick for debugging something like this is to confirm that all values are what you expect up to a certain point, so you can exclude everything before that as being the problem. 

Place a `print` statement in your custom `attr` lockfunc like I did for my simple testing lockfunc and print the inputs to the lockfunc (the prints will appear in the log). If the args/kwargs look ok your issue is for sure inside the lockfunc itself and not in how it is being called. If not, you may have come upon some bug we need to look at. 
Assuming the issue is in your code, you move your print to see if your lambda-call returns what you expect it to return and that you are actually comparing what you expect to be comparing. You also have a try...except statement that swallows any errors and returns False. Remove that and see if you are in fact just hiding a simple exception from  being shown.

**Comment by Tegiminis** [comment] 2020-06-28 14:29
I think you may be hyperfocusing on "custom lockfuncs". While I originally noticed this behavior while creating a custom lockfunc to search a dictionary, this ~particular~ behavior is expressed in the default lockfunc ``attr()``, as mentioned in both posts above. I did not change it whatsoever. This code:

```
CF_MAPPING = {
    "eq": lambda val1, val2: val1 == val2 or str(val1) == str(val2) or float(val1) == float(val2),
    "gt": lambda val1, val2: float(val1) > float(val2),
    "lt": lambda val1, val2: float(val1) < float(val2),
    "ge": lambda val1, val2: float(val1) >= float(val2),
    "le": lambda val1, val2: float(val1) <= float(val2),
    "ne": lambda val1, val2: float(val1) != float(val2),
    "default": lambda val1, val2: False,
}```

```
def valcompare(val1, val2, typ="eq"):
        "compare based on type"
        try:
            return CF_MAPPING.get(typ, CF_MAPPING["default"])(val1, val2)
        except Exception:
            # this might happen if we try to compare two things that
            # cannot be compared
            return False
```
> attr() and everything associated with it is unchanged from the definition here: https://github.com/evennia/evennia/blob/master/evennia/locks/lockfuncs.py

I'll address your debugging advice, but you're telling me to do debugging things I already did, so I'm not sure what you expect.

> A basic trick for debugging something like this is to confirm that all values are what you expect up to a certain point, so you can exclude everything before that as being the problem.

All my values are correct. Double, triple, quadruple checked. I know I said I was a newb but I'm not literally brand new to programming.

> Place a print statement in your custom attr lockfunc like I did for my simple testing lockfunc and print the inputs to the lockfunc (the prints will appear in the log).

I already know the lockfunc correctly accepts kwargs and args, because calling it directly and calling it through ``attr_gt()`` works, as mentioned in the comment directly preceding yours. I'm not interested in debugging how the Evennia engine parses a cmd: lockstring because it is frankly out of my league.

> You also have a try...except statement that swallows any errors and returns False. Remove that and see if you are in fact just hiding a simple exception from being shown.

I did not write this statement, but I did remove the ``try...except`` at your behest and it was not hiding an exception.

> If not, you may have come upon some bug we need to look at.

I am fairly sure I have, because this is not a custom lockfunc, so even if it's a problem with ``attr()`` and not however lockstrings are parsed, it's still this project's code, not mine.

Because I want to make it abundantly clear, here is the only personal code I am using, a command I have attached to my player object:

```
class CmdPTest(BaseCommand):
    """
    Tests if locks can use dicts

    Usage:
      ptest

    A debug command to test lockfuncs.
    """

    key = "ptest"
    locks = "cmd: attr(locktest, 80, compare=gt)"
    help_category = "General"

    def parse(self):
        self.target = self.args.strip()

    def func(self):
        caller = self.caller
        _str = lockfuncs.attr(self.caller, self.caller, "locktest", "80", compare="gt")
        caller.msg("Attr() returned: %s" % _str)
```

**Expected Functionality**: The command is visible and usable if your "locktest" db attribute is above 80.

**Actual Functionality**: The command is invisible and unusable unless your "locktest" attribute equals 80, regardless of what value "compare" is set to

**Comment by Griatch** [comment] 2020-06-28 14:36
Ok, I missed the transition from not being able to pass a kwarg to a lockfunc to the default `attr` lockfunc not doing what's expected. I'll look at that. :)

**Comment by Tegiminis** [comment] 2020-06-28 14:37
Ty! Let me know if there's anything I can do to help. Apologies for perhaps being unclear, always nervous sharing code.

**Comment by Griatch** [comment] 2020-06-28 15:09
Np, thanks for clarifying and sticking with it. 

This is fixed now. It was a simple, but subtle error - when parsing the kwargs in the lock string, the key/value was not stripped of whitespace. So in the lockstring, `"cmd: attr(locktest, 80, compare=gt)"`, the "compare kwarg would come into the lockfunc as `**{" compare": 80}` (with an initial space), which will interpreted as no "compare" was given (and thus the `eq` compare-type is used). When calling the lockfunc directly you of course set `compare="eq"` which has no such issue with spaces. 

Fixed in the lockhandler parser now.

**Closed by Griatch** 2020-06-28 15:09 UTC
Labels: bug, more info needed
