### ISSUE TITLE
[Bug] SaverDict Saving Situation

### ISSUE THREAD

**Issue by alephate** [evennia/evennia#2599] opened 2021-12-01 22:14 UTC
#### Describe the bug
When you reference a saverdict in a command, edit it, and then call a function to edit it, and then edit it in the command again -- the editing done in the function is erased.

#### To Reproduce
1. Use this code:
```python
from commands.command import Command

def saverdict_test(caller):
    print(caller.db.test_saverdict)
    caller.db.test_saverdict["test"]["nest"].append("the called function value has saved")
    print(caller.db.test_saverdict)

class CmdTest(Command):
    """Command for testing code, replaceable"""
    key="test"
    locks = "perm(Admin)"
    def func(self):
        caller = self.caller
        caller.db.test_saverdict = {"test": {"nest": []}}
        saverdict = caller.db.test_saverdict
        saverdict["test"]["nest"].append("the value is set up initially from the command func")
        print(caller.db.test_saverdict)
        saverdict_test(caller)
        saverdict["test"]["nest"].append("a second value is set up from the command func")
        print(caller.db.test_saverdict)

```
2. Add CmdTest to your character cmdset.
3. Start evennia in interactive mode, log in, enter 'test', then look at your terminal

#### Expected behavior
You should see something like this:
```

2021-12-01T16:55:28-0500 [stdout#info] {'test': {'nest': ['the value is set up initially from the command func']}}
2021-12-01T16:55:28-0500 [stdout#info] {'test': {'nest': ['the value is set up initially from the command func']}}
2021-12-01T16:55:28-0500 [stdout#info] {'test': {'nest': ['the value is set up initially from the command func', 'the called function value has saved']}}
2021-12-01T16:55:28-0500 [stdout#info] {'test': {'nest': ['the value is set up initially from the command func', 'a second value is set up from the command func']}}
```

#### Environment, Evennia version, OS etc
```

         Evennia version: 0.9.5 (rev 76af934fd)
         OS: nt
         Python: 3.7.9
         Twisted: 20.3.0
         Django: 2.2.5
```

#### Additional context
It has something to do with how saverdicts are managed. I would suggest making all changes to them persistent (?) or making sure this issue is well-known in the documentation.

**Comment by Griatch** [comment] 2022-01-08 17:29
@alephate The function and command are unnecessary; I can reproduce with an even simpler setup: 

```python
>>> obj.db.foo = {"test": {"nest": []}}
>>> foodict = obj.db.foo

>>> foodict["test"]["nest"].append("first value")
>>> print(obj.db.foo)
{'test': {'nest': ['first value']}}

>>> obj.db.foo["test"]["nest"].append("second value")
>>> print(obj.db.foo)
{'test': {'nest': ['first value', 'second value']}}

>>> foodict["test"]["nest"].append("third value")
>>> print(obj.db.foo)
{'test': {'nest': ['first value', 'third value']}}

```

There is a difference between assigning to the 'extracted' `foodict` variable compared to updating directly on the object's `.db` handler. It's rare to mix the update-style like this, so it may not have come up before; the issue is this: 

```python
>>> print(id(foodict)), id(obj.db.foo))
140325612172480 140325611552384
>>> print(id(foodict["test"]["nest"]), id(obj.db.foo["test"]["nest"])
140325612674304 140325612674448
```
As seen, the extracted variable and the entity on the handler is _not_ the same memory object. Same is true when comparing the nested entities. 

So when changing the handler-based value, the stand-alone one is not updated - since they are not the same shared object. When updating the stand-alone value it will only update what it knows which will thus overwrite the previous change. It's essentially a case of out-of-sync cache.

I suspect this is due to the serialization - we deserialize the entity on the handler in order to edit it, and the result is a new entity. Basically it works fine as long as you only modify `foodict` or `obj.db.foo` but not when mixing the two. It's possible there is no real way around this, but I don't remember noticing this behavior in the past so I'll investigate a bit further. If it remains a thing, it's certainly something that should be documented, though.

**Comment by owllex** [comment] 2022-03-02 01:28
I am running into a similar problem where dict data in an attribute isn't getting synced in some cases back to the DB. The ID thing you pointed out above is interesting, because I see (mostly) completely different IDs for the `_SaverDicts` being returned from regular attribute access.

In the following snippet, I just rapid-fired the same command repeatedly and got (mostly) different IDs for the returned objects. I don't have any looping scripts running that are interacting with this attribute. Setting values in these returned dicts does not sync that value back to the DB. This has the humorous effect of causing a test character to revert to being dead every time the server reloads since that's the last successful save of his vitals dict.

```
>>> id(me.db.vitals)
140141277051392
>>> id(me.db.vitals)
140141277255792
>>> id(me.db.vitals)
140141277255792 # Same ID as the previous one. Unsure why.
>>> id(me.db.vitals)
140141277260064
>>> id(me.db.vitals)
140141277252048
```
A similar thing happens if I access the attribute via `obj.attributes.get`

**Comment by Griatch** [comment] 2022-03-02 19:27
So after analyzing this, I have concluded that while the outcome is confusing, this is _not_ a bug. This is the wrong way to operate on Attributes and not something we can support. This is an even simpler example of the effect:

```
> obj.db.foo = [1, 2, 3]
> foo = obj.db.foo 
> obj.db.foo[1] = 5
> obj.db.foo 
[1, 5, 3]
> foo
[1, 2, 3]
```

- When extracting the  `obj.db.foo` into the variable `foodict` we are creating a local copy of the data. This is as expected. 
- When we read data from `foo`, we are _not_ hitting the database, but are working off a local copy of the data. This is usually the reason we want to extract this into a variable in the first place (to avoid extra db reads). `foo`, by nature of being a `_Saver`-structure however retains the ability to _write_ to the database.
- So if we did `foo[1] = 5` above _would_ be detected by `obj.db.foo` since the latter will fetch this from the database directly. 
- However, when we do `obj.db.foo[1] = 5` we are updating the database, but the variable `foo` is _working with a local copy of the data_ - we didn't want it to read the database every time, that's the point! 

So the read/write is assymmetric here. `obj.db.foo` can both read and write from the db, while the extracted variable can write to the database, but not read from it. This is the way the system has always worked actually, it just manifested here in a confusing way. 

There is really only one way to 'resolve' this confusion, theoretically 

- Make `_Saver` structures read their data from the database. That is, it would make no performance difference if you extract to a variable `foo` or just work against `obj.db.foo` all the time. To decouple, you'd always have to use `foo.deserialize()`, regardless of if you are reading or writing. Advantage of this is consistence, the drawback is that a lot of people have been relying on simply extracting to a variable to avoiding hitting the database. 

I don't think this makes much sense though; it's better to expand the Attribute documentation and to not mix writing to the database from two sources like this. 

> Why couldn't one change it so that `obj.db.foo` always deserializes the return instead (so the opposite of the above)? The reason is that doing `obj.db.foo['first']['nest'] = "this"` requires the `.db` handler to return a `_SaverDict` in order to have that change be detected and saved to the database. And Python can't differentiate between returning the `foo` Attribute for accessing it with ['first']['nest']` from returning `foo` to store in a variable (`foo = obj.db.foo`).

**Comment by owllex** [comment] 2022-03-02 20:57
One more question about this before you close it out. In the case of nested `_SaverDicts`, I notice that if you bind a reference to the top-level attribute data, then bind a reference to a nested dict within, they become disconnected, and changes you making using the nested reference actually un-do changes made in the outer reference. See below for an example:
```
>>> me.db.test = {"a": True, "sub": {"b": True, "c": True}}
>>> me.db.test
{'a': True, 'sub': {'b': True, 'c': True}}
>>> outer = me.db.test
>>> inner = me.db.test["sub"]
>>> outer
{'a': True, 'sub': {'b': True, 'c': True}}
>>> inner
{'b': True, 'c': True}
>>> outer["a"] = False
>>> me.db.test
{'a': False, 'sub': {'b': True, 'c': True}}
>>> inner["b"] = False
>>> me.db.test
{'a': True, 'sub': {'b': False, 'c': True}}
```
I assume this is related because the two references, `outer` and `inner` are actually different `_SaverDicts`, but what is unintuitive is that modifying the inner dict ALSO modifies the outer scope. It took a while to track down what was going on here. Is this also working as intended based on your investigation above? This has caused some very sneaky bugs that required more than a novice-level understanding of attributes to diagnose.

**Comment by Griatch** [comment] 2022-03-02 21:10
@owllex Yeah, this is expected. In order for something like `obj.db.foo['outer']['inner'] = False`, the nested structures is actually part of a _tree_. That is, they don't each have an independent reference to the database field, instead each reference the next _outer_ nesting. The outermost nesting is the one with the db-field reference. This is because it would make no sense to update only the inner one (in the database the entire structure must be pickled as one blob after all). 

So what happens when you update the `sub` `_SaverDict` is that it checks if it is the outermost scope (it is not), so it instead finds the back reference to its parent - the `test` dict. This `_SaverDict` is the outermost scope and also has the back-reference to the database (this is why it has to be this weird `_SaverDict` and not a normal dict). When this is reached, the _entire_structure is updated to the database. 

Hope that clarifies things.

**Closed** 2022-03-05 15:43 UTC
Labels: bug, branch-develop, branch-master, not implemented
