### ISSUE TITLE
Object comparisons need `is` instead of `==`

### ISSUE THREAD

**Issue by robbintt** [evennia/evennia#1092] opened 2016-10-03 20:37 UTC
#### Brief summary of issue / Description of requested feature:

Object comparison using `==` instead of `is` causes logic collisions.

See: http://stackoverflow.com/questions/1227121/compare-object-instances-for-equality-by-their-attributes-in-python

#### Steps to reproduce the issue / Reasons for adding feature:

https://github.com/evennia/evennia/blob/c30a55a677006faacea9dd445a24ef4657e6a83b/evennia/commands/default/general.py#L257

I think there is at least one other instance.

#### Error output / Expected result of feature

If an object instance tries to CmdGet at another instance with the same name, the logic will detect that you are trying to get yourself and fail.

**Comment by TehomCD** [comment] 2016-10-04 23:55
After reading that, I looked at TypedObject's __eq__ method, and think I saw a possible problem. The __eq__ method for TypedObject compares dbid, but PlayerDB and ObjectDB both inherit TypedObject, so a dbid comparison could be true when they're different objects. With the exception of the superuser, a PlayerDB's ID is very unlikely to have the same ID as a corresponding Character they might have. So caller == obj could be true or false arbitrarily if caller is a playerdb and obj is an objectdb. I guess have __eq__ for TypedObject also check the .__class__ matching?

**Comment by Griatch** [comment] 2016-10-13 06:07
In a local branch I have modified the `TypedObject.__eq__` to compare both by `dbid` and by `__dbclass__`. Even more curious, the `DefaultObject.__eq__` would deliberately defer so as to make Player and Objects compare as equal. I don't know what the thinking was for that originally.

**Comment by Griatch** [comment] 2016-10-13 17:58
@robbintt  While the changes to `__eq__` mentioned above will happen for other reasons, I cannot reproduce the error in this issue using unmodified master. If I do the following (playing as a character "Griatch"): 

1. @create/drop Griatch
2. get griatch 
3. I get a multi-match telling me to choose between 1-griatch or 2-griatch, where 2-griatch is the new object and 1-griatch is myself. 
4. get 2-griatch 
5. I pick up the object. 

So this works. Obviously, if I do get 1-griatch I will try to pick up myself and will get an error - but this is as expected. Could you give a more specific example for how to reproduce the exact GetCmd error you are experiencing?

**Comment by robbintt** [comment] 2016-10-13 23:09
I now cannot reproduce this following your method.  Sorry, wish I had given more details at the time. Thanks!

**Comment by Griatch** [comment] 2016-10-16 18:09
The changes mentioned earlier in this thread is implemented as of cd9c11f. Since the original problem cannot be reproduced I'm thus closing this. Re-open if the problem should resurface with the latest code.

**Closed by Griatch** 2016-10-16 18:09 UTC
Labels: more info needed, ongoing
