### ISSUE TITLE
utils.spawner fails in testing without overriding PROTOTYPE_MODULES

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1516] opened 2017-11-14 16:57 UTC
#### Brief summary of issue / Description of requested feature:
Using utils.spawner in an Evennia game can fail when testing if one doesn't override PROTOTYPE_MODULES specifically in the setup for the tests.
See [Ainneve's `test_chargen.py`](https://github.com/evennia/ainneve/blob/develop/world/test_chargen.py#L22) for an example.
If one doesn't override PROTOTYPE_MODULES and is using prototype module locations not covered by Evennia core, then tests will fail as the spawner will complain about not finding the specified prototypes.

This happens even if one runs Evennia's tests correctly with `evennia test . --settings=settings.py` or `evennia test --settings=settings.py .`

#### Steps to reproduce the issue / Reasons for adding feature:

1. Set up a test case and use a command/feature that uses the spawner and a customized PROTOTYPE_MODULES location.
2. Run tests correctly via `evennia test --settings=settings.py .`
3. The tests will fail - the spawner will have Evennia's core PROTOTYPE_MODULES instead of your customized PROTOTYPE_MODULES

As a workaround, in the test case setup, override the PROTOTYPE_MODULES as in [Ainneve's `test_chargen.py`.](https://github.com/evennia/ainneve/blob/develop/world/test_chargen.py#L22)

#### Error output / Expected result of feature
The test will fail, as the spawner will return that it couldn't find your prototype - assuming that like Ainneve, you're not using a core Evennia prototype module location.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This is present on the development branch of Ainneve - all tests currently are passing, but if you clone the develop branch and remove the overrides, which are in [`test_chargen.py`](https://github.com/evennia/ainneve/blob/develop/world/test_chargen.py#L22) and [`test_combat.py`](https://github.com/evennia/ainneve/blob/develop/world/test_combat.py#L501), the tests will fail.

**Comment by chainsol** [comment] 2017-11-14 17:08
The failure output is as follows:

`test_chargen.py`
```
FAIL: test_node_equip_insuff_funds (ainneve.world.test_chargen.ChargenTestCase)
test insufficient funds messaging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nmatlaga/Projects/ainneve/ainneve/world/test_chargen.py", line 597, in test_node_equip_insuff_funds
    self.assertIn("You do not have enough money to buy a brigandine.", messages)
AssertionError: 'You do not have enough money to buy a brigandine.' not found in ['________________________________________________________________________________________________________\n\nNext, purchase your starting equipment.\nYou have 0 CC.\nSelect a category of equipment to view:\n________________________________________________________________________________________________________\n\n 1: Melee Weapons    5: Shields                               \n 2: Ranged Weapons   6: Ammunition                            \n 3: Thrown Weapons   Inventory: Show your current inventory   \n 4: Armor            Done: Continue to character description  ', "Menu node 'menunode_equipment_list' is not implemented. Make another choice.", "Menu node 'menunode_equipment_list' is not implemented. Make another choice.", "Choose an option or try 'help'."]
```
`test_combat.py`
```
ERROR: test_attack_fail (ainneve.world.test_combat.AinneveCombatAttackTestCase)
test unsuccessful attacks with weapons
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nmatlaga/.virtualenvs/ainneve/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/nmatlaga/Projects/ainneve/ainneve/world/test_combat.py", line 894, in test_attack_fail
    rulebook._do_attack(0, self.char1, self.char2, [])
  File "/home/nmatlaga/Projects/ainneve/ainneve/world/rulebook.py", line 381, in _do_attack
    ammunition = weapon.get_ammunition_to_fire()
  File "/home/nmatlaga/Projects/ainneve/ainneve/typeclasses/weapons.py", line 81, in get_ammunition_to_fire
    bundle.expand()
  File "/home/nmatlaga/Projects/ainneve/ainneve/typeclasses/items.py", line 84, in expand
    location=self.location))
  File "/home/nmatlaga/Projects/ainneve/evennia/evennia/utils/spawner.py", line 251, in spawn
    _validate_prototype(None, prototype, protparents, [])
  File "/home/nmatlaga/Projects/ainneve/evennia/evennia/utils/spawner.py", line 122, in _validate_prototype
    raise RuntimeError("%s's prototype '%s' was not found." % (key or prototype, protstring))
RuntimeError: {'prototype': 'ARROW', 'location': <Character: Char>}'s prototype 'ARROW' was not found.
```

Both of these, oddly, are fixed via the mentioned workaround. The reason the `test_chargen.py` one doesn't mention the PROTOTYPE_MODULES is potentially related to [this line in `chargen.py`.](https://github.com/evennia/ainneve/blob/develop/world/chargen.py#L416)

**Comment by Griatch** [comment] 2018-01-08 21:41
I think this is probably an extension/specification related to https://github.com/evennia/evennia/issues/1396.

**Comment by chainsol** [comment] 2018-01-08 21:44
I'd agree, though this is maybe a distinct part of solving that issue. I found it really odd that my "fix" of overriding the `PROTOTYPE_MODULES` in the test suite actually worked.

**Comment by Griatch** [comment] 2018-01-10 07:07
I think what needs to happen is to enforce the default settings during tests to a much higher degree.

**Comment by Kelketek** [comment] 2018-01-10 09:41
Use of Django's override_settings decorator is highly recommended here.

**Comment by chainsol** [comment] 2018-01-10 17:06
@Griatch Wait, one moment - this isn't about core unittests failing. This is about Ainneve's custom unittests failing when correctly using `evennia test .`

**Comment by Griatch** [comment] 2018-01-10 17:35
@chainsol Yes, but you are using `EvenniaTest` for the Ainneve test, so I still think this is a symptom of the same thing - not enough isolation of the default test environment from its surroundings.

**Comment by Griatch** [comment] 2019-03-30 22:51
@chainsol I cannot reproduce this on current py3 `develop` branch. I didn't test with Ainneve itself though (not sure where it stands with py3?). Instead I set up the following to test: 

```python
# mygame/typeclasses/myprototypes.py`

MYTEST = {
    "key" = "footest"
}
```
```python
# mygame/commands/command.py

from evennia import Command
from evennia.prototypes.spawner import spawn

class CmdCustomSpawnLocation(Command):
    key = "myspawn"

    def func(self):
        obj = spawn("mytest")
        obj[0].location = self.caller.location

```

I then added this command to my character cmdset and added to my settings file: 

    PROTOTYPE_MODULES += ['typeclasses.myprototypes']

After testing it works to spawn, I then made a test: 

```python
# mygame/typeclasses/tests.py
from evennia.commands.default.tests import CommandTest
from evennia.utils import test_resources
from commands import command

class TestMySpawn(test_resources.EvenniaTest):
    def test_spawn(self):
        self.obj1.execute_cmd("myspawn")

class TestMySpawn2(CommandTest):
    def test_spawn(self):
        self.call(command.CmdCustomSpawnLocation(), "", "")
```

I tested both main base classes above to see if it made any difference. I then run with `evennia test --settings=settings.py .`. Both tests pass for me ... could you check if this is still and issue on Ainneve? In that case it's doing something different from this simple principle and we need to dig deeper.

**Comment by Griatch** [comment] 2019-08-14 18:10
I still cannot reproduce this in Evennia 0.9 and Ainneve is not updated to 0.9 yet so cannot test with that. Closing this until @chainsol says otherwise.

**Closed by Griatch** 2019-08-14 18:10 UTC
Labels: bug, master-branch, more info needed
