### ISSUE TITLE
The CmdHandler is bypassing the obj.access method for the access type 'call'

### ISSUE THREAD

**Issue by Nadorrano** [evennia/evennia#752] opened 2015-06-01 17:44 UTC
The cmdhandler is bypassing the obj.access method for the access type 'call', as it calls `obj.locks.check` directly. This makes impossible to intercept the access in other ways except lockfuncs. The problem is solved replacing `locks.check` with `access` (line 203). I apologise in the case this is the intended behavior.

**Comment by Griatch** [comment] 2015-06-01 18:12
This is the intended behavior since `access()` does not pass on the critical `no_superuser_bypass` kwarg upstream. Without that you will get multiple-command multimatch errors as superuser, since you'd be pulling in commands from other characters in the same room. 

 When looking at it, the access bypass is pretty unexpected though. So it will be fixed so that the `no_superuser_bypass` gets passed on correctly and you can overload `access` like other lock types.

**Comment by Nadorrano** [comment] 2015-06-01 19:05
Thank you. Also, why cmdsets does not have their own locks? It seems that the get_and_merge function will handle this since it "knows" who is the caller. With locks on cmdsets the DarkRoom example will be solved with just a lock check on the darkroom cmdset. Am I missing something here too?

**Comment by Griatch** [comment] 2015-06-01 19:48
Command Sets are much more flexible than you could do with a simple lock - you can merge and filter and make new cmdsets on the fly depending on the situation. You are correct that you could lock the darkroom cmdset with a lock, but what happens when you get "partial light" in that room, so that only some limited commands are available? Would you change the lock? Or when a battle starts in the dark room, so that new combat commands become available on top of the darkroom cmdset? Your lock would then need to account for this somehow, using if statements to represent all combinations. Hence the power of merging cmdsets, which are intended to make the system fully flexible and modular.

If you really want locks, each individual Command is lockable anyway, for very fine-grained control.

**Closed** 2015-06-01 19:57 UTC
