### ISSUE TITLE
First launch, Evennia blocks after trying to restart (Windows)

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1601] opened 2018-03-29 08:12 UTC
#### Brief summary of issue / Description of requested feature:

After `evennia start` has been run for the first time, the superuser is created.  Evennia then tries to restart the portal.  On Windows, it doesn't work: the portal doesn't restart and need a manual `evennia stop` and `evennia start`.

#### Steps to reproduce the issue / Reasons for adding feature:

1. On Windows (perhaps Linux too), create a new game directory (`evennia --init mygame`, `evennia migrate`).
2. Start Evennia for the first time and supply the superuser information: `evennia start`.

#### Error output / Expected result of feature

Evennia says it will be restarting in the console, but it doesn't seem to do so.  The portal isn't accessible even after a few minutes.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

- Evennia develop.

**Comment by BlauFeuer** [comment] 2018-03-29 08:15
This seems related to #1593

**Comment by Griatch** [comment] 2018-03-29 08:28
Yes, this is a duplicate of  #1593. Closing.

**Closed by Griatch** 2018-03-29 08:28 UTC
