### ISSUE TITLE
[BUG] Serializing invalid JSON results in silent failure.

### ISSUE THREAD

**Issue by rowebb** [evennia/evennia#2972] opened 2022-11-03 15:25 UTC
#### Describe the bug
When sending OOB data to a Character, if the data that is being serialized to JSON contains data that does not "cleanly" serialize to a string/JSON structure, the web client will appear to never receive the message (probably blocked on the web client end for being invalid JSON). This manifests as a silent failure with no indication as to why the message was never received on the web client end (save for maybe a message in the debug console).

#### To Reproduce
Define an enum to use:
```python
from enum import Enum
class ValueType(Enum):
    VALUE_1 = 1
    VALUE_2 = 2
```
Now use the enum in a payload to send to the client via:
`
client.msg(cmd_name={"data": ValueType.VALUE_1})
`
This will result in no error being thrown and no message received on the Evennia.js end.

#### Expected behavior
I would expect the msg() method to throw an error if it was generating invalid JSON before it sent it off to the web client.

#### Environment, Evennia version, OS etc
Using the evennia docker image:
    Evennia 0.9.5
    OS: posix
    Python: 3.7.15
    Twisted: 21.7.0
    Django: 3.2.16

**Comment by Griatch** [comment] 2022-11-13 16:31
This will be resolved on the develop branch.

**Comment by Griatch** [comment] 2022-11-13 17:03
@rowebb I can't reproduce this on develop branch: If I make a simple test-command: 

```python 
from enum import Enum 
from evennia import Command 

class MyValue(Enum):
    VALUE_1 = 1

class CmdTest2972(Command):
   key = "test2972"
   def func(self): 
       self.caller.msg(text=(("Test2972",), {"data": MyValue.VALUE_1})
```
Adding this command to the character cmdset and running it with `test2972` indeed gives no visible error; but it does raise a very clear traceback in the log: 
```
|Portal| 2022-11-13 16:58:35 [!!] Traceback (most recent call last):
|Portal| 2022-11-13 16:58:35 [!!]   File "/Home/evennia/evennia/evennia/server/portal/portalsessionhandler.py", line 480, in data_out
|Portal| 2022-11-13 16:58:35 [!!]     getattr(session, funcname)(*cmdargs, **cmdkwargs)
|Portal| 2022-11-13 16:58:35 [!!]   File "/Home/evennia/evennia/evennia/server/portal/webclient.py", line 297, in send_text
|Portal| 2022-11-13 16:58:35 [!!]     self.sendLine(json.dumps([cmd, args, kwargs]))
|Portal| 2022-11-13 16:58:35 [!!]   File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
|Portal| 2022-11-13 16:58:35 [!!]     return _default_encoder.encode(obj)
|Portal| 2022-11-13 16:58:35 [!!]   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
|Portal| 2022-11-13 16:58:35 [!!]     chunks = self.iterencode(o, _one_shot=True)
|Portal| 2022-11-13 16:58:35 [!!]   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
|Portal| 2022-11-13 16:58:35 [!!]     return _iterencode(o, 0)
|Portal| 2022-11-13 16:58:35 [!!]   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
|Portal| 2022-11-13 16:58:35 [!!]     raise TypeError(f'Object of type {o.__class__.__name__} '
|Portal| 2022-11-13 16:58:35 [!!] TypeError: Object of type MyValue is not JSON serializable
```
This seems like the correct behavior to me, so this seems to have been resolved in `develop` branch and will resolve once it merges.

**Comment by rowebb** [comment] 2022-11-15 19:21
Interesting, I can't reproduce this again on my end either. Though it might be because I was serializing data off of the database? Here's an example of the payload I was sending:
`    def to_json(self):
        """
        Serializes the Card to JSON for the webclient.
        """
        return {
                "id": self.dbref,
                "sprite_sheet" : {
                    "images" : [ self.db.sprite_sheet_uri ],
                    "frames" : {
                        "width": self.db.sprite_width,
                        "height": self.db.sprite_height
                    },
                },
                "frame": self.db.sprite_frame,
                "type": self.db._card_type,
            }`

self.db._card_type is an Enum type, which is what was causing it to silently fail. Maybe it has more to do with what I'm getting back on the _card_type attribute rather than the enum?

**Comment by Griatch** [comment] 2022-11-15 19:32
I think the enum should be correctly stored/deserialized from the Attribute - pickling understands Enums just fine (even though JSON doesn't). I don't know where your `to_json` function is located, but if it just passes that return into `msg(foo=(args, to_json_return))`, having enums in the output does seem to produce a correct error in the log. Since you can't reproduce the issue yourself either, maybe we should close this until the issue can be reliably reproduced ...

**Comment by rowebb** [comment] 2022-11-15 19:41
I use the to_json() and add it to an array of cards before sending it off; not sure if packaging them in an array avoids the pickling errors?

**Comment by Griatch** [comment] 2022-11-15 19:42
It seems unlikely, but there's little point in speculating. If you can reliably reproduce the issue by wrapping it in an array, then present the code for doing so, so it can be tested and we can figure out what's going on :)

**Comment by rowebb** [comment] 2022-11-15 19:44
I'll back out the changes I made to fix this originally and see if I can repro on my end.

**Comment by rowebb** [comment] 2022-11-15 19:58
OK I am still able to repro. Here's the full Card class (it's based on the Object classes):

```
class CardType(IntEnum):
    """
    The different types of cards available.
    """
    ACTION = 1
    CONSUMABLE = 2
    ITEM = 3
    NPC = 4

class Card(Object):
    """
    Base class representing Cards
    """

    def at_object_creation(self):
        """
        Inititalize Card values!
        """
        super().at_object_creation()
        self.db._card_type = CardType.ITEM

    @property
    def card_type(self):
        """
        The type of card this is.
        """
        return self.db._card_type

    def to_json(self):
        """
        Serializes the Card to JSON for the webclient.
        """
        return {
                "id": self.dbref,
                "sprite_sheet" : {
                    "images" : [ self.db.sprite_sheet_uri ],
                    "frames" : {
                        "width": self.db.sprite_width,
                        "height": self.db.sprite_height
                    },
                },
                "frame": self.db.sprite_frame,
                "type": self.db._card_type,
            }
```

Here's the serialization part; we have a list of cards that get created and then we call to_json on each and append them to a new list before sending it off to the client:

```
        actions = []
        for a in self.db.equipped_cards:
            actions.append(a.to_json())
        self.msg(update_bar={"actions": actions})
```

**Comment by Griatch** [comment] 2022-11-15 20:20
Thanks for the example! Most of this means nothing to me for the sake of reproducing; I don't have what `sprite_frame` or `sprite_frame` looks in this instance. So I cut it down to the minimal parts: 

```python 
class MyValue(Enum):
    VALUE_1 = 1
    VALUE_2 = 2


class CmdTest2972(Command):
    key = "test2972"
      
    def to_json(self):
         """
         Serializes the Card to JSON for the webclient.
         """
         return {   
             "type": self.caller.db._card_type,
    }
                                                                                
    def func(self):                                                            
        # self.caller.msg(text=(("Test2972",), {"data": MyValue.VALUE_1}))     
        self.caller.db._card_type = MyValue.VALUE_1                            
        self.caller.msg(dummy=[self.to_json() for i in range(5)])
```

This should be functionally the same as what you have, and I get an exception every time.

Have you checked for other, simpler, errors here - like `db.equipped_cards` being an empty list (so nothing is actually sent)?

**Comment by rowebb** [comment] 2022-11-15 20:23
Yeah, I've had the full message sent as text to the client as well as the OOB "update_actions" command, the text looked good and the OOB command never was sent. I'll do some more digging to see why my scenario is not producing the right errors.

**Comment by Griatch** [comment] 2022-11-30 22:20
@rowebb I'll close this now since this works as expected as far as I can determine. If your issue can be reliably reproduced in plain Evennia, feel free to comment here and I can reopen again.

**Closed by Griatch** 2022-11-30 22:20 UTC
Labels: bug, branch-develop, devel-implemented, more info needed
