### ISSUE TITLE
NPC Shop crashes server

### ISSUE THREAD

**Issue by DauntlessAutumn** [evennia/evennia#893] opened 2015-12-05 08:32 UTC
Hi all. Great project, amazing stuff.

I'm having an issue with the tutorial implementation of the NPC Shop.

Out of the box, it works fine in the store, the buy command (in my case I'm using 'browse') brings up the menu. Initially, it did show the exit leading back to the storefront in the shops wares, but that was an easy fix.

The issue starts when you call the buy command outside of the shop. It produces this:

> Error in menu node 'menunode_shopfront'.
> An untrapped error occurred. Please file a bug report detailing the
> steps to reproduce. Server log time stamp is '2015-12-05 18:17:26+1000'.

After that, other commands just produce this error:

> An untrapped error occurred. Please file a bug report detailing the
> steps to reproduce. Server log time stamp is '2015-12-05 18:24:38+1000'.
> A command handler bug occurred. Please file a bug report with the
> Evennia project. Include the relvant traceback from the server log at
> time stamp '2015-12-05 18:24:38+1000'.

This is what the cmd log spits out:
[npcshop_error_log.txt](https://github.com/evennia/evennia/files/52782/npcshop_error_log.txt)

I have to stop and start the server to regain control.
I figure one solution would be to perform a check to make sure the calling character
is in a room that's the npcshop typeclass, but I'm not sure exactly how to go about that.

Thanks in advance!
Here's my npcshop.py in .txt format.
[npcshop_debug.txt](https://github.com/evennia/evennia/files/52781/npcshop_debug.txt)

**Comment by Griatch** [comment] 2015-12-05 11:44
@DauntlessAutumn 

Hi there!  You write that you get the error by calling the `buy` command from outside the store. This is not possible unless you have added `CmdBuy` to your default character cmdset as well. Don't do that, the only command you should add from the tutorial is the command for building the shop in the first place - that will in turn add `CmdBuy` to the *shop's front room*, making the command available to you *only* when you are actually inside the shop. 

I just tried this with your `npcshop.py` and it works as expected - whenever leaving the shop you can no longer use the `CmdBuy` command, so no error can occur.

If you want a more general "buy" command that is available everywhere in the game you can't use this particular implementation since it depends on being called only in a very particular type of room. 

(You can have both though - you could have a generic "buy" command on the character cmdset for use everywhere else (you need to code this yourself) and then just set a slightly higher priority to the cmdset in the shop (for example `priority=1`) - the shop's buy-command will then temporarily override the normal one while the player is in the shop.)

As far as I understand this is not a bug in the tutorial, so I'm closing this. Do comment again and ask to re-open if I misunderstood something. :)

**Closed by Griatch** 2015-12-05 11:44 UTC
