### ISSUE TITLE
[Feature Request] Documentation build puts a lot of untracked files in source tree

### ISSUE THREAD

**Issue by audiodude** [evennia/evennia#2899] opened 2022-10-04 00:55 UTC
#### Is your feature request related to a problem? Please describe.
When building the docs with `make local`, I get a bunch of untracked files in my git source tree including modifications of files that are checked in. This makes it difficult and error-prone to isolate my documentation changes and check them in.

#### Describe the solution you'd like
I don't know why these files get dynamically edited by the docs process, but I guess the solution would be to minimize the changes to a "staging" area of sorts that could be git ignored?

#### Alternatives you've considered
None.

#### Additional context
None.

**Comment by audiodude** [comment] 2022-10-04 00:56
![image](https://user-images.githubusercontent.com/57832/193711821-4a24d49d-cccd-4e29-b077-70aa96e155fe.png)

**Comment by audiodude** [comment] 2022-10-04 00:56
ignore `../.netlify/`, that's my netlify deploy for demoing docs.

**Comment by Griatch** [comment] 2022-10-04 06:56
This is not a bug; these are files that are auto-generated from code - we auto-generate doc pages for new contributions, so they can be easily found. So [this page](https://www.evennia.com/docs/1.0-dev/Contribs/Contribs-Overview.html) is completely auto-generated, and all the pages linked from it is also generated based on the README files of each contrib the system finds. In addition the build system auto-correct internal links to the doc pages, so if missing an absolute path, the `.md` file may be updated in-place to have its links correctly point to the right place in the tree. 

In this case, there were contribs added, but I had not run/committed the automatic doc additions that were generated. I did this yesterday, so if you pull and use the latest Evennia develop branch you should not be seeing these contrib .md pages being generated anymore.

**Closed by Griatch** 2022-10-04 06:56 UTC
Labels: feature-request
