### ISSUE TITLE
Server still logging after evennia stop

### ISSUE THREAD

**Issue by cwingho** [evennia/evennia#1680] opened 2018-10-08 15:37 UTC
#### 1. Brief summary of issue / Description of requested feature:
After execute evennia stop, a python program still writing the **yourmud/server/logs/server.log** file. It seems that the amp_client.py (**/evennia/server/amp_client.py**) still running after shutting down the server.

#### 2. Steps to reproduce the issue / Reasons for adding feature:

1. cmd evennia start
2. cmd evennia stop

#### 3. Error output / Expected result of feature
**yourmud/server/logs/server.log**
```
18-10-08 15:10:48 [..] Server disconnected from the portal.
18-10-08 15:10:50 Attempting to reconnect to Portal ...
18-10-08 15:10:52 Attempting to reconnect to Portal ...
18-10-08 15:10:56 Attempting to reconnect to Portal ...
18-10-08 15:11:01 Attempting to reconnect to Portal ...
18-10-08 15:11:09 Attempting to reconnect to Portal ...
18-10-08 15:11:19 Attempting to reconnect to Portal ...
18-10-08 15:11:27 Attempting to reconnect to Portal ...
18-10-08 15:11:39 Attempting to reconnect to Portal ...
18-10-08 15:11:51 Attempting to reconnect to Portal ...
18-10-08 15:12:00 Attempting to reconnect to Portal ...
18-10-08 15:12:10 Attempting to reconnect to Portal ...
18-10-08 15:12:24 Attempting to reconnect to Portal ...
18-10-08 15:12:33 Attempting to reconnect to Portal ...
```

#### 4. Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Environment: OSX High Sierra 10.13.4
Current solution: kill the python process manually

**Comment by Griatch** [comment] 2018-10-08 19:52
@cwingho The Portal should be telling the Server to shut down *before* the Portal itself shuts down. I can't reproduce this, not sure if it's Mac related or not. If you look at the `portal.log` file, do you see anything out of the ordinary?

**Comment by cwingho** [comment] 2018-10-09 02:31
@Griatch Thanks for reply. It looks normal.
```
18-10-08 15:07:27  |Portal| Loading /Users/HO/Desktop/mymud/evennia/evennia/server/portal/portal.py...
18-10-08 15:07:27  |Portal| Loaded.
18-10-08 15:07:27  |Portal| twistd 18.7.0 (/Users/HO/Desktop/mymud/pyenv/bin/python 2.7.10) starting up.
18-10-08 15:07:27  |Portal| reactor class: twisted.internet.selectreactor.SelectReactor.
18-10-08 15:07:27  |Portal| AMP starting on 4006
18-10-08 15:07:27  |Portal| Telnet starting on 4000
18-10-08 15:07:27  |Portal| Websocket (WebSocketFactory) starting on 4002
18-10-08 15:07:27  |Portal| Webserver-proxy starting on 4001
18-10-08 15:08:55  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53598)
18-10-08 15:08:55  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53600)
18-10-08 15:08:57  |Portal| Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53605)
18-10-08 15:10:49  |Portal| (TCP Port 4001 Closed)
18-10-08 15:10:49  |Portal| (TCP Port 4002 Closed)
18-10-08 15:10:49  |Portal| (TCP Port 4000 Closed)
18-10-08 15:10:49  |Portal| (TCP Port 4006 Closed)
18-10-08 15:10:49  |Portal| Main loop terminated.
18-10-08 15:10:49  |Portal| Server Shut Down.
```

**Comment by Griatch** [comment] 2018-10-13 09:37
@cwingho That memory error I've not seen before. Yes that does sound very fishy. If you can reproduce this, could you monitor the memory use of your server to see what it uses, and how much the Evennia processes take up?

**Comment by Griatch** [comment] 2019-03-31 19:26
Closing this since there is no further info.

**Closed by Griatch** 2019-03-31 19:26 UTC
Labels: bug, master-branch
