### ISSUE TITLE
[BUG] Access Method returning Incomplete Tuple

### ISSUE THREAD

**Issue by rainmaze** [evennia/evennia#2040] opened 2020-01-27 23:04 UTC
#### The Bug
Familiarising myself with Evennia, I was running through the [First Steps coding](https://github.com/evennia/evennia/wiki/First%20Steps%20Coding) tutorial.  As documented, I re-wrote the `at_object_creation` function in the `Character` class to assign 3 persistent ability attributes (self.db.strength, self.db.agility, self.db.magic) the values of 5, 4, and 2 respectively. Then, I wrote a function to return those values as a tuple.

When I `@reload`, `@update`, and call this function in-game, however, it only returns the first element, 5. The entries exist in the database, confirmed with `@examine self`, and the values can be printed and indexed from the tuple.

#### Input

In typeclasses.characters, as found in the documentation:
```

    def at_object_creation(self):
        """
        Called only at initial creation. This is a rather silly
        example since ability scores should vary from Character to
        Character and is usually set during some character
        generation step instead.
        """
        #set persistent attributes
        self.db.strength = 5
        self.db.agility = 4
        self.db.magic = 2

    def get_abilities(self):
        """
        Simple access method to return ability
        scores as a tuple (str,agi,mag)
        """
        return self.db.strength, self.db.agility, self.db.magic
```

#### Expected Result
`@py self.get_abilities()`
*\>\>\> (5, 4, 2)

Evennia correctly returns all elements in the tuple corresponding to persistent data.

#### Actual Result

`reload`

 Server restart initiated ...
 ... Server restarted.
`update rainboa`
rainboa updated its existing typeclass (typeclasses.characters.Character).
Only the at_object_creation hook was run (update mode). Attributes set before swap were not removed.
`py self.get_abilities()`
\>\>\> self.get_abilities()
5
`examine self`

Name/key: rainboa (\#1)
Session id(s): \#1
Account: rainboa
Account Perms: <Superuser>
Typeclass: Character (typeclasses.characters.Character)
Location: Limbo (\#2)
Home: Limbo (\#2)
Permissions: developer [Superuser]
Locks:      ...
Commands:      ...
Persistent attributes:
 desc = This is User #1.
 prelogout_location = Limbo
 strength = 5
 agility = 4
 magic = 2

#### Steps Taken
I have:
- Tried this on a clean database.
- Tried this on a new character.
- Reproduced this in Linux and Windows.
- Experimented with writing different functions that do the same thing.
- Experimented with making the attributes non-persistent.

##### OS
1. Windows 10Ver1909 (64-bit) build 18363.592
2. Debian GNU/Linux 10

##### Python, Evennia, Etc
Evennia version: 0.9.0 (rev 798cacc2)
         OS: nt
         Python: 3.8.1
         Twisted: 19.10.0
         Django: 2.2.9

**Comment by strikaco** [comment] 2020-01-28 00:16
Interesting. There is a simpler way to prove this as well:

```
>>> self.db._something = (1,2,3)
>>> self.db._something
1
>>> self.msg(self.db._something)
```

**Comment by rainmaze** [comment] 2020-01-28 09:37
Much simpler, yeah. I'm just a bit new to this, is my report going to be frustrating to read seeing as we can get this in far fewer steps?

**Comment by strikaco** [comment] 2020-01-28 16:11
No, not at all, your report was fine :)

**Comment by Griatch** [comment] 2020-01-28 17:34
Huh. This is a curious one.

**Comment by Oscuro87** [comment] 2020-01-28 17:41
Hello,

Have you tried with the following notation:
```
return (self.db.strength, self.db.agility, self.db.magic)
```
? Your notation should not be an issue be you never know.

Also, wouldn't this behaviour be caused by the fact that Evennia has to make a db query, which would be a non "instant" response, leading to this? But perhaps the query was cached, then idk...

Try caching the db query results, possibly, like this:
```
def get_abilities(self):
        """
        Simple access method to return ability
        scores as a tuple (str,agi,mag)
        """
        strength = self.db.strength
        agility = self.db.agility
        magic = self.db.magic
        return strength, agility, magic
```
I'm not even sure it would change anything though :thinking:

**Comment by Griatch** [comment] 2020-01-28 17:44
Can confirm e.g.
 
    py self.db.foo = (1,2,3)
    py self.db.foo
    >>> 1

An equivalent list works, so there is something iffy specifically with the tuple.

**Comment by volundmush** [comment] 2020-01-28 17:44
It looks like this robably has something to do with how @py is converting a tuple to a string representation, and not the data.

**Comment by rainmaze** [comment] 2020-01-28 17:53
Agreed, I can't get anything but `@py` to do it, the data remains.

@Oscuro87 tried both, but they ultimately imply the same type of data so the result was the same. Thank you :-)

**Comment by Griatch** [comment] 2020-01-28 17:54
Yes, it's appears to be a py-display issue when using the `py` command as a one-liner. Starting the full `py` interpreter in-game will also show the full tuple correctly.

**Comment by rainmaze** [comment] 2020-01-28 18:00
Confirmed:

`self.db.x = 3, 9, 27`
`py self.db.x`
>>> self.db.x
3
`py`
[py mode]
`self.db.x`
(3, 9, 27)

**Comment by Griatch** [comment] 2020-01-28 18:05
Let's not close this quite yet. Let's resolve the issue even though the cause was different.

**Comment by rainmaze** [comment] 2020-01-28 18:07
Sure, apologies there.

**Comment by Griatch** [comment] 2020-01-28 18:12
Np, just happy it was no worse bug than that. Resolved now.

**Closed** 2020-01-28 18:12 UTC
Labels: bug

**Comment by strikaco** [comment] 2020-01-29 17:21
@Oscuro87 
> Your notation should not be an issue be you never know.

Even though that wasn't the issue in this case, this is still a fair concern to be wary of in any Python codebase that was ever ported from 2.x to 3.x. There are quite a few subtle syntactical gotchas that were introduced in that migration, affecting even basic mechanics like how the division operator works :/

**Comment by Oscuro87** [comment] 2020-01-29 17:54
> @Oscuro87
> 
> > Your notation should not be an issue be you never know.
> 
> Even though that wasn't the issue in this case, this is still a fair concern to be wary of in any Python codebase that was ever ported from 2.x to 3.x. There are quite a few subtle syntactical gotchas that were introduced in that migration, affecting even basic mechanics like how the division operator works :/

True, I even remember when I first came across python 3, and all my `print "some string"` suddenly died :rofl:. Thankfully the error message was developer friendly IIRC.
