### ISSUE TITLE
Evennia Telnet Parser Accepts NullByte Commands

### ISSUE THREAD

**Issue by biscuitWizard** [evennia/evennia#1008] opened 2016-07-16 08:42 UTC
#### Brief summary of issue / Description of requested feature:
The evennia telnet access accepts "Nullbyte" commands. These are line terminators sent without any other content. Convention has been for PennMUSH/TINY/Etc to eat these as primitive "keepalives" sent by some clients. To keep backwards compatibility, the suggestion here is to just do the same. If only a line terminator is sent to the server, ignore it (but consider the connection 'still alive')

#### Steps to reproduce the issue / Reasons for adding feature:

1. Use the POTATO MUSH Client
2. Under world settings/connection enable "Send Nullbyte Keepalives"
3. Log in and wait on an Evennia server.

#### Error output / Expected result of feature
Receive: Command '' is not available. Type "help" for help.

Expected: The server does not response or send an error.

**Comment by BlauFeuer** [comment] 2016-07-16 09:02
Packets with an ACK flag and 0 size can be TCP Keepalive packets, but I think POTATO's getting it wrong by sending nullbyte at the Telnet level instead of using the Telnet IAC and NOP (bytes 255 and 241).

It does make sense to treat the null character sent as a command in the same way as the `idle` command, however.  Sending no character (truly '') is ignored (although this unidles your session), but sending '^@' is actually a character, albeit a null one.

**Comment by biscuitWizard** [comment] 2016-07-16 09:48
I don't have a link to the MUX documentation specifically, but it's actually correct for older games. It's a weirdly undocumented thing clients have to do for older games like MUX that will "silent disconnect" clients.

**Comment by BlauFeuer** [comment] 2016-07-16 11:33
Heh! Well, uncheck the box, 'cause you don't have to do that for Evennia.

**Comment by biscuitWizard** [comment] 2016-07-17 06:12
Yes. This is just a point to make sure we include that backwards compatibility in Evennia. :) It is important as some clients do not offer the ability to disable that feature.

**Comment by biscuitWizard** [comment] 2016-07-17 06:12
It is crucial there are no regressions in Evennia. As all MUSH servers don't treat null terminators as commands. ^_^

**Comment by Griatch** [comment] 2016-07-17 22:12
This is not a regression of Evennia. The ability to treat the empty return as a command is crucial and useful for several functions, such as allowing the line text editor to insert new paragraph or allowing game menus to accept default options (e.g pressing return to accept a proposed default option) or to pages when reading a long text.

So this is not something we'll remove. What we *can* do however is to add a Session option (together with an update to `@option` to set/save it) to allow those for which it matters to switch Evennia to handle empty command input as (yet another) keepalive.

**Comment by BlauFeuer** [comment] 2016-07-17 22:26
Sending the null character is a different thing than sending an empty line (no character).

You don't get that message `Command '' is not available. Type "help" for help.` with an empty line; you get it with a null character.

I personally prefer how Evennia currently handles empty lines (someone pressing return in the client) - it is exactly how most other mu* handle them - much like a "wait" or "do nothing" - the session is unidled (shown as active), but the character does nothing.  It is different from the `idle` command where the session is not marked as unidled.

More to the point, unless you named a command <the null character>, I think @biscuitWizard is just asking for <the null character> to be treated as if the `idle` was sent - because it seems like a legacy behavior and POTATO client offers that option for it.  What's up for debate should be if Evennia wants to emulate that legacy behavior just because a client offers the option.

**Comment by Griatch** [comment] 2016-07-17 22:36
Ah, I was confused by the original issue mentioning 'line  terminator'. It does sound wrong if the NULL comes across as the empty string although I know why; the reason for this is that the EmptyCommand is not correctly absorbing the null the way it does a single line return. 
I can't  look into this further at this time, but in general it sounds okay to make the raw null into a keepalive if this helps anyone.

**Comment by biscuitWizard** [comment] 2016-07-17 23:25
Blau: I will say it's not just Potato. Multiple clients do this made for MUDs, and we should likely try to keep compatibility with all of them. MuckClient (while defunct) is still seen in the wild and does this behavior, for example. (And there are more). I'd hate to have to answer for a player who logs onto my game and says: "Hey, I don't know why but I keep getting this error every five minutes."

**Comment by BlauFeuer** [comment] 2016-07-18 00:19
Word to your users!  Hang tight, the future is coming soon.

How about every 30 seconds, the client gets Evennia's noopkeepalive and displays a gremlin character?  That's a bug in the client, just like assuming the mu*'s going to respond to a `<null character>` being sent as if it was a command.  It's not just any one client that's aberrant; it's become an undocumented expected behavior for all ancient mu*.

"I know exactly why you're getting this error - it's your client." is my response when the nokeepalive's Evennia sends is interpreted incorrectly by the client.  Here, we have the reverse - the mu* is not a legacy mu*, and the client expects it to be.  In my opinion, it's just not a bug in Evennia; you've made a feature request, just like I did when I asked for the `@option nokeepalive=off`.  Fortunately, now I can tell them "Try setting this option to counteract your aberrant client...."

I'm certainly not against Evennia (or any mu*) responding to the `<null character>` being sent as a command and silently calling that session still active, and the character still idle (same behavior the `idle` command has).  I just don't want the behavior of hitting enter and sending a blank/empty line to change.  As  Griatch says, that behavior shouldn't and can't change.

The most elegant and simple solution is probably what you are asking for: `<null character>` sent as a command (which is seemingly what POTATO is doing when you select that option), is treated as if the client sent `idle` as a command. Unless someone's got any other use case for responding to a command named  `<null character>` , I have no issue with it being Evennia's default behavior.  Otherwise, to make this behavior game-specific, you'd have to make a new command named `<null character>` and have it do whatever you want - it could be your "secret command" that only those certain clients know.

You could probably make a game-specific work-around, or Evennia patch for this issue until someone can make a PR to change this in Evennia.  I really don't think it needs a whole `@option` setting in this case; it can just silently deal with it in the same way a legacy mu* might.  I fully understand having to explain the protocol difference between client and mu*, and there's a lot of that in the wild.  I had users complain for a few months about Evennia's protocol-compliant keepalive until Griatch gave us the option to turn it off.

**Comment by biscuitWizard** [comment] 2016-07-18 00:23
Yes, unfortunately this is what happens when you have technology from the 60s.

**Closed** 2016-08-07 12:38 UTC
