### ISSUE TITLE
Web client doesn't work behind TLS-enabled reverse proxy.

### ISSUE THREAD

**Issue by ghost** [evennia/evennia#1421] opened 2017-09-07 21:50 UTC
#### Brief summary of issue / Description of requested feature:
Web client doesn't work behind TLS-enabled reverse proxy. I was unable to find this issue being duplicated on any forums or on the issue tracker. It works fine when not being accessed through the reverse proxy.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Set up NGINX reverse proxy at server 1 with reverse proxy, TLS enabled

2.  Install game server/portal on server 2, then try to access the web client.

3. ???

4. Don't profit, because it doesn't work.

#### Error output / Expected result of feature
Blank output at web client interface. 

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

EDIT:
Current solution: Fallback to AJAX by disabling Websocket-enable as recommended by @chainsol .

**Comment by chainsol** [comment] 2017-09-07 21:52
Can confirm this. Workaround is disable Websocket-enabled webclient - it'll fallback to AJAX.
Currently working on [my development server](mud.perfectdisorder.net)

**Comment by bostrt** [comment] 2017-12-10 22:14
I was able to get a TLS reverse proxy working with websockets by doing the following:

1. Update [base.html](https://github.com/evennia/evennia/blob/master/evennia/web/webclient/templates/webclient/base.html#L46-L50) to look like below (removed the `:{{websocket_port}}` part inside of `if` block.):
```
{% if websocket_url %}
    var wsurl = "{{websocket_url}}";
{% else %}
    var wsurl = "ws://" + this.location.hostname + ":{{websocket_port}}";
{% endif %}
```
2. Then, inside of my `server/conf/settings.py`, I set `WEBSOCKET_CLIENT_URL` to be `wss://external-hostname.com/ws` which points to my TLS reverse proxy server.
3. Finally, in my reverse proxy server, I configured it to proxy any `/ws` requests to `ws://127.0.0.1:4005/`.

If everyone thinks this is acceptable, I would be happy to submit a pull request updating `base.html` and the docs.

**Comment by chainsol** [comment] 2017-12-10 22:28
Exciting! I'll try that out! If that works it seems like a great idea!

**Comment by chainsol** [comment] 2017-12-11 15:57
@bostrt Could you go more into detail on your reverse proxy setup? I've tried in Apache, but it doesn't seem too happy with proxying websockets for whatever reason.

**Comment by bostrt** [comment] 2017-12-11 16:35
Yes, seems to work for me fine. I see the websocket request receiving a `101` status with the `Upgrade: websocket` response header. Here's my httpd configuration:

```
<VirtualHost *:80>
  ServerName external.example.com
  Redirect / https://external.example.com
</VirtualHost>

<VirtualHost *:443>
  SSLEngine On
  ServerName external.example.com
  SSLCertificateFile /etc/pki/tls/certs/external.example.com.crt
  SSLCertificateKeyFile /etc/pki/tls/private/external.example.com.key
  SSLProtocol TLSv1.2
  SSLCipherSuite HIGH:!eNULL:!NULL:!aNULL
  ProxyPass /ws ws://127.0.0.1:4005/
  ProxyPassReverse /ws ws://127.0.0.1:4005/
  ProxyPass / http://127.0.0.1:4001/
  ProxyPassReverse / http://127.0.0.1:4001/

  ErrorLog logs/evennia_error.log
  CustomLog logs/evennia_access.log combined
</VirtualHost>
```

Then, in my `/home/mud/ainneve/server/conf/settings.py` I added the folllowing. Especially note that `/ws` addition; this is key in allowing httpd to differentiate between plain HTTP requests and the websocket requests without the need for a `RewriteRule`. Also, make sure to have the change to `base.html` I mentioned in https://github.com/evennia/evennia/issues/1421#issuecomment-350586031 :

```
WEBSOCKET_CLIENT_URL = "wss://external.example.com/ws"
```
Finally, here's my javascript console output when connecting to the webclient. No failure mentioned there:

```
evennia.js:447 {"0":"Trying websocket ..."}
evennia.js:447 {"0":"Evennia initialized."}
```

**Comment by bostrt** [comment] 2017-12-11 17:45
Oh! Also, if you are using SELinux, make sure to allow httpd to make the outgoing proxy connection:

```
# setsebool httpd_can_network_connect on
```

**Comment by chainsol** [comment] 2017-12-11 17:55
OK, I can confirm this as working with your modifications! Something was off about my Evennia instance, who knows what, but a fresh instance and the changes you describe and we're off to the races - Evennia's webclient with SSL! As long as @Griatch thinks that change makes sense I think you've hit the nail on the head!

**Comment by Griatch** [comment] 2017-12-12 17:39
This looks like a good way to resolve it. A PR with the base.html update along with a wiki update describing the proxy would be highly useful I think.

**Comment by bostrt** [comment] 2017-12-13 00:33
At what point should docs be updated? I'm happy to do that in addition to PR #1530.

**Comment by Griatch** [comment] 2017-12-15 22:39
@bostrt The time would be once the PR has been merged - which is now. :)

**Comment by bostrt** [comment] 2017-12-16 19:42
@Griatch @chainsol  I've worked in the documentation on https://github.com/evennia/evennia/wiki/Apache-Config

**Comment by Griatch** [comment] 2017-12-16 19:50
@bostrt Thanks! I wonder how many actually use apache as a proxy these days (it would seem something more light weight like nginx would be better) but this looks like a good update overall!

**Comment by bostrt** [comment] 2017-12-16 20:25
@Griatch Agreed! However, I think the same `WEBSOCKET_CLIENT_URL` update will still apply to applications like nginx/haproxy/etc. Unfortunately, I'm not quite as familiar with those.

**Comment by chainsol** [comment] 2017-12-16 21:29
I've tried this with NGINX, and it's not ideal. The websocket server ignores the X-Forwarded and X-Host headers, so everyone ends up with localhost/127.0.0.1 as their ip.

**Comment by bostrt** [comment] 2017-12-16 21:43
@chainsol Can you post your nginx config you are using? I am curious to try and help out with alternative webservers like NGINX.

**Comment by wyrdathru** [comment] 2018-01-27 21:00
I just ran into this issue now myself, so have disabled web sockets until I figure it out. I'm using nginx as well so will update if I encounter a solution. If anyone else has made any progress on this, however, it'd be more than welcome!

**Comment by Griatch** [comment] 2018-01-27 21:13
@wyrdathru, @chainsol Since @bostrt asked for an nginx config for further debugging, maybe one of you might suppy one?

**Comment by chainsol** [comment] 2018-01-27 21:37
@Griatch Absolutely - except that I've switched to Apache because although I was able to make NGINX work, the forwarding did not correctly work with Evennia itself.

```
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	server_name mydomain.com;

	include /etc/nginx/snippets/letsencrypt.conf;

	location / {
		return 301 https://mydomain.com$request_uri;
	}
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name mydomain.com;

  ssl_certificate /etc/letsencrypt/live/www.mydomain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.mydomain.com/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/www.mydomain.com/fullchain.pem;
  include /etc/nginx/snippets/ssl.conf;

  location / {
    proxy_pass http://127.0.0.1:4001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /ws/ {
    proxy_pass http://127.0.0.1:4005;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
}
```

**Comment by Griatch** [comment] 2018-01-28 09:42
As for the use of `X-FORWARDED-FOR` and IP spoofing, this is useful security info: http://esd.io/blog/flask-apps-heroku-real-ip-spoofing.html

**Comment by wyrdathru** [comment] 2018-01-28 15:11
Okay, so essentially this is my setup to get SSL + WSS working with an Nginx setup:

- Modify `evennia/web/webclient/templates/webclient/base.html` with the changes outlined in @bostrt 's comment [here](https://github.com/evennia/evennia/issues/1421?_pjax=%23js-repo-pjax-container#issuecomment-350586031).
- Modify `settings.py` to include `WEBSOCKET_CLIENT_URL = 'wss://www.mydomain.com/ws'`
- Add the entry to your Nginx conf to support your Websockets:
```
    location /ws {
        proxy_pass http://mydomain.com:4005;

        # HTTP -> WebSocket handover
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Set this or the connection times out. Default is 60s - this won't do. Maybe consider trying to disable timeout or set it ridiculously high. This is one funky gotcha. 
        proxy_read_timeout 86400;
    }
```
- Make sure you `sudo service nginx reload` and `evennia reload`.

**Comment by chainsol** [comment] 2018-01-29 14:54
@Griatch: On Apache, I haven't had to do anything with `X-FORWARDED-FOR` - everything just works, for whatever reason, which is nice. On NGINX, every IP address will appear to be the local IP address (since I don't make the ports public, I just proxy to 127.0.0.1) when not using something similar to `X-FORWARDED-FOR`.

That article you linked suggests using `X-FORWARDED-FOR` and a middleware suggested by the author to correctly interpret that list and avoid injection of IPs - which is a good idea, and could probably be implemented by Evennia easily...however our websocket client ignores the `X-FORWARDED-FOR` header anyway, as far as I can tell.

**Comment by chainsol** [comment] 2018-01-30 22:50
To give a little update to this issue - to get it working on Apache, one might have to enable `mod_proxy_wstunnel`. I still get an odd timeout issue, though - my connection drops after a minute or two.

**Closed** 2018-09-30 13:01 UTC
Labels: bug, help wanted, master-branch
