### ISSUE TITLE
[BUG] Random I/O Errors

### ISSUE THREAD

**Issue by jumpscarejumpscare** [evennia/evennia#2527] opened 2021-09-09 19:33 UTC
#### Describe the bug
Sometimes (maybe 1 time out of every 1,000 commands), Evennia just can't access the DB, giving disk I/O errors. This has been happening for about a year.

#### To Reproduce

1. Script inside characters.py
```python
    class ActionQueueHandler(DefaultScript):
        """
        Lies dormant while queue is empty.
        Is active while queue is not empty.
        Calls a valid action (at time of entry) from the action queue and attempts to run it. The action is removed from the action queue and this script is restarted, waiting for the next interval in the queue.

        def at_script_creation(self):
            self.key = "queue_handler"
            self.desc = "Handles timing for actions in a queue."
            self.persistent = True
            self.interval = 1

        def at_start(self):
            # We're going to resolve stuff in our queue if it was still there prior to a restart. If there's nothing to resolve, we pause.
            if not self.obj.db.action_queue:
                self.pause()

        def at_repeat(self):
            #Run 1st item in queue, remove it from queue, pause if queue is empty, then restart script
            if not self.obj.db.action_queue:
                self.pause()
            else:
                self.obj.resolve_action(self.obj.db.action_queue[0][0])
                self.obj.db.action_queue.pop(0)

            if not self.obj.db.action_queue:
                self.pause()
            else:
                # Step 1: When we restart, we pause the interval, then we trigger at_repeat and resolve it above.
                self.restart ( interval = self.obj.db.action_queue[0][1], start_delay=True )
```
2.Also in characters.py, this is the thing you call to add something to the queue.
```python
    def queue_command(self, queue_string, delay):
        """
        Queues up a command to be run.
        queue_string is command, [space], arguments
        delay is how long to delay after running
        to do a multi-step command, you have to call this after the first command completes
        """
        aq_empty = False
        if self.db.action_queue == []:
            aq_empty = True
        #self.msg("We appended: " + queue_string + " @ " + str(delay) + "sec.")
        self.db.action_queue.append([queue_string, delay])
        # Because the delay always happens first, we don't need to restart the queue_handler unless the action queue is empty. An empty action queue means the queue_handler is inert.
        if aq_empty == True:
            #self.msg("We restarted the queue_handler because it was paused.")
            _aqh = self.scripts.get('queue_handler')
            _aqh[0].restart(interval=delay, start_delay=True)
```
3. Lastly is this, where you put whatever you want to resolve the queued action. Put a ton of DB accesses and writes in here, for example.
```python
    def resolve_action(self, queue_string):
        # Put a bunch of DB accesses and writes here.
        if self.db.something:
            self.db.something += 1
        else:
            self.db.something = 1
        self.msg("This has worked correctly " + str(self.db.something) + " times.")
        # restart this whole thing from the beginning
        self.queue_command("whatever", 1)
```
4. To start it, you'll need a command that calls
    self.caller.queue_command("whatever", 1)
and it might be handy to have a command to stop it from going, which just needs
    self.caller.db.action_queue = []

5. See error
Script queue_handler(#8) of type 'ActionQueueHandler': a_repeat() error 'disk I/O error'.

#### Expected behavior
It should keep going without that error.

#### Environment, Evennia version, OS etc
I have a fresh hard drive and I'm using WSL2.
    Evennia 0.9.5 (rev 5f361fbd5) (rev 5f361fbd5)
    OS: posix
    Python: 3.7.5
    Twisted: 19.10.0
    Django: 2.2.12

#### Additional context
I think this might just be a "me" problem or a problem unique to WSL2. But Griatch asked me to open this. Thanks, Griatch!

**Comment by davewiththenicehat** [comment] 2021-09-09 20:10
Do you happen to have a full traceback to post?

I am confident it is just a typo on the post but on "5. See Error" it shows `a_repeat()` rather than `at_repeat`.

It could be WSL2. If you wanted to test that, just write something, anything that reads and writes to the db a few thousand times. If the issue is hardware or OS (or emulation platform in this case) related you should see the error there as well as within your custom command queue.
For example just make a unit test somewhere with a big loop in it and call just that one unit test.

**Comment by jumpscarejumpscare** [comment] 2021-09-09 20:14
Since it's within a script, there is no full traceback. And yes, that was a typo from when I typed up the error.

Here's a traceback I got from some other time I got a disk I/O error while doing EVENNIA RELOAD

Traceback (most recent call last):
  File "/home/muddev/evenv/bin/evennia", line 7, in <module>
    exec(compile(f.read(), file, 'exec'))
  File "/home/muddev/evennia/bin/unix/evennia", line 10, in <module>
    main()
  File "/home/muddev/evennia/evennia/server/evennia_launcher.py", line 2209, in main
    init_game_directory(CURRENT_DIR, check_db=True)
  File "/home/muddev/evennia/evennia/server/evennia_launcher.py", line 1746, in init_game_directory
    check_database()
  File "/home/muddev/evennia/evennia/server/evennia_launcher.py", line 1449, in check_database
    evennia._init()
  File "/home/muddev/evennia/evennia/init.py", line 397, in _init
    GLOBAL_SCRIPTS.start()
  File "/home/muddev/evennia/evennia/utils/containers.py", line 182, in start
    self._load_script(key)
  File "/home/muddev/evennia/evennia/utils/containers.py", line 163, in _load_script
    found.restart(interval=interval, start_delay=start_delay, repeats=repeats)
  File "/home/muddev/evennia/evennia/scripts/scripts.py", line 589, in restart
    del self.db._manual_pause
File "/home/muddev/evennia/evennia/typeclasses/models.py", line 186, in delattr
    _GA(self, _GA(self, "name")).remove(attrname)
  File "/home/muddev/evennia/evennia/typeclasses/attributes.py", line 723, in remove
    attr_obj.delete()
  File "/home/muddev/evennia/evennia/utils/idmapper/models.py", line 415, in delete
    super().delete(*args, **kwargs)
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/models/deletion.py", line 318, in delete
    sender=model, instance=obj, using=self.using
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/transaction.py", line 240, in exit
    connection.commit()
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/utils.py", line 89, in exit
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/muddev/evenv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: disk I/O error

**Comment by davewiththenicehat** [comment] 2021-09-09 20:21
Have you tried removing and recreating the db? This of course only works if this is a best environment. I'm guessing it is since you are running from a Linux emulator.
That is my best guess without researching the messages in the traceback.

**Comment by strikaco** [comment] 2021-09-09 22:20
> Lastly is this, where you put whatever you want to resolve the queued action. Put a ton of DB accesses and writes in here, for example.

I think your problem is here. I don't use WSL, but from the last time I tried doing batch operations ("tons of DB accesses and writes") within script hooks, I encountered different I/O errors-- database locked.

What worked for me was not running through the entire queue at once-- pop 10 (or 100 or whatever) items, execute them, then do more on the next repeat ~1-2s later. 

The trick throughout this framework is that you can't do long-running blocking operations that access the database (if you're using SQLite). If you need things to work the way you have them, change to a backend that supports concurrent access. (Heading this off-- running these as async calls won't work either unless you change backends to one that supports concurrency.)

Some other unsolicited thoughts:
* Your script itself seems overcomplicated. Unless you really, really need it to go dormant when nothing is going on, it's probably a lot cheaper to just poll the queue every few seconds even if it's empty.
* Do you actually need pending actions stored to disk-- persistently? You might be able to avoid your current problem altogether by mounting queues as `self.caller.ndb.action_queue = []` (notice ndb instead of db); they will be stored in memory instead of serialized to disk (where you are already experiencing a bottleneck).
* Also, don't use lists as queues if you can avoid it-- use `collections.deque`. They're serializable, play nice with Evennia and are designed for push/pop operations-- there's no reason not to.

**Comment by davewiththenicehat** [comment] 2021-09-10 14:56
My unit tests read/write to the database a rather large amount. I use a lot of custom datatypes (I'm a big fan of handles and descriptors). Rough guess is around 10k read & writes over 500 or so unit tests. If I recall they take about 400 seconds with an Intel processor something like 700 with an AMD.
At any rate, I do not have disk errors. In my unit tests.

strikaco, just to make certain we understand the suggestion. You are suggesting migrating from sqllite to something like postgres or mariadb?
I am fairly certain the only thing in evennia that is threaded are the web interface. Everything else is in a main that gets looped.
The only time you need to worry about concurrent calls is when you are writing something that interacts with the web folder. Think, making a character creation tool that is on the website. Unrelated to evennia, but normally I switch to postgres when I know their will be large volumes. I had though sqllite could handle threaded calls. Honestly that was an assumption though.

**Comment by strikaco** [comment] 2021-09-10 16:47
> You are suggesting migrating from sqllite to something like postgres or mariadb?

Not as a drop-in solution, no. I'm advocating rewriting this in a way that doesn't fire off an arbitrarily-lengthy blocking call in the main thread.

I think you are right though-- for switching backends to do anything, this would have to make use of async as well.

**Comment by Griatch** [comment] 2021-11-04 08:28
Not sure what we could do from the Evennia side about this ... the system can't connect to the database and that's why this error shows up. It's out of the scope of Evennia itself. 

We could in principle try to catch an error like this and retry, but not sure this is an error one would want to hide. My first guess would be that your hard drive is getting wonky.

**Comment by mrseeker** [comment] 2021-11-04 08:40
Another thought that could cause the I/O errors: what virusscanner are you using? Some virusscanners will request an exclusive lock files after a write, which causes the application to lock. Putting the file/directory in a whitelist can usually resolve this error.

**Comment by Griatch** [comment] 2022-02-12 17:51
Closing this; it's not related to Evennia itself but is likely a problem with the system or hardware.

**Closed by Griatch** 2022-02-12 17:51 UTC
Labels: bug
