### ISSUE TITLE
@reload sometimes stops, but fails to restart the server

### ISSUE THREAD

**Issue by j3b4** [evennia/evennia#899] opened 2015-12-10 00:54 UTC
I've been hesitating to post this since I am not having luck reproducing it reliably, however it occurs on its own two or three times a day when I'm working on my server.  Sometimes @reload works as expected.  At other times it provides the "Server shutting down message" then simply shows scrolling ellipses indefinitely.  At those times the only thing that shows up in the server log is this:

```
2015-12-10 00:17:33+0000 [AMPProtocol,0,127.0.0.1] [..] Logged in: Horatio(player 1) ('192.168.1.6', 51298) (1 session(s) total)
2015-12-10 00:28:00+0000 [-] (TCP Port 5001 Closed)
2015-12-10 00:28:00+0000 [-] Stopping factory <twisted.web.server.Site instance at 0xb6050d2c>
2015-12-10 00:28:00+0000 [-] (TCP Port 5000 Closed)
2015-12-10 00:28:00+0000 [-] Stopping factory <evennia.server.amp.AmpServerFactory instance at 0xb60f7b0c>
2015-12-10 00:28:00+0000 [AMPProtocol,0,127.0.0.1] AMPProtocol connection lost (HOST:IPv4Address(TCP, '127.0.0.1', 5000) PEER:IPv4Address(TCP, '127.0.0.1', 48046))
2015-12-10 00:28:00+0000 [-] Main loop terminated.
2015-12-10 00:28:00+0000 [-] Server Shut Down.
```
From the command line, I can get the server started again with 
`evennia start server -l` as usual.

```
Starting Evennia Server (output to server logfile).
--------------------------------------------------
 Portage Server (0.5.0 (rev 5d3df58)) started.
  amp (to Portal): 5000
  webserver: 5001
--------------------------------------------------
```

I've tried at @reload at different lengths of time after restarting and after idling for different lengths of time so far I haven't found any pattern.

I'd be happy to accept some advice about other tests or steps I can take to make this report more useful.

**Comment by Griatch** [comment] 2015-12-10 08:15
As you note, it's indeed hard to tell what could be wrong without clear instructions on how to reproduce. 

A failed reload usually only happens if you have a critical syntax error in your code (so that Evennia can't even get the module since it's not a valid Python source, which means the Server can't (re)start). This will show as a traceback in your log though, which you don't appear to see. Have you checked `mygame/server/logs/portal.log` to see if that has anything? 

You also say you use `evennia start server -l` as a start command; just to avoid silly mistakes, make sure you are looking at the right log file (`mygame/server/logs/server.log` by default). Try running without the `-l` argument (so errors are shown in the terminal), just to make sure there is nothing fishy with Evennia's logging mechanism rerouting your errors (there have been some changes to error reporting lately).

**Comment by Griatch** [comment] 2016-01-20 17:38
Since I haven't seen any more on this I assume this was due to a coding error. Closing. Reopen if you find a condition where it can be reliably reproduced.

**Closed by Griatch** 2016-01-20 17:38 UTC
