### ISSUE TITLE
Possible website hang when http log reaches 1mb size

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#983] opened 2016-05-30 00:57 UTC
I hesitate to post this since I'm running the older version, and I'm unsure if this has already been fixed with a newer version of twisted or your rewrite of so much of the server/portal, but I was having website hangs due to twisted logger's attempt to write to a closed file when it hit the 1mb size limit of the http file when switching over (presumably callbacks trying to do log writes after it was closed). I think I fixed it myself by making a Site class that the server/portal use and having its log method check for an exception, but have no idea if this is an error that would occur in the current version of Evennia. I figured I should probably mention it just in case.

**Comment by Griatch** [comment] 2016-05-31 11:15
@TehomCD 

No changes have been done to the logging system in a long time. Some questions for clarification:

 - How does this limit manifest? If you have DEBUG=True, do you see any errors? 
 - How did you figure out this was the particular reason for the error?
 - What file are you referring to - portal.log, html.log ... ? 
 - How do you reproduce it -  by filling a log file with data up to 999Kb and then wait ...?

**Comment by TehomCD** [comment] 2016-05-31 18:32
I had noticed the website hung a few times after heavy activity, and after shutting down and restarting to fix it, I saw that it had happened each time when the http_requests.log file had become full. Originally I didn't notice any visible traceback, but I did get one after I added a Site class that both server/portal use and overrode the log method to prune out webclient POST requests in the http log. I was then able to find a traceback the next time it happened:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 405, in startReactor
    self.config, oldstdout, oldstderr, self.profiler, reactor)
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 326, in runReactorWithLogging
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "C:\Python27\lib\site-packages\twisted\web\wsgi.py", line 338, in wsgiFinish
    self.request.finish()
  File "C:\Python27\lib\site-packages\twisted\web\server.py", line 228, in finish
    return http.Request.finish(self)
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 942, in finish
    self.channel.factory.log(self)
  File "C:\ArxMUSH\src\server\webserver.py", line 149, in log
    return Site.log(self, request)
  File "C:\Python27\lib\site-packages\twisted\web\http.py", line 2089, in log
    logFile.write(line)
  File "C:\Python27\lib\site-packages\twisted\python\threadable.py", line 53, in sync
    return function(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\twisted\python\logfile.py", line 188, in write
    BaseLogFile.write(self, data)
  File "C:\Python27\lib\site-packages\twisted\python\logfile.py", line 97, in write
    self.flush()
  File "C:\Python27\lib\site-packages\twisted\python\logfile.py", line 105, in flush
    self._file.flush()
exceptions.ValueError: I/O operation on closed file

At the time I got the error, my Site class only pruned out the post requests from the old AJAX webclient:

class WebSite(Site):
    """
    More or less a copy of server.Site but with different logging.
    """
    def log(self, request):
        try:
            # remove webclient POST requests
            if "/webclientdata" in request.uri:
                return
        except Exception:
            pass
        return Site.log(self, request)

It doesn't seem to occur exactly at 1mb as you might expect, but a bit before - the last time it froze was when the log was at 975kb, I believe, with the last few log messages just being incomplete fragments for some reason.

I just did a test run with help from WhiteNoise for filling up my log, and didn't encounter the error now that I've wrapped Site.log in a try/except block:

class WebSite(Site):
    """
    More or less a copy of server.Site but with different logging.
    """
    def log(self, request):
        try:
            # remove webclient POST requests
            if "/webclientdata" in request.uri:
                return
        except Exception:
            pass
        try:
            val = Site.log(self, request)
        except Exception:
            return
        return val

**Comment by Griatch** [comment] 2016-06-03 09:04
After discussions in IRC, this might be due to some sort of twisted log file rotation maybe? 

At any rate, it might be an idea to ditch the http.log output overall; maybe we should istead just set it up to be used only when settings.DEBUG is `True`.

**Comment by Griatch** [comment] 2016-06-15 21:10
@TehomCD 

The HTTPlog has now been disabled in latest Evennia unless `settings.DEBUG` is set. If you want to retro-add this to your version of Evennia you can peek at the linked commit above. Closing this now.

**Closed by Griatch** 2016-06-15 21:10 UTC
Labels: bug, more info needed
