### ISSUE TITLE
Trying to create an account using the webpresence does so even if the password is not accepted.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1857] opened 2019-06-30 10:26 UTC
Trying to create an account using the webpresence does so even if the password is not accepted due to being "too similar to the username".

I've tried creating a test account using the web presance with a silly password and it would not allow me to do it. Afterwards tried doing it from the client itself and noticed that account name was already used.
Looking at the admin panel on the webpresence I can see the account listed with a hash for the password so it saved *something*, just not sure exactly what.

**Comment by Griatch** [comment] 2019-07-01 06:13
@BP-Santo I cannot reproduce this. I tried variations of the following: 

1. Logged out of the website
2. Tried to register with `Foobarens` and password `foobarens`, `foobarens1` etc
3. Got blocked for "Too similar to the username"
4. Checked in Admin and from `evennia shell` with `from AccountDB;AccountDB.objects.all()` and see no extra accounts. I can also go to the client and create `Foobarens` (with a reasonable password) with no issue. 

Can you reproduce this reliably? Could you list exactly what combination of name and password or other thing you did to manage to create your account despite getting the password error?

**Comment by BP-Santo** [comment] 2019-07-01 06:47
I'll try and reproduce later today. I tried adding the same account with different passwords so possibly it actually accepted one of them as safe but din't reload the page?

**Comment by Griatch** [comment] 2019-08-28 21:33
@BP-Santo I still cannot reproduce this. Have you found a way to reproduce or should this be closed?

**Comment by BP-Santo** [comment] 2019-08-28 22:33
While testing I noticed something else that is a bit odd:
It for some reason allowed me (from the web presence) to create an acount with login: `test` pass: `test4455`
At the same time it did not allow me to create: login `foobarfoobar` with pass `foobarfoobar1` nor `foobarfoobar4455`

I then tried different combinations and it seems, if the login name is 4 characters it will allow that kind of password. If the login is 5 characters however the behaviour seems to be the same as a longer login. I din't attempt to script a proper test - just did a few quick checks.

I could no longer reproduce the previous issue however :)

**Comment by strikaco** [comment] 2019-08-29 18:04
> I then tried different combinations and it seems, if the login name is 4 characters it will allow that kind of password. If the login is 5 characters however the behaviour seems to be the same as a longer login.

By default the Django password similarity validator requires two strings to be 70% similar to warrant rejection. `test` and `test4455` are only 50% similar so it passes.

https://docs.djangoproject.com/en/2.2/topics/auth/passwords/#included-validators

You can tweak the threshold by redefining the validator in settings.py:
```
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': 0.9}},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
```

**Comment by Griatch** [comment] 2019-08-29 20:10
@strikaco That'd be the explanation then. Thanks! Closing this.

**Closed by Griatch** 2019-08-29 20:10 UTC
Labels: bug, master-branch, more info needed
