### ISSUE TITLE
ANSI Colors Bugs: Crazy behaviours!

### ISSUE THREAD

**Issue by tajmone** [evennia/evennia#726] opened 2015-03-23 12:08 UTC
Try this from within Evennia:
```
say AAA{*BBB{*CCC
```
You'l notice that `{*` inverts BG/FG only once. Tried it in many other combinations also. It seems to exhaust some "state memory" after first operation.
But, if you insert any ANSI marker between the two `{*`:
```
say AAA{*BBB{g{*CCC
```
It works again.
But then if you try:
```
say AAA{*BBB{[gCCC
```
instead of changing CCC bg color it changes the FG color! As if after inverting BG/FG it has actually swapped reference to them!

And of cours, trying:
```
say AAA{*BBB{[gCCC{*DDD
```
results the last `{*` not having any effect (or maybe it is working with swapped references behind the scene)

But even more interesting is this:
```
say AAA{*BBB{gCCC
```
where the last  `{g` changes the BG color instead of FG (so, yes they are inverted in reference!)

But, amazingly, if you try this (with NORMAL FG instead of BRIGHT):
 ```
say AAA{*BBB{GCCC
```
it works (but resets the BG color to default!)

Wooow, some add behaviours going on here!

**Comment by tajmone** [comment] 2015-03-23 12:30
POST SCRIPTUM: Once this bug is fixed, there still will be to decide how swapping BG/FG will handle "normalization" of colors for BGs. That is: since background has only normal (dark) colors, when swapping any FG bright color it will be converted to dark in the BG.

When swapping a second time, should the FG revert to its original bright color, or should it now inherit the (converted to) dark color of the BG?

I guess swapping BG/FG is something one would mailny to to highlight parts of the text, so it might be better if the swapped BG is "virtually" dark and preserves a reference to the orignal color (which might have been brigth) and in a further swap restore the true original color, not the virtual one.

It seems to me that all this would handled in a much simpler way if BG colors would accept both bright and dark colors (using same case as foreground) even though they will only display the dark version of them. But at least they would store a colour in 16 colors references. This would allow double swaps to restore the initial state when highlighting.

But then, it all boils down to what the old terminal standards were, I guess.

Truely, in the modern age we live in, nothing should prevent us to implement 16 colors also for background after all.

**Comment by Griatch** [comment] 2015-03-24 14:36
This is not a bug, but the way the ANSI reverse video tag works. Complain to the Telnet ANSI standard people. ;) There is anyway nothing we can do to change this since each tag is a stand-alone state - there is no concept of storing state across tags or to "know" what it affects as far as Evennia goes. The reverse video is only intended for marking small text snippets anyway I think, beyond that it requires experimentation, especially since the implementation also varies on the client terminal side. 

So I'm closing this, it's not going to be changed.

**Closed by Griatch** 2015-03-24 14:36 UTC
