### ISSUE TITLE
[BUG] Help Files Do Not Display New Line Characters With Escape

### ISSUE THREAD

**Issue by jaborsh** [evennia/evennia#2598] opened 2021-11-27 07:25 UTC
Help entries no longer validate `||/` to display `|/`. Instead, it continues onward to display a new line.

#### To Reproduce
1. Create help entry
2. Put `||/` somewhere in help entry
3. See error

#### Expected behavior
In master branch, help entries automatically escape the new line generation to display. Helpful information for builders.

**Comment by Griatch** [comment] 2022-09-22 18:22
I cannot reproduce this; this seems to be working fine using `sethelp` command in current `develop` branch. Closing, if this is still happening using some other process, reply here and we can re-open.

**Closed by Griatch** 2022-09-22 18:22 UTC
Labels: bug, branch-develop
