### ISSUE TITLE
tags.get returns tag after removal until tags.all() is called

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1142] opened 2016-12-16 05:16 UTC
#### Brief summary of issue / Description of requested feature:
When using tags earlier for a player setting, I noticed that it was remaining 'on' even after the tag was removed from a player unless `player.tags.all()` was called to update the cache. This happened when finding the player who was tagged with player.search() from another command. I noticed that using `@py self.player.tags.add` and .remove would have get work fine, but matching them from the command would have the tags reference be stale for some reason unless .all() was called.

#### Steps to reproduce the issue / Reasons for adding feature:

1. add tag to a player
2. remove tag from player
3. check for tags.get again

Edit: After a `@reload`, I can no longer duplicate this. So I'm guessing it was some strange caching thing? Very strange.

#### Error output / Expected result of feature
The tag is returned despite removal, unless tags.all() is called.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
After a reload, I stopped being able to duplicate this. I'm not sure why it happened suddenly, and then stopped occurring. Possibly a stale foreignkey issue with `self.player`?

**Comment by BlauFeuer** [comment] 2016-12-16 07:22
A similar caching issue occurs when changing a CMD lock on an exit - the default building commands being under test for these conditions will eventually catch these kinds of issues.

**Comment by Griatch** [comment] 2016-12-16 23:33
@TehomCD 
I also cannot reproduce this. I tested 

```
@py self.player.tags.add("testlock")
@py self.player.tags.get()
<<< testlock
@py self.player.tags.remove("testlock")
@py self.player.tags.get()
<<< None
```
Leaving this open for now in case it can be reproduced. 

@blau that is completely unrelated and is not a caching issue but the fact that what runs your exit is a Command sitting on said exit. When it is recached it loads the locks from the exit-object. The problem is that if you store a new lock on the exit the Command sitting on said exit does not know it should update as well.

**Comment by Griatch** [comment] 2016-12-17 15:21
@BlauFeuer:  Update: I cannot replicate the exit lock-issue you mention either. I know it has been a problem in the past, but I tried the following successfully from in-game: 

```
@quell 
@tunnel north = kitchen
@lock north
>>> ... traverse:all() ...
@lock north = traverse:false()
@lock north
>>> ... traverse:false()
north
>>> You cannot go there. 
@py self.search("north").locks.add("traverse:all()")
north
>>> kitchen (#12) ...
```

One do have to handle the ExitCommand and its object specially, but for the default operations this seems to work fine. Do you have a particular example when this the exit object's lockstring and the lockstring on its -command gets out of sync?

**Comment by Griatch** [comment] 2016-12-17 15:24
@BlauFeuer Actually I realize you are talking about a "cmd"-type lock. The cmd lock is a little special since exits are not actually exits without it.

**Comment by Griatch** [comment] 2016-12-17 15:29
To update the "cmd" type lock (which changes the way the Command itself is accessed on the Exit object, the Exit object must currently be manually updated. For example like this: 

```
@lock north = cmd:false()
@py self.search("north").at_init()
north
<<< Command 'north' is not available.
```

I'm not sure just how much effort it would be to make that particular lock type auto-update. I suspect it may require a rewrite of the lockhandler for the Exit object specifically.

**Comment by BlauFeuer** [comment] 2016-12-29 21:53
I was thinking about just updating `@lock` to at_init() on updates to the cmd lock, but maybe that's a poor temporary solution.

My association of the two different issues here (I honestly didn't mean to hijack the issue with another issue) was more to point out that tests for staleness could uncover similar situations.  We're finding them one by one and it involves a bit of head-scratching and a `@reload` to see if that fixes it.

**Comment by Griatch** [comment] 2017-01-11 20:54
@BlauFeuer I think we might have done something similar in `@lock` in the past, but it was removed since it's not needed for *most* lock updates - only the `cmd:` type lock is still an issue. We can't have `@lock` call `at_init` on everthing either though. So I added a conditional check to `@lock` to have it re-run `at_init` on children of DefaultExits only; resolving that particular issue. 

@TehomCD: I still cannot reproduce this issue no matter how I try. So I'm closing this now. Re-open if it can be reproduced or reoccur.

**Closed by Griatch** 2017-01-11 20:54 UTC
Labels: bug
