### ISSUE TITLE
Bug: runtime error in tutorial when admin uses an exit admin is carrying

### ISSUE THREAD

**Issue by dwesely** [evennia/evennia#1018] opened 2016-08-18 02:28 UTC
#### Brief summary of issue / Description of requested feature:
Admin did something stupid. I set up a default installation and logged in as admin/Player1. In the tutorial, I made it to the Dark cell (27), and saw the root-covered wall was an object. So I picked it up, then promptly forgot I was holding it and tried to enter it.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Go to room 27, Dark cell
2.  Enter commands:
```
@unquell
get wall
wall
```
3. Receive error message

#### Error output / Expected result of feature
In the web client:
`Couldn't perform move ('location change'). Contact an admin. (Error: admin.location = admin creates a location loop.)`

In the command line window:
```
2016-08-17T21:39:51-0400 [AMPProtocol,0,127.0.0.1] [..] Logged in: admin(player1) 127.0.0.1 (1 session(s) total)
2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::] Traceback (most recent call last):
2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::]   File "<snip>\evennia-master\evennia\objects\objects.py", line 656, in move_to

2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::]     self.location = destination
2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::]   File "<snip>\evennia-master\evennia-master\evennia\objects\models.py", line 275, in __location_set
2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::]     raise RuntimeError(errmsg)
2016-08-17T22:08:36-0400 [AMPProtocol,0,127.0.0.1] [::] RuntimeError: Error: admin.location = admin creates a location loop.

```
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Running on windows 7 command line
Python 2.7.10
Downloaded Evennia source on 8/4/2016 from the master branch on github

**Comment by Griatch** [comment] 2016-08-18 13:39
This is specific to the Wall exit-type only; it does not happen when carrying any other exit. Exactly what goes wrong is unclear in this particular case. 

This appears at such a special situation (superuser, using an exit in your own inventory) and can't affect normal Players. It also concerns a tutorial-world object meant as an example. Keeping this open for now, but I must say this might not be worth spending much effort on fixing it unless the fix is trivial.

**Comment by Griatch** [comment] 2016-08-19 18:27
So, looked into the more specific cause for this. 

This is not a bug but comes from the Wall working a little specially. The wall won't work as an Exit until the button on it has been pressed, which means that the `wall.open_wall()` method must called (by the button). At his point the target destination is set and the locks allow for the player to pass. When you traverse the wall as superuser (you don't need to pick it up), the wall is in its default destination mode given to it at creation. This happens to be the location it was created in, namely in its creator (you).  This is normally not be an issue - normal users would be forbidden to ever traverse the lock until the wall is open and the correct destination has been set. But as superuser you bypass all locks. And since you can't enter yourself, you get this error. 

Fixed a minor related error when testing the wall, but this particular issue is not something to fix. Closing this now.

**Closed by Griatch** 2016-08-19 18:27 UTC
Labels: bug

**Comment by dwesely** [comment] 2016-08-21 00:57
Thank you for the clarification!
