### ISSUE TITLE
[BUG] object.copy() is not properly copying tags

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#1972] opened 2019-10-20 13:57 UTC
#### Describe the bug
Copying an object does not copy its tags.

#### To Reproduce
1. Create an object.
2. Add tags to said object.
3. Copy the object through any method.

#### Expected behavior
There seems to be a clear intent to make an exact copy of the object, including all attached tags.

#### Environment, Evennia version, OS etc
Evennia 0.9.0, rev 09f10db3

#### Additional context
The root of the problem appears to be in evennia/objects/manager.py, at line 593 at the time of this writing.

The line is currently:

`         for tag in original_object.tags.get(return_tagobj=True, return_list=True):`

Which returns only an empty list.

The following line should fix the issue:

`         for tag in original_object.tags.all(return_objs=True):`

**Comment by Griatch** [comment] 2019-10-24 18:46
@awranthyr I cannot reproduce this. I tested the following from in-game: 

1. `create/drop box`
2. `tag box = foo`
3. `py self.search('box').copy()`     (this creates `box000`)
4. `ex box000`
The copy now has the tags. 

Could you give a more specific process to reproduce the error?

**Comment by awranthyr** [comment] 2019-10-24 22:17
@Griatch Sorry about that, I should have done more testing before reporting the issue.

The bug doesn't apply to all tags, apparently, but only those with categories.  I just tested the following in a fresh install of Evennia, to make sure it wasn't just some of my own game's code causing it:

1. `create/drop thing1`
2. `tag thing1 = first_tag`
3. `tag thing1 = second_tag:new_category`
4. `py self.search('thing1').copy()`
5. `ex thing1000`

The copy does have the non-categorized tag, but not the one with a category.

**Comment by strikaco** [comment] 2020-01-12 21:02
@awranthyr A fix for this was implemented; are you still having this issue?

**Comment by Griatch** [comment] 2020-01-20 18:43
Since there are no further replies here and a fix was already made, I'm closing this issue.

**Closed by Griatch** 2020-01-20 18:43 UTC
Labels: branch-master, bug, more info needed
