### ISSUE TITLE
Feature Request: Collaborative Building Tools

### ISSUE THREAD

**Issue by Kelketek** [evennia/evennia#525] opened 2014-06-26 15:44 UTC
We have a large number of people coming over from MUCKs and MUSHes that are used to a more collaborative building environment, where user content is king. The current build commands and configuration aren't conducive for this sort of environment. As Evennia's intended purpose is more of a MUD development kit, it doesn't make sense to make collaborative building the default. However, a well constructed contrib could be made to easily transform Evennia into a collaborative worldbuilding toolkit.

A few things would be needed for this to work right. The first is going to be a concept of object ownership. The standard locks work well for determining if someone should have access to something, but leave something to be desired in terms of 'default powers' in relationship to the object's creator. If someone makes a room, they should be able to change the locks on it, etc, even if the current locks might otherwise say they're unable. It is also useful for keeping track of what objects were created by who. It also shouldn't be possible for a normal user to be able to create something that an immortal is barred from modifying.

This will also inevitably bring up the issues of 'softcode'. Full blown softcode, like MUSHcode, or MPI, is undesirable-- more complex logic should be in the Python code, and managed with merge requests and what have you. But even some basic logic could be added without too much difficulty if we used something like [Jinja](http://jinja.pocoo.org/) to provide for a templating language with conditionals and loops and variable access. This would, effectively, allow for creativity while making the path for more complex interaction clear-- edit the Python code. Jinja supports custom tags, which would allow teams to expand the functionality of the templating system as desired.

**Comment by tricuspa** [comment] 2016-02-17 07:10
Late to this topic, but let me bring introduce perhaps a simpler refinement.  Would version control be the better overall solution.  Along with the object in question having  some sort of attribute such as.

- Editable : Fully editable by anyone - automatically updated upon change (wiki)
- Reviewed: Object may be edited by anyone and owner is notified of suggested changes and confirms or ignores or perhaps the system even has "accept/decline changes automatically after xx hours/days etc"  (monitored discussion board)
- Owner Only: Only the owner may edit / revise this object. (ownership)

These seem to me the major methods used nowadays and help protect the data.

**Comment by Kelketek** [comment] 2016-02-17 16:05
@tricuspa I don't think version control would be simpler to implement. However it could certainly be implemented on top of this change. It's possible to set properties with different permissions levels, so one could make a system that does what you're suggesting. The lock system can certainly support checking whether an object would be 'wiki editable' by a target user or not. And if that lock fails, a secondary lock checking for 'reviewable changes' could also be done, and a revision could be created that just isn't set.

It's not a bad idea, and I could be wrong about the difficulty. If you want to try implementing it and see if it can be done in a smaller timespan than my improvement (I have been mostly absent on this lately but am planning to play with it a bit this weekend) by all means, go for it. Or you could work on an implementation that works atop this one when it's complete.

**Comment by BlauFeuer** [comment] 2016-02-17 16:13
Now that you mention it, considering the back end is a database, version control is exactly what you're asking for when you want collaborate editing — especially when you talk about not trusting anyone, and having fall back states.

**Comment by Kelketek** [comment] 2016-02-17 16:15
Hmm. You know, I'll look into this. You may be right that it's an easier change, and it DOES seem to fit the pattern of where things are going. The biggest question will be how to version control the chain of models involved in an Evennia object.

**Comment by Griatch** [comment] 2016-02-17 16:21
@kelketek, @tricuspa, @BlauFeuer:  Interesting, although I would be interested in seeing more about just what "version control" would entail in an Evennia context. Are we basically talking about each object storing a history of diffs of ... what? Attribute changes? Field diffs?

**Comment by BlauFeuer** [comment] 2016-02-17 16:21
Then to implement the moderated change, the most recent edit is held and locks editing until a moderator addresses it, or some period of time passes.  You would want rate limiting on public and community object editing, and a way for the owner to clear past and pending revisions.  The building tools just have to be aware of your revision system and which objects are flagged to use them on.

**Comment by Griatch** [comment] 2016-02-17 16:23
Btw: https://bitbucket.org/emacsway/django-versioning

**Comment by Kelketek** [comment] 2016-02-18 04:39
I've thought over this further and I don't think I want to do it for the initial implementation. The reason being that I've already gotten most of the infrastructure in place, I'm in no position to start over with what time I've been able to dedicate, and most of the functionality within collab that's currently implemented will have to be implemented in the new system anyway-- default permissions, the ability to specify who can edit an item/how public it is, etc.

It's going to be better at this point, from a practical standpoint, to add versioning on top of this if we want it.

**Comment by Griatch** [comment] 2016-05-25 12:04
@Kelketek 

Now that devel branch has merged and I can get back to overall server work, is there anything in collab that could be helped by some changes on the core side of things?

**Comment by Kelketek** [comment] 2016-05-25 12:57
@Griatch Hard to say. I've not had much chance to come up for air since my business started-- it's going to get busier before it gets more relaxed.

**Comment by Griatch** [comment] 2016-10-20 13:04
The PR for this is closed for now due to lack of updates, but this feature request remains for reference to the discussion.

**Comment by Griatch** [comment] 2018-02-14 20:43
Noting that the [PR](https://github.com/evennia/evennia/pull/1333) for this is open again (since some time) since others have expressed interest in helping @Kelketek to finish this long-coming feature.

**Comment by Kelketek** [comment] 2018-02-14 20:45
@chainsol How have things been going on this? Have you had much chance to work on it?

**Comment by chainsol** [comment] 2018-02-14 21:02
I'm sorry, no, I haven't! I've been working locally on my webclient changes, and then I'll be focusing on this. :D

**Comment by BlauFeuer** [comment] 2018-02-14 22:42
I'm still somewhat at a lost as to why the concept of ownership is important in collaborative building.  It seems like ownership is exactly the opposite of communal building which would just use locks for control and edit, and does not care who "owns" it.

If the crux of the issue is that the person making the room (or object) has no control or edit permission after creation, then that's a fault of the building tool default lock, not a paradigm problem.  The creator can set locks with the `@spawn` command to properly allow said creator and possibly others to control and edit, or if (as in the example) Alice was _not_  the creator, but can edit (because Bob correctly controls the object without Alice, but allows Alice (and potentially many others by naming them singly or as a group) to edit it (but not change the locks).   All Alice can do is get fussy and make a bunch of undesirable edits.

As for listing all objects that a person "owns" by virtue of having created it (or even just list what a person controls, for that matter), that is some sort of search on locks or tags (depending how you want to label ownership).  Once you establish some sort of ownership tagging, then of course you want a sane `@chown` command that won't change ownership without passing the control lock, and will know to remove control from the old owner and give control to the new one. 

But overall, the concept of ownership just gives an abstraction that is further from the reality that it's who controls the object who decides who else can edit it.  And in adding this abstraction, does not solve the issue of Alice's undesirable edits - it's not version control in any way.

Lastly, understand that I am giving an alternate viewpoint, not attacking the project.  I'm hoping to advocate for a simple paradigm that everyone (even those old TinyMU*-centric types) can properly operate.

**Comment by Griatch** [comment] 2019-03-31 19:46
@chainsol, @Kelketek: No activity on this for a year; this will require updates not only to Evennia 0.7, 0.8 and 0.9 but also a move to Python3 before it can merge. Closing this for inactivity again. If there is interest in picking this up and finally complete it, let me know.

**Closed by Griatch** 2019-03-31 19:46 UTC
Labels: develop-branch, feature-request
