### ISSUE TITLE
[BUG] Bad interpreter: Error finding evennia executable if spaces in folder name

### ISSUE THREAD

**Issue by Jaykingamez** [evennia/evennia#2602] opened 2021-12-12 13:58 UTC
#### Describe the bug
Following the Getting Started documentation, if one chooses to name their folder "Mud Development" or any other name with one spacing in it. An error will be outputted when typing in 

```
evennia --init mygame
```
One would receive the following error
```
-bash: /mnt/c/Users/jayki/documents/Mud Development/evenv/bin/evennia: "/mnt/c/Users/jayki/documents/Mud: bad interpreter: No such file or directory
```
As one can see, 
#### To Reproduce
Steps to reproduce the behavior (According to the quickstart [tutorial](https://www.evennia.com/docs/latest/Getting-Started.html)):
1. Install Python, GIT and python-virtualenv. Start a Console/Terminal.
2. cd to some place you want to do your development (like a folder /home/anna/mud dev/ on Linux or a folder in your personal user directory on Windows).
Note: As long as the named folder's name have spaces in it, when one reaches step 7 evennia --init mygame
3. See error

#### Expected behavior
evennia command should be able to be executed without errors

#### Environment, Evennia version, OS etc
```
Evennia 0.9.5 (rev aa6d01e01) (rev aa6d01e01)
    OS: posix
    Python: 3.8.10
    Twisted: 21.7.0
    Django: 3.2.10
```

#### Additional context
(Replace with any other context about the problem, or ideas on how to solve.)

**Comment by The-Archemist** [comment] 2021-12-12 17:49
It sounds like you didn't follow the get started directions and skipped over the part where you first install Evennia.

**Comment by Griatch** [comment] 2022-09-22 18:29
I can't reproduce this in `develop` branch: I create a folder `mud development`, enter it and I can init a game dir just fine in there. Closing this.

**Closed by Griatch** 2022-09-22 18:29 UTC
Labels: bug
