### ISSUE TITLE
Inline funcs in object descs results in some characters being stripped from the desc

### ISSUE THREAD

**Issue by rnmissionrun** [evennia/evennia#1498] opened 2017-10-28 17:51 UTC
#### Steps to reproduce the issue / Reasons for adding feature:

1. To reproduce the error, simply set your object description to something like:
>> @desc here=$pad(whoa,10)!@#$%^&*()<>_+-=
2. 
3.

**Comment by rnmissionrun** [comment] 2017-10-28 17:54
[Screenshot](https://imgur.com/a/0l1k8)

**Comment by BlauFeuer** [comment] 2017-10-28 21:53
I think this is a partial duplicate of #989, which was closed. Below is how I reproduced the issue back then:
`pose $clr(|g,finds that these are the missing characters: \\?><|+@$+)\?><|+@$+`

**Comment by Griatch** [comment] 2018-06-16 23:29
This is fixed as part of vastly improving the regex parsing for inlinefuncs. Backporting from development.

**Closed** 2018-06-16 23:28 UTC
Labels: bug, good first issue, master-branch
