### ISSUE TITLE
[BUG] Quirk in saving webclient layout

### ISSUE THREAD

**Issue by Griatch** [evennia/evennia#2247] opened 2020-11-01 13:52 UTC
#### Describe the bug

It's visibly possible to circumvent the block against saving the `default` webclient layout. It doesn't actually work, but it's confusing.

#### To Reproduce
In webclient, open options: 

1.  Start to edit the `default` layout name by adding more letters to its name, like `default1234232`
2.  The `Close Options and Save` button becomes active
3.  Without saving, erase the extra letters, down to `default`
4.  The `Close Options and Save` buttons _remains_ active and you can now save your modified layout as 'default'

The save does not _actually_ happen (so this is correct), as loading default returns the 'real' default layout.

#### Expected behavior

The `default` button should remain greyed out whenever it's about to save something named `default`. While the above behavior is apparently benign in the sense that the `default` layout is not *actually* saved, it nevertheless confuses the user. 

#### Environment, Evennia version, OS etc
Evennia master branch.

**Comment by Griatch** [comment] 2022-10-23 08:02
Afaik this is still an issue.

**Comment by count-infinity** [comment] 2024-10-13 02:56
#3282  is merged and closes this issue I believe.  Currently unable to reproduce.

**Closed** 2024-10-23 18:25 UTC
Labels: bug, Hacktoberfest, help wanted, web
