### ISSUE TITLE
Commands to translate Evennia fail

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1735] opened 2018-11-01 19:51 UTC
#### Brief summary of issue / Description of requested feature:

The two commands given in the [documentation](https://github.com/evennia/evennia/wiki/Internationalization#translating-evennia) fail:

    evennia makemessages -l <language-code>
    evennia compilemessages

#### Steps to reproduce the issue / Reasons for adding feature:

1. With a fresh, unmodified Evennia from Git.
2. Cd into evennia, then the evennia sub-folder (where the `locale` directory is, says the [documentation](https://github.com/evennia/evennia/wiki/Internationalization#translating-evennia)).
3. Enter one of the given commands.

#### Error output / Expected result of feature

    ERROR: No Evennia settings file was found. Evennia looks for the
    file in your game directory as server/conf/settings.py.

    You must run this command from somewhere inside a valid game
    directory first created with

        evennia --init mygamename

    If you are in a game directory but is missing a settings.py file,
    it may be because you have git-cloned an existing game directory.
    The settings.py file is not cloned by git (it's in .gitignore)
    since it can contain sensitive and/or server-specific information.
    You can create a new, empty settings file with

        evennia --initsettings

    If cloning the settings file is not a problem you could manually
    copy over the old settings file or remove its entry in .gitignore

This makes some sense since I'm not in my game folder (again, following the documentation).  However, I fancy this is a trick of the launcher and might break other commands that are not meant to be run in the game directory, though obviously translating is the first one I can think off.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to 

* Evennia version : master.
* Operating System: Windows.

**Comment by Griatch** [comment] 2018-11-05 07:14
This is likely a regression due to the launcher changes in 0.8 leading to the game dir location being expected.

**Comment by strikaco** [comment] 2018-11-20 21:45
Maybe unrelated, but also pertains to the launcher-- many management commands also fail due to the way the launcher parses arguments. 
* Trying to dump data and specifying an indent level or handling of foreign keys does not correctly execute.
* With Django extensions installed, show_urls errors out.

**Comment by Griatch** [comment] 2019-03-13 08:35
This is resolved in development branch which improvements to how arguments are passed on to django from the launcher.

**Comment by Griatch** [comment] 2019-06-29 18:13
Closed with merger of develop branch.

**Closed by Griatch** 2019-06-29 18:13 UTC
Labels: bug, develop-branch, implemented
