### ISSUE TITLE
[Documentation] (Enter a brief description here)

### ISSUE THREAD

**Issue by Xinefus-Braska** [evennia/evennia#3060] opened 2023-01-03 01:20 UTC
#### Existing page
https://www.evennia.com/docs/latest/Howtos/Beginner-Tutorial/Part1/Beginner-Tutorial-More-on-Commands.html#more-advanced-parsing

#### Documentation issue
Typo in the `class CmdHit(Command)` example. 
#### Suggested change
Line 20 should read: `self.weapon = weapon[0].strip()`

**Comment by Griatch** [comment] 2023-01-06 20:23
Duplicate of #3049. Closed by commit referenced in that issue.

**Closed by Griatch** 2023-01-06 20:23 UTC
Labels: documentation
