### ISSUE TITLE
Contrib RP System Issues

### ISSUE THREAD

**Issue by Caliah** [evennia/evennia#1051] opened 2016-09-08 15:15 UTC
#### Brief summary of issue / Description of requested feature:
This refers to the evennia contrib rpsystem module

According to the file:  To use, simply import the typclasses you want from this module and use
them to create your objects, or set them to default.

The Look and Say commands do not function as expected, nor do the Entry/Exit messages.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Objects, Characters and Rooms all set to inherit from the rpsytem module (new objects created, or old ones forced to the new models)
2. The sdesc set, pose. recog commands all set the appropriate fields, and the room displays them.
3. The emote command works properly, and can recognize by sdesc and recog.
4.  The Look command will not target any part of the sdesc or recog strings, reporting it cannot find the character.
5. Say and Entry/Exit messages display the key name of the character, not the sdesc or recog string.

#### Error output / Expected result of feature
1. Look should be able to view by sdesc and recog.
2. Say and Entry/Exit should display sdesc or recog string rather than key name.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I've tried this on two separate installs, with the same outcomes. Both are Win10.
Evennia version is: 0.6.0 (rev 405983d)

**Comment by BlauFeuer** [comment] 2016-09-08 15:25
What "search" method is your look command using, by the way?  For this to work, it needs to use an object search on one of the RP System object instances, like `obj.search` where `obj` is hopefully the RP System character that's trying to look. 

My particular custom look does this:
```python
        obj = char.search(obj_string, quiet=True,
                          candidates=[here] + here.contents + char.contents)
```

**Comment by BlauFeuer** [comment] 2016-09-08 15:29
Hmm, the fact that `say` and the `announce_move_from` and `announce_move_to` messages are not giving the sdesc either could mean that the character objects are just not inheriting the RP System methods or that the `say` and announce isn't calling `get_display_name` to deliver the sdesc version of the name in their output.

**Comment by Caliah** [comment] 2016-09-08 15:43
My question on the forum  was whether or not I needed to modify the look command. I have not made any changes other than setting the objects to inherit from the classes in the file. 

griatch's answer implied that that  was sufficient, though I admit I was surprised no changes needed to be made elsewhere.

So no I have not changed the search method for the look command. Looking at oneself returns the sdesc, not the key name.

**Comment by BlauFeuer** [comment] 2016-09-08 16:24
I'm just brainstorming to list ways it could go wrong.

@Griatch is correct, you shouldn't have to modify the look command, and if you do customize the look command, it should still work, assuming using the overloaded search function. 

I can only say that it works in my game, but I have modified many different things - so I'll have to get back to you in a bit; I'm looking into it now, setting up an out of the box game then adding the RP contrib.

**Comment by BlauFeuer** [comment] 2016-09-08 17:21
I did a very bare minimal from out of the box and there are some issues specifically related to default commands like `look`, `say`, `pose`, and the `announce_move`... messages not utilizing `get_display_name`, but instead using `obj.name` or `obj.key`  - all things I customized in my own game.  Oddly, my test case showed `emote` not using sdesc at all (`#3` from your list of results), but I could not reproduce  your result `#4` -- the search using default `look` properly used sdesc/recog keys instead of name/alias keys for me.

Overall, some PR's against the default `say` and `pose` and `announce_move`... can fix some of the results you are reporting, but your issue with `look` is still a mystery to me.

**Comment by Griatch** [comment] 2016-09-08 19:54
I just ran this test and cannot reproduce the look errors you see. I tried both by using `@typeclass` on existing characters and by setting the defaults to inherit from the contrib typeclasses and starting with a completely fresh database and install. 

Both looking using any word of an sdesc as well as using emotes with sdescs etc works correctly as far as I can see. 

The ContribRPCharacter comes with a full set of custom commands. These are loaded in its own at_object_creation hook.  Apart from the new commands "sdesc", "recog"  and "mask", this includes special versions of "say", "look", "emote" and "pose". If you set yourself to this typeclass you will automatically be using the custom version of those commands. When examining yourself you should find the RPSystemCmdSet mixed with the CharacterCmdSet. 

I can confirm that move messages are not translated though. This is not really the fault of the contrib though but more a matter of the default move messages not using `get_display_name` but the `key` directly to send messages. It's a simple enough fix to do. 

The other errors in this issue I cannot reproduce however, so I will mark this as more info needed.

**Comment by Caliah** [comment] 2016-09-08 23:11
Apparently I had two bad copies of the rpsystem file, neither had self.add(CmdSay()) as part of the command set list. I've yet to scan through to see what else was corrupted. While it's odd that I somehow managed to get two bad copies on two different computers, git pull solves the issue.

With that everything seems to be working except Forget. I can Recognize people, but forget just repeats the syntax back at me. (Usage: recog <sdesc> as <alias> or forget <alias>)  I'm poking at that now.

**Comment by Caliah** [comment] 2016-09-08 23:31
ok, so after poking. If I recognize a character as Bill. Forget Bill just gives me the syntax line. forget Bill Bill, or forget bill again works as intended. I presume the line is not getting split correctly.

 # try to split by space instead
            try:
                self.sdesc, self.alias = [part.strip() for part in self.args.split(None, 1)]

**Comment by Griatch** [comment] 2016-09-09 06:28
@Caliah 

If git pull solved the issue it sounds like you were simply working off an old version of the repo. Good it was not a harder problem! I have fixed the issue with `forget` now, so will close this issue (you can still comment in it as needed). Thanks for the feedback!

**Closed by Griatch** 2016-09-09 06:28 UTC
Labels: more info needed
