### ISSUE TITLE
installation problem with Pillow - linux&-windows

### ISSUE THREAD

**Issue by jaggiJ** [evennia/evennia#1736] opened 2018-11-03 14:07 UTC
There are errors with pillow, during installation of develop or master version of Evennia.
I use remote connection to my Rasbian on Raspberry Pie3b+ through ssh putty if that matters.

### steps to reproduce
1. clone evennia, git checkout -b develop, git pull origin develop
2. cd.. | . ./py2env/bin/activate | cd..
3. pip install -e evennia
OR 
install evennia according to getting started for linux guide

### Error output
``` python3  
  Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ADarXS/pillow/setup.py", line 807, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
```
## detailed error output for evennia/master:
https://paste.ofcode.org/QRnpe2SSEeEhbKYWGnq2mC
also after that **pip list** output:
https://paste.ofcode.org/9rAVMTigk5X5Bb7D4jF3wJ

### version
Evennia revision/repo/branch, operating system
Rasbian, evennia develop&master branches

**Comment by jaggiJ** [comment] 2018-11-05 15:08
**Solved:** 

indeed, Raspbian doesn't have a precompiled Pillow binary and dependencies are missing.

### To install all dependencies for pillow in rasbian (debian stretch) :
sudo apt-get update
sudo apt-get install libjpeg62 -y
sudo apt-get install libjpeg62-dev -y
sudo apt-get install zlib1g-dev -y
sudo apt-get install libfreetype6-dev -y
sudo apt-get install liblcms1-dev -y
sudo apt-get install libopenjp2-7 -y
sudo apt-get install libtiff5 -y

**Source** : [https://www.techcoil.com/blog/how-to-setup-python-imaging-library-pillow-on-raspbian-stretch-lite-for-processing-images-on-your-raspberry-pi/](url)

**Comment by jaggiJ** [comment] 2018-11-05 16:08
No idea I installed about half of them (the rest were already present) and then tried pillow. One can go from libjpeg62 OR libjpeg62-turbo if he chooses so , and down the list until pillow works.

**Comment by jaggiJ** [comment] 2018-11-09 14:00
To build pillow==5.2.0 in newest standard rasbian image that is debian9 stretch you need:
libjpeg62-turbo-dev 
OR 
libjpeg62-dev
Your choice.

zlib1g-dev is already present

source:
1. I installed fresh rasbian image, updated it and failed evennia installation because of lacking
dependencies to build pillow.
2. I installed libjpeg62 , but not enough,
[screen from installing that package shows how much things it changes (for some may be undesirable?)](https://paste.ofcode.org/6XWXyCwBrFxETE8uGkRpZN)
3. I installed libjpeg62-dev  and then pillow build went fine
4. I removed libjpeg62-dev & libjpeg62 & pillow and build pillow again with success (because it was build from cached source), so I uninstalled pillow to test again
5. pip install --no-cache-dir pillow==5.2.0 and it ... failed as expected since I removed crucial libs
6. sudo apt-get install libjpeg62-turbo-dev
   pip install --no-cache-dir pillow==5.2.0 and it worked ! then pip install -e evennia and it worked
![temp](https://user-images.githubusercontent.com/18056024/48266601-25e30c00-e430-11e8-8024-768e3add4e16.png)

**Comment by jaggiJ** [comment] 2018-11-09 14:16
I run into next issue trying to start evennia.
```
Superuser created successfully.
Portal starting ...
Traceback (most recent call last):
  File "/home/mud/muddev/evenv/bin/twistd", line 7, in <module>
    from twisted.scripts.twistd import run
  File "/home/mud/muddev/evenv/local/lib/python2.7/site-packages/twisted/scripts                                                                                        /twistd.py", line 13, in <module>
    from twisted.application import app
  File "/home/mud/muddev/evenv/local/lib/python2.7/site-packages/twisted/applica                                                                                        tion/app.py", line 17, in <module>
    from twisted import copyright, plugin, logger
  File "/home/mud/muddev/evenv/local/lib/python2.7/site-packages/twisted/plugin.                                                                                        py", line 18, in <module>
    from zope.interface import Interface, providedBy
ImportError: No module named zope.interface
Connection to Evennia timed out. Try again.
```


detailed screen:
https://paste.ofcode.org/Eqfk3cwzVZBDMupnmLE5jM

**Comment by jaggiJ** [comment] 2018-11-22 14:06
issue solved and solution added to [wiki/requirement/Pillow](https://github.com/evennia/evennia/wiki/Getting-Started#requirements):  
- Rasbian-Linux users also need to install 'libjpeg62-turbo-dev' as missing dependency to build Pillow.

**Comment by CloudKeeper1** [comment] 2018-11-27 10:54
As Jagg took the liberty of reopening this I might as well outline the issue. I'm trying to install Evennia develop-py3 branch on Windows 7. On running 'pip install -e evennia' I get the following error:

`
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program
Files\\Microsoft SDKs\\Windows\\v8.1\\lib'

    ----------------------------------------
Command "c:\users\user\python\evenv\scripts\python.exe -u -c "import setuptools,
 tokenize;__file__='C:\\Windows\\TEMP\\pip-install-idyqbi48\\twisted\\setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Windows\TEM
P\pip-record-9_hahd6f\install-record.txt --single-version-externally-managed --c
ompile --install-headers c:\users\user\python\evenv\include\site\python3.6\twist
ed" failed with error code 1 in C:\Windows\TEMP\pip-install-idyqbi48\twisted\
`

From the best I can tell, SDK 8.1 is only available on Windows 8 and above.

**Comment by Griatch** [comment] 2019-06-09 13:16
I cannot reproduce this particular, latest, error on Win7. A lot has changed in the branch since so if this problem persists another ticket should be opened. Closing again.

**Closed** 2019-06-09 13:16 UTC
Labels: OS/DB-dependent, bug, develop-branch
