### ISSUE TITLE
Stuck web calls max out cpu usage

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1493] opened 2017-10-27 01:36 UTC
#### Brief summary of issue / Description of requested feature:
So a few times I've had an issue where after a particularly long server event, such as our weekly script which takes a few minutes to finish, our cpu usage will spike through the roof, and I get alerts from Linode saying that we're way over their allowed threshold. When I go to `@reload` the server, I get notifications of it trying to let pending webserver requests to finish, and it'll be stuck there, since they don't ever finish on their own. This requires me to then `kill -9` the process to get it over with. My theory is that if the server is very busy, webserver requests made during that time get lost somehow but start to consume more and more resources.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Possibly try to run some very long, time-intensive script that locks down the server
2. Make web requests during this period
3. Monitor cpu usage, see if the server can be reloaded afterwards

#### Error output / Expected result of feature
CPU usage skyrockets, those web requests are unresponsive, server cannot be reloaded because the requests never finish.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I'm still on the previous version of Evennia, so it's possible this could already be resolved in the current version, if it's related to the portal having that open connection somehow.

If it's not fixed in the current version, is there some some setting we can use somewhere to make web requests that are unresponsive time out after some period of time, like 30 seconds to a few minutes?

**Comment by BlauFeuer** [comment] 2018-01-09 15:05
I've had this occur recently on Evennia 0.7.0.  `kill -9` on the process and `evennia start` got it unstuck. It has only happened once.

**Comment by strikaco** [comment] 2018-10-30 22:42
For the sake of testing, is your web instance sitting behind apache/nginx and mod_wsgi/gunicorn or did you simply expose port 4001?

The script in question, does it hammer the DB, spawn a bunch of threads/API calls or just burn CPU/RAM? How can one emulate what you're doing that causes this problem?

**Comment by TehomCD** [comment] 2018-10-31 03:35
Just using twisted, no reverse proxy of apache/nginx. Script does a huge number of database writes. You could probably emulate it via a bunch of Attribute updates. As long as it takes 10 minutes or go and people are trying to use the website at the same time, it might happen. Pretty rare when it does occur, though. Maybe one time out of 50 or so (about once a year when running script weekly).

**Comment by strikaco** [comment] 2018-11-27 20:41
I forgot to ask but I assume you are using Sqlite? I did the same for my testing. My environment is an Ubuntu 16.x(?) build with 4G of RAM and a 10G swap.

I wrote a management command that infinitely creates new accounts by making a `requests.post` call to a View set up for this purpose. It sets a bunch of attributes post-creation as well. Given a few minutes for warmup, if I start poking around on the website it will trigger a locked db error. There is no discernable difference in CPU use.

So I can't reproduce this as stated (no hard lockups), but it does raise other issues :\

**Comment by TehomCD** [comment] 2018-11-30 00:02
I think that any sort of loop will be blocking if it sits in the main process unless it's done as a coroutine that the event loop calls periodically with twisted's `inlineCallbacks` or some such. I'm sure @Griatch would know much better than I would, though.

**Comment by Griatch** [comment] 2021-10-31 21:24
@TehomCD This is an old ticket (Evennia was still Python2 when it was written), but I suspect long-running requests could remain being an issue.
I have it on the docket for Evennia 1.0. Just to check - do you still see this error occur also with later Evennia versions?

**Comment by TehomCD** [comment] 2021-11-01 23:04
I'm not sure, actually - any time I see the CPU maxxed out is usually due to the AMP bridge failing and getting in a loop that blocks communication across it. Reload often fails after the rework to the portal/server process, but is unrelated to the above, I think.

**Comment by Griatch** [comment] 2022-01-19 22:04
With the lack of updates and inability to reproduce this, I'm closing this for now. Feel free to re-open should it appear again.

**Closed by Griatch** 2022-01-19 22:04 UTC
Labels: bug, branch-master
