### ISSUE TITLE
[BUG] using SET to create a dictionary attribute and assign a key:value pair at the same time creates a misnamed attribute

### ISSUE THREAD

**Issue by Tegiminis** [evennia/evennia#2796] opened 2022-07-07 07:18 UTC
#### Describe the bug
Using SET to create a dictionary attribute and assign a key:value pair at the same time through switches creates a misnamed attribute. For example, if you were to use `set self/foo['foo'] = 3`, it creates an attribute named `foo['foo']` with the value 3, rather than the attribute `foo = {'foo': 3}`.

This is a problem because if you then try to remove the misnamed attribute with `set self/foo['foo'] =`, it errors out as a mismatch, as it is an integer attribute instead of a dictionary. You can only remove it via code or resetting your typeclass.

#### To Reproduce
1. Use `set self/foo['foo'] = 3`
2. Observe that it creates the attribute `foo['foo'] = 3` instead of the attribute `foo = {'foo': 3}`

#### Original Repro

1. I had the following attribute on myself:``buffs = {'maxHP': {'ref': <class 'content.bufflist.PropertyBuffTest'>, 'pid': 'maxHP', 'start': 1657171549.4178708, 'duration': 0, 'prevtick': None, 'stacks': 1, 'source': succendo}}``
2. I attempted to change the duration with the following command:``set self/buffs['maxHP']['duration'] = 30``
3. Which created the attribute ``buffs['maxhp']['duration'] = 30``.
4. I then attempted to delete it with the command ``set self/buffs['maxHP']['duration'] =``
5. Which resulted in the following traceback:
```
Traceback (most recent call last):
  File "c:\muddev\evennia\evennia\commands\cmdhandler.py", line 621, in _run_command
    ret = cmd.func()
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 1946, in func
    result.append(self.rm_attr(obj, attr, category))
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 1739, in rm_attr
    deep = self.do_nested_lookup(val, *nested_keys[:-1])
  File "c:\muddev\evennia\evennia\commands\default\building.py", line 1706, in do_nested_lookup
    result = result.__getitem__(key)
AttributeError: 'int' object has no attribute '__getitem__'
```

#### Expected behavior
Either an error that informs the player they must create a dictionary through the format `set self/foo = {'foo': 3}`, or proper parsing of set command arguments such that `set self/foo['foo'] = 3` creates the attribute `foo = {'foo': 3}`.

#### Environment, Evennia version, OS etc
1.0 dev

**Comment by Griatch** [comment] 2022-07-07 08:10
This is not a bug. 

- `set self/foo['foo'] = 3`  does not work and should never work to create a dict. It would not work in Python either. We can't exclude [] from the syntax either or do some sort of assumptions about what the user expects to be a dict or not, there are all sorts of weird namings out there that people want to use.
- The correct way to create a dictionary is `set self/foo = {}` followed by `set self/foo['bar'] = 3`, or to use `set self/foo = {'bar': 3}` as you wrote.
- We can add a dict example to the `set` command help string, but this works as expected.

**Comment by Tegiminis** [comment] 2022-07-07 08:15
It may work as expected, but if you manage to create an attribute with this malformed name, it cannot be removed using SET. So there's still a bug that needs to be fixed here.

**Comment by Griatch** [comment] 2022-07-07 08:21
Ok, that extends the original ticket then. Please add exactly how you 'attempted to remove' the malformed Attribute to get the traceback and add it in with the original ticket.

**Comment by Griatch** [comment] 2022-07-07 08:22
Ok, that adds more info to the ticket then.

**Comment by Tegiminis** [comment] 2022-07-07 08:24
Maybe it's more than a single nest deep? I'm updating with the original repro right now, which is two dicts deep.

**Comment by Griatch** [comment] 2022-07-07 08:25
Update the ticket if you find a way to reliably reproduce the delete issue.

**Comment by Tegiminis** [comment] 2022-07-07 08:30
I'm not sure how I ran into this now since using SET and a malformed attribute name cleans up properly... so I'm stumped.

**Comment by Griatch** [comment] 2022-09-24 23:08
I can't reproduce this. Unless there's some new info, I'll close it.

**Closed** 2022-09-24 23:30 UTC
Labels: bug
