### ISSUE TITLE
Global scripts stop responding & can't be removed

### ISSUE THREAD

**Issue by Goldscutlle** [evennia/evennia#635] opened 2015-01-02 18:26 UTC
I am using a global script for time of day functions. Even though it is flagged as persistent, it does not survive a server restart. It stays in the database, & shows up using @scripts, but cannot be resumed or started with @script command.

I am using Windows 7 64-bit, Python 2.7.9rc1, Twisted 14.0.2, Django 1.7.1

```python
from ev import Script
ECHOES = ["dawn",
         "morning",
         "mid-morning",
         "noon",
         "afternoon",
         "mid-afternoon",
         "late afternoon",
         "evening",
         "dusk",
         "sunset",
         "night",
         "midnight"]  
class TimeTicker(Script):
    """
    This implements a subscription model ticker 
    that drives global notifications
    """
   
    def at_script_creation(self):
        "Called when script is created"
        self.key = "time_ticker"
        self.interval = 60 # * 60 * 2 # every two hours        
        self.persistent = True 
        # storage of subscriptions
        self.db.subscriptions = []
        self.db.timeindex = 0
    def subscribe(self, obj):
        "add object to subscription"
        if obj not in self.db.subscriptions:
            self.db.subscriptions.append(obj)
    def unsubscribe(self, obj):
        "remove object from subscription"
        try:
            del_ind = self.db.subscriptions.index(obj)
            del self.db.subscriptions[del_ind]
        except ValueError:
            pass
    def list_subscriptions(self):
        "echo all subscriptions"
        return self.db.subscriptions        
    def at_repeat(self):
        "called every self.interval seconds"
        echo = ECHOES[self.db.timeindex]        
        # msg_contents() is a standard method, so this
        # ticker works with any object.
        for obj in self.db.subscriptions:
            #obj.msg(echo, self, **kwargs)
            obj.msg_contents(echo)
        # resetting/stepping the counter
        if self.db.timeindex == len(ECHOES) - 1:
            self.db.timeindex = 0
        else:
            self.db.timeindex += 1
```

**Comment by Griatch** [comment] 2015-01-02 19:58
Don't know why your script does not survive a server restart, that should only happen if you have a bug in it. Also, note that  `@script` is for scripts stored on an object. Use `@scripts` for global scripts - first to see the `#dbref` of your script, then use `@scripts/stop #dbref` to stop it. Is this still not working?

**Comment by Goldscutlle** [comment] 2015-01-02 21:37
You can close this issue. It was MySQL database user permissions. Didn't
have execute permissions. :/

**Comment by Griatch** [comment] 2015-01-02 22:45
That would do it. :) Closing this issue.

**Comment by Antrare** [comment] 2015-01-02 22:57
May be worth making a note somewhere on that as I have had the same issue.

**Comment by Antrare** [comment] 2015-01-02 23:25
I'm going to reopen as I have a similar issue after a shutdown of evennia I run into the same issue.

Ircbot and my custom global scripts do not start. They must be removed and added again for them to work.

**Comment by Goldscutlle** [comment] 2015-01-02 23:47
I have switched back to Sql3lite for the time being, the scripts restore &
continue operating for some time now.

**Comment by Griatch** [comment] 2015-03-06 19:56
I cannot reproduce this problem on mysql using the latest Evennia no matter what I try. I'm closing this again. Please note for re-open if it can still be reliably reproduced using some particular setup and example code.

**Closed by Griatch** 2015-03-06 19:56 UTC
Labels: bug
