### ISSUE TITLE
Where's Limbo? Resources not loading properly.

### ISSUE THREAD

**Issue by jdshaeffer** [evennia/evennia#1850] opened 2019-05-31 14:05 UTC
#### Brief summary of issue / Description of requested feature:
I dove into the quick start and ran all the commands with some success. Ran `evennia start` and the server is up and running fine. I then see I should navigate to the `Limbo` room and run `@batchcommand tutorial_world.build`. I go to the web client and also connect via telnet, and no matter what I type on either platform, I get no output. I can't find a `Limbo` room, nor can I run any commands. Also, it seems there are resources not loading properly when I go to http://localhost:4001/. I inspect and I see that there are 5 404 error messages (failed to load resource) in the console. When I go to the web client and inspect, there are 22 404 error messages (failed to load resource). I don't know where to go from here.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Follow the quick start word for word, command for command (for macOS installation)
2. Navigate to http://localhost:4001/
3. Observe unloaded resources and lack of options...?

#### Error output / Expected result of feature
Following the `Where To Go Next` tutorial and continuing with a successful build.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I'm running macOS Mojave version 10.14.5. Python version of 2.7.15. For now I think I'll delete everything and try again. Thanks!

**Comment by Griatch** [comment] 2019-05-31 14:11
@jdshaeffer Unclear from this what the issue is; suffice to say the normal result of following the instructions is not this :wink:
To start over, you should not need to delete 'everything' though - just delete your `mygame` folder and re-run from the `evennia --init mygame` command to rebuild the mygame folder etc. Continue from there to see if you still see the same problems. If so you'll need to paste the exact tracebacks you are getting.

**Comment by jdshaeffer** [comment] 2019-05-31 14:22
@Griatch, thanks for the quick response! I ran your suggestions above, and am now getting an Error 500, Internal Server Error the moment I navigate to http://localhost:4001/. Seems like I messed something up on the earlier bits of the install. Sorry to bother, I'm going to do a clean sweep and start from scratch. Thanks!

**Comment by Griatch** [comment] 2019-06-07 17:03
Unclear what the issue is. I'll close this for now, if you find something can be reproduced, comment in here again and I can re-open this.

**Closed** 2019-06-07 17:03 UTC
