### ISSUE TITLE
Infrequent RunTimeError in portal.log

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1207] opened 2017-02-10 11:56 UTC
#### Brief summary of issue / Description of requested feature:
Occasionally in the portal log, the following exception will pop up. This happens fairly rarely (a few times a week, perhaps) and doesn't seem to affect anything, but I thought I should post it just on the off chance it could somehow be related to other errors.

```
2017-02-05T00:12:46-0500 [ProxyClient,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/application/app.py", line 310, in runReactorWithLogging
	    reactor.run()
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
	    self.mainLoop()
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1207, in mainLoop
	    self.doIteration(t)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 396, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
	    selectable.readConnectionLost(f)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 272, in readConnectionLost
	    self.connectionLost(reason)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 478, in connectionLost
	    self._commonConnection.connectionLost(self, reason)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 486, in connectionLost
	    self.handleResponseEnd()
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/proxy.py", line 87, in handleResponseEnd
	    self.father.finish()
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/server.py", line 231, in finish
	    return http.Request.finish(self)
	  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 863, in finish
	    "Request.finish called on a request after its connection was lost; "
	exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```
http://stackoverflow.com/questions/10710047/twisted-http-server-error seems to suggest it could just be a cosmetic error that can be ignored, but I thought it might warrant a look in case it could somehow be related to things like the reload issue.

#### Steps to reproduce the issue / Reasons for adding feature:

1. No idea how to reproduce them. I just see them randomly in the portal log.

#### Error output / Expected result of feature
The above exception.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
N/A

**Comment by Griatch** [comment] 2017-02-18 19:35
@TehomCD This is due to the user closing the connection before the webserver request has had time to finish. I added the errback in the webserver (see the commit) but since I cannot reproduce this locally (it appears it's too fast for me to be able to disconnect the request and trigger an error) I will keep this issue open for a while so you can see if the error keeps popping up or not; if it does it might be worth dropping this same errback handling in some other of the views.

**Comment by TehomCD** [comment] 2017-02-27 23:32
The following exception was generated by the latest change:

```
2017-02-22T21:48:34-0500 [twisted.internet.defer#critical] Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 1951, in connectionLost
    request.connectionLost(reason)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/web/http.py", line 1337, in connectionLost
    d.errback(reason)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/tehom/arx/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/tehom/arx/evennia/evennia/server/webserver.py", line 73, in <lambda>
    request.notifyFinish().addErrback(lambda f: f.cancel())
exceptions.AttributeError: Failure instance has no attribute 'cancel'
```

**Comment by Griatch** [comment] 2017-08-27 13:58
This, and notably the traceback from the first fix, appears to be a lingering issue that has already been resolved. Closing.

**Closed by Griatch** 2017-08-27 13:58 UTC
Labels: bug, more info needed
