### ISSUE TITLE
object.search() with multiple potential results returning NoneType?

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1225] opened 2017-02-19 14:04 UTC
#### Brief summary of issue / Description of requested feature:
I can't imagine this is intended behavior, but if I search an object for a given item and the item is unique among the parent's contents, the item is returned as expected.

However, if an object contains multiple similar items and a search is performed for one, NoneType is returned.

This is pretty annoying since when I get NoneType back I don't know if the item doesn't exist at all or if multiple items were found. 

If this is intended, is there a more reliable way of searching a container?

#### Error output / Expected result of feature
Traceback (most recent call last):
  File "/home/johnny/projects/sandbox/tests.py", line 117, in test_object_search_multi
    self.assertTrue(self.char1.search('object1'))
AssertionError: None is not true

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia version 46a5a62

Test case available here:
https://gist.github.com/strikaco/2893fae870dc9b842a42db2b566e179c

**Comment by Griatch** [comment] 2017-02-19 14:23
This is indeed intended behavior. The `DefaultObject.search` method will by default return either a single result or `None`. This is because the search method will itself handle all error messaging for you, correctly listing the options in a multimatch or give an error if no match was found (this is customized through overriding the default handler function `settings.SEARCH_AT_RESULT`). This functionality allows for the convenient shorthand
```python
    target = self.caller.search(self.args)
    if not target:
        # at this point caller already saw any error messages.
        return
```
Which is a very common structure in Commands. 

If you want to bypass the automatic error handling you have two options: 
- Call the object search with `quiet=True`. You will then always get a list of 0, 1 or more results and is expected to handle any error messaging yourself. This is likely what you are looking for here. 
- Use ´evennia.search_object` instead. This is a lot more "raw" than than the `DefaultObject.search` though and doesn't offer all the convenient input analysis like nicks and room-limiting. So the former is recommended for use in Commands. 

Closing.

**Closed by Griatch** 2017-02-19 14:23 UTC
