### ISSUE TITLE
Contrib RP System Issues

### ISSUE THREAD

**Issue by BlauFeuer** [evennia/evennia#1112] opened 2016-10-29 03:01 UTC
#### Brief summary of issue / Description of requested feature:
1. Contrib RP System Issues (issue unresolved in #1054) - The new character still sees the Superuser character (named "One") listed in the room contents with "None" as its room pose
2. Using "emote" command without making a reference to any object causes traceback.
3. Using "emote" command from Superuser character with a `/me` reference.
4. Using "emote" command from Superuser character with a `/person` reference to newly created character.
#### Steps to reproduce the issue / Reasons for adding feature:
1. In new game folder, init, migrate, and start a new game
2. Add RP System to default object, character, and room typeclasses, reload game.
3. Create and login new character (Observe output 1)
4. From second character, `emote tests RP system.`  with the new character (Observe output 2 with traceback)
5. From Superuser character, `emote /me`  does not replace `/me` reference. (Observe output 3)
6. From Superuser character, `emote waves to /person!`  does not replace `/person` reference. (Observe output 4)
   #### Error output / Expected result of feature
##### _Output 1_

``` text
Limbo
Welcome to your new Evennia-based game! Visit http://www.evennia.com if you need
help, want to contribute, report issues or just join the community.
As Player #1 you can create a demo/tutorial area with @batchcommand tutorial_world.build.
One None
```
##### _Output 2_

``` text
Traceback (most recent call last):
   File "/home/evennia/evennia/evennia/commands/cmdhandler.py", line 493, in _run_command
     ret = yield cmd.func()
   File "/home/evennia/evennia/evennia/contrib/rpsystem.py", line 810, in func
     send_emote(self.caller, targets, emote, anonymous_add='first')
   File "/home/evennia/evennia/evennia/contrib/rpsystem.py", line 499, in send_emote
     send_emote = emote.format(**receiver_lang_mapping)
 KeyError: u'#3'
```
##### _Output 3_

``` text
One /me
```
##### _Output 4_

``` text
One waves to /person!
```
#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Current evennia, master branch, RP System contrib, any OS.
1. Superuser character named "One" has _no RP defaults_, including sdesc or room pose setting. This simulates a character object created before RP system is engaged.
2. KeyError occurs when no emote reference is given in user-supplied input, but should resolve to a reference to the character caller object.
3. and 4... seems related to "One" character not being typeclassed as an RP object.  **Might be expected behavior.**

**Comment by CloudKeeper1** [comment] 2016-11-01 02:19
In reproducing issue 2. "Using "emote" command without making a reference to any object causes traceback." I found when player one(with sdesc attributes) emotes with no reference in a room with player two(no sdesc attributes) it works. When player one(with sdesc) emotes with no reference with player two(with sdesc) it causes the key error.

**Comment by CloudKeeper1** [comment] 2016-11-01 03:47
Re: Issue 2.
Maybe I'm way off but...
At line 499 `send_emote = emote.format(**receiver_lang_mapping)`
emote is expecting receiver_lang_mapping to have an entry with the key of your dbref:
See lines 478 & 482:
`key = "#%i" % sender.id`
`emote = "%s%s%s" % ("{%s}" % key, possessive, emote)`

The error is caused because receiver_lang_mapping does not have a key that matches the senders id when no reference is made. I followed the rabbit hole:

receiver_lang_mapping is a dict that has it's entries supplied by `language_mapping.iteritems()` at line 494
language_mapping is a dict which has it's entries supplied by `parse_language(sender, emote)` at line 467
`parse_language(sender, emote)` returns a dict  `mapping[key] = (langname, saytext)` 
where key is `key = "##%i" % imatch` 
where imatch is  `for imatch, say_match in enumerate(reversed(list(_RE_LANGUAGE.finditer(emote)))):`
where emote is `emote = _RE_REF_LANG.sub(r"\1", emote)`

From what I can tell, the emote replaces all the instances of '/random_player says "hello"' effectively with {dict[dbref]} says "{dict[message]}" and sends the reference dictionary along with the emote to later be parsed by sdesc and language handlers before it's values are injected back in at line 499.

On line 476 `if anonymous_add and not "#%i" % sender.id in obj_mapping:` it adds {senders.dbref} to the front of the emote, but this is getting caught up with line 499 `send_emote = emote.format(**receiver_lang_mapping)` causing it to request a value that is never supposed to be in that dictionary. I think what is intended is the {senders.dbref} at the beginning added by line 476 is supposed to remain until line 525 `receiver.msg(send_emote.format(**receiver_sdesc_mapping))`

Line 499 assumes that there will be a reference to the senders dbref in that dictionary when there isn't unless a reference is used inside the emote command i.e. "/me" which is why /me works.

Note: I tried removing a hash from  `key = "##%i" % imatch`  at line 291 as a stab at the dark but the error persists.

**Comment by Griatch** [comment] 2016-11-01 20:06
Thanks for the elaborate issue, made it very easy to reproduce and test!

1. This was a genuine bug, the pose was set to `None` instead of the empty string when no pose was set - a pair of parentheses where missing. 
2. This was also a genuine bug, a regression from the recent fixes to rpsystem relating to says and quotes. The sdesc and language parsing is a two-step process with the language mapping being applied first - this means all sdesc mappings must be escaped, which was not done properly for the case of no sdescs being added (which adds the self reference automatically - this must also be escaped and was not). 
3. This is expected behavior and is resolved by `@type/force self` on the superuser. For objects to use the RP typeclass they must be re-initialized.
4. Same as 3. 

Closing.

**Closed by Griatch** 2016-11-01 20:06 UTC
Labels: bug
