### ISSUE TITLE
Default @tunnel creates alias conflict with inventory command

### ISSUE THREAD

**Issue by driscoll** [evennia/evennia#1297] opened 2017-04-03 22:31 UTC
#### Brief summary of issue / Description of requested feature:

By default, if you @tunnel to a new room with "in" as one of the exits, the exit will include the alias "i". This creates an alias conflict with the "inventory" command which has the aliases ['inv', 'i'] by default. As a result, a player in the room with the "in" exit will not be able to check their inventory.

#### Steps to reproduce the issue / Reasons for adding feature:

1. @tunnel o = newroom
2. o
3. inventory

#### Error output / Expected result of feature

Error output:
Command 'inventory' is not available. Maybe you meant "@version"?

Expected result:
Contents of player inventory

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

The simplest fix would be to remove the i alias from the inventory command

**Comment by eldritchsemblance** [comment] 2017-04-04 03:54
@Griatch I think this is one of those places where standardizing on MUXlike interfaces without being MUXlike under the hood creates user expectations that don't match the behavior.  The MUX order of command precedence (see [Mush Manual](http://www.mushcode.com/File/MUSH-Manual---Section-IVColon-Wizards-Supplement)), along with MUX's command parser using longest-substring pattern matchings for exits and commands, this means the behavior in a room with local exit "In <I>;in;i" the exit will be caught with "i" and "in", as local exits take precedence over internal commands, but "inv" goes through to the command because of the way the parser matches tokens.

If the intention is for Evennia to still behave in a MUXlike manner for building purposes, rather than change the default behavior of @tunnel, change the parser.  A MUX/MUSH/MUCK player encountering an exit  "In" would expect to just be able to type "i"

**Comment by BlauFeuer** [comment] 2017-04-04 04:25
I'd have to say as a MUX/MUSH/MUCK player who has frequently encountering a local "in" exit, my expectations are different.

I don't expect builders to alias exits that override aliases of default character commands, even though MUX/MUSH/MUCK allows it.   So I'm frustrated by typing "i" and going "in" when I expected to see my inventory, or typing "w" to whisper, but instead going west.

In my mind, but certainly not everyones:
* No exit should have an "i" alias.  "i" has always been for viewing inventory, even though "o" is reasonable for being short for going out when the native language is English.  "in" is for going in, and "i", "inv" is for inventory
* No command should have a "w" alias.  "w" has always been for going west and "wh", "whisper" is for whispering.

To confuse matters, "o" is for Osten (east) in German language mu*, so "out" is never aliased as "o". Cardinal directions (as in the case of "w") should never replace a default command. 

But that might just be a game-specific policy. The real issue I guess would be making the framework behave how the developer intended, or making it easier for administrators to enforce a standardized building policy.

**Comment by BlauFeuer** [comment] 2017-04-04 04:45
Hmm, the "o" is for Osten (east) is an LPMUD, and my expectations are clearly for MUX-like behavior, which is why I'm so often frustrated with MUX/MUSH/MUCK.

How can Evennia's command handler better emulate different mu* styles?  If it's already built in, we need to develop the corresponding wiki pages.

**Comment by BlauFeuer** [comment] 2017-04-04 04:49
How can Evennia's command handler better emulate different mu* styles?  If it's already built in, we need to develop the corresponding wiki pages.

**Comment by Griatch** [comment] 2017-04-08 19:40
@eldritchsemblance, @BlauFeuer: Apart from the fact that Evennia's default commands are not aiming to emulate MUX verbatim, but mainly used it as a starting point for its command corpus, this is not really a parser issue but a command priority issue. The Evennia parser can perfectly separate the commands, but it never gets the chance in this case; The reason for this error is because command objects are made equal both by `key` and by their `aliases` at the cmdset merger stage. As outlined in the documentation, two Commands having *any one of their key or aliases matching* are considered identical when it comes to their cmdsets merging. And since the ExitCmdSet (where in/i is) has a higher priority than the Character Cmdset (where inventory/i is), the ExitCommand object will take the place of the Inventory Command object and thus the "inventory" command will be no more. Normally you want the exits to always be available, but doing so does require making sure you are not overriding key commands in the lower-prio set, which is the issue here. 

One possibility would be to lower the exitcmdset priority to be the same as the CharacterCmdset while turning on `duplicates=True` on it. Then the parser will get to work on them and will work very hard to separate them. The result will be a multimatch error on using the alias 'i' (you get a little menu where you can choose if you want the exit or the inventory Command). If you explicitly enter  'inventory' or 'in' the parser will separate them uniquely and each will work as normal. This solution is potentially more general but less appealing if you always want the exits to work no matter what.

I think a sane (and simple) default here is to simply not have `@tunnel` assign the `i` alias by default, but I am open to pondering the consequence of instead defaulting to the multimatch.

**Comment by BlauFeuer** [comment] 2017-04-09 19:17
Not having `@tunnel` assign the `i` alias was one of the first modifications I made, even though it removed the shortcut for `in`.  Defaulting to multimatch choice is entirely reasonable if the user was prompted in a more useful way.

If the multimatch response was "Do you mean `i` for `inventory` or `in`? (suggesting based on the command key), then the user would be prompted in a more informed way instead of being offered a choice between `1-i` and `2-i`.

**Comment by Griatch** [comment] 2017-04-21 07:56
Since this is not a bug but expected behavior with the current setup of the cmdset system. I'm closing this and deferring further discussion to the duplicate issue #1310.

**Closed by Griatch** 2017-04-21 07:56 UTC
