### ISSUE TITLE
Error on reload

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1770] opened 2019-01-17 08:27 UTC
#### Brief summary of issue / Description of requested feature:

I have an error when I use the `@reload` command.  It doesn't happen on a fresh installation of Evennia and the error message is pretty strange, so I can't give many useful details.  Talk about it in IRC?

#### Steps to reproduce the issue / Reasons for adding feature:

I can't reproduce the issue on Evennia Vanilla and my game is still a bit hard to install.  It's getting better but it requires some adjustments.  If the log is not enough to identify the issue I'll provide an install guide for Avenew.

#### Error output / Expected result of feature

That's what can be seen in the `portal.log` file after a reload.  Note that the reload in itself is successful.

```
19-01-17 08:50:10+01  |Portal| portal data_to_server: <class 'evennia.server.portal.amp.AdminPortal2Server'>, 0, {'operation': '\x03', 'server_restart_mode': 'reload', 'sessiondata': {1: {'protocol_key': 'telnet', 'address': '127.0.0.1', 'suid': None, 'sessid': 1, 'csessid': None, 'uid': 1, 'uname': 'vincent-lg', 'logged_in': True, 'puid': 1, 'conn_time': 1547711399.0513535, 'cmd_last_visible': 1547711404.7225628, 'cmd_last': 1547711404.7225628, 'cmd_total': 10, 'protocol_flags': {'ENCODING': 'latin-1', 'SCREENREADER': False, 'INPUTDEBUG': False, 'RAW': False, 'NOCOLOR': False, 'NOGOAHEAD': False, 'SCREENWIDTH': {0: 78}, 'SCREENHEIGHT': {0: 45}, 'FORCEDENDLINE': True, 'TTYPE': False, 'ANSI': True, 'MCCP': False, 'OOB': False, 'MXP': False, 'NOPKEEPALIVE': True}, 'server_data': {}, 'cmdset_storage_string': 'commands.default_cmdsets.SessionCmdSet'}}, 'portal_start_time': 1547711362.143507}
19-01-17 08:50:10+01  |Portal| dataReceived: b"\x00\x06_error\x00\x011\x00\x0b_error_code\x00\tEXCEPTION\x00\x12_error_description\x00*a bytes-like object is required, not 'str'\x00\x00"
19-01-17 08:50:10+01  |Portal| [EE] AMP Error for AdminPortal2Server: a bytes-like object is required, not 'str'
```

I don't get a regular traceback.  I can enter commands after a few seconds even if I never get the message "... server reloaded.".  However, if I use `@shutdown` (or `evennia stop` for that matter), I get another traceback in the log (server.log this time):

```
19-01-17 08:50:28+01 Unhandled Error
	Traceback (most recent call last):
	  File "d:\pyenv3\Lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "d:\evennia\evennia\server\amp_client.py", line 240, in server_receive_adminportal2server
	    server_sessionhandler.server.shutdown(mode='shutdown')
	  File "d:\pyenv3\Lib\site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "d:\pyenv3\Lib\site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "d:\pyenv3\Lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "d:\evennia\evennia\server\server.py", line 377, in shutdown
	    for p in AccountDB.get_all_cached_instances()]
	  File "d:\evennia\evennia\server\server.py", line 377, in <listcomp>
	    for p in AccountDB.get_all_cached_instances()]
	  File "d:\evennia\evennia\accounts\accounts.py", line 336, in unpuppet_all
	    self.unpuppet_object(self.sessions.all())
	  File "d:\evennia\evennia\accounts\accounts.py", line 322, in unpuppet_object
	    obj.at_pre_unpuppet()
	  File "d:\evennia\evennia\contrib\ingame_python\typeclasses.py", line 391, in at_pre_unpuppet
	    self.callbacks.call("unpuppeted", self)
	builtins.AttributeError: 'Character' object has no attribute 'callbacks'
```

Obviously this is due to the first error as, if I try to shutdown without having reloaded, all works.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

* Evennia branch: develop-py3

**Comment by vincent-lg** [comment] 2019-01-17 18:19
Okay, after debugging and catching a lot, I have a nice traceback to share.  This happens right after the server has reloaded and seems to be directly connected to the way information is pickled and unpickled by the dbserializer.  In other words, it might (possibly) be responsible for the errors in trying to use a database generated for Python 2, on a Python 3 Evennia.  However, I don't feel confident enough to remove this `to_str` and see if there's a counter-part in pickling, because I don't know how much that is used and how much it would break.  But that's probably something to do in the end, I let you decide, ask me to do something if needed:

```
Traceback (most recent call last):
  File "d:\evennia\evennia\server\sessionhandler.py", line 392, in portal_sessions_sync
    self.server.at_post_portal_sync(mode)
  File "d:\evennia\evennia\server\server.py", line 444, in at_post_portal_sync
    TICKER_HANDLER.restore(mode == 'reload')
  File "d:\evennia\evennia\scripts\tickerhandler.py", line 424, in restore
    restored_tickers = dbunserialize(restored_tickers)
  File "d:\evennia\evennia\utils\dbserialize.py", line 692, in dbunserialize
    return from_pickle(do_unpickle(data), db_obj=db_obj)
  File "d:\evennia\evennia\utils\dbserialize.py", line 682, in do_unpickle
    return loads(to_str(data))
TypeError: a bytes-like object is required, not 'str'
```

One last thing: if you want to reproduce the issue you will have to create a ticker in a fresh Evennia.  However, I had to place `self.server.at_post_portal_sync(mode)` in a try/except block, otherwise it would completely break the server (commands still worked, but shutting down the server would cause problems).

**Comment by Griatch** [comment] 2019-01-17 19:41
@vincent-lg I could not actually reproduce this when creating a ticker, but `pickle.loads` expects a bytes-object so this should clearly be changed. Closing.

**Comment by vincent-lg** [comment] 2019-01-17 20:04
Unfortunately the error persists, although it changes shape: it looks like there's another `to_str` somewhere but not in the traceback.  So `pickle.loads` expect bytes, we feed it str:

```
Traceback (most recent call last):
  File "d:\evennia\evennia\server\sessionhandler.py", line 392, in portal_sessions_sync
    self.server.at_post_portal_sync(mode)
  File "d:\evennia\evennia\server\server.py", line 444, in at_post_portal_sync
    TICKER_HANDLER.restore(mode == 'reload')
  File "d:\evennia\evennia\scripts\tickerhandler.py", line 424, in restore
    restored_tickers = dbunserialize(restored_tickers)
  File "d:\evennia\evennia\utils\dbserialize.py", line 692, in dbunserialize
    return from_pickle(do_unpickle(data), db_obj=db_obj)
  File "d:\evennia\evennia\utils\dbserialize.py", line 682, in do_unpickle
    return loads(data)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Griatch** [comment] 2019-01-23 19:54
@vincent-lg Let's see if this is fixed for you know, still can't reproduce here ...

**Comment by Griatch** [comment] 2019-01-23 20:58
@vincent-lg No need to apologize, good to catch these! Closing.

**Closed by Griatch** 2019-01-23 20:58 UTC
Labels: bug, develop-branch
