### ISSUE TITLE
[BUG - Develop] MENU_LOGIN hangs server at login

### ISSUE THREAD

**Issue by Antrare** [evennia/evennia#2981] opened 2022-11-13 05:03 UTC
#### Describe the bug
Evennia Server appears to hang upon login (new user & existing) when using the MENU_LOGIN contrib.

TOP shows twistd maxing out CPU at the time.

Server log shows both Authentication success & Login lines immediately

I was using the contrib prior to upgrading to 1.0 and it was not causing this issue.  

#### To Reproduce
1. Enable EVMENU by adding the following lines into conf/settings.py
CMDSET_UNLOGGEDIN = "evennia.contrib.base_systems.menu_login.UnloggedinCmdSet"
CONNECTION_SCREEN_MODULE = "evennia.contrib.base_systems.menu_login.connection_screens"
3. Reload the server
4. Attempt to login.

#### Expected behavior
Normal login performance.

#### Develop-branch commit
(evenv) root@li2133-155:~/evriftmud/RiftMud/server/logs# evennia -v

    Evennia 1.0-dev (rev 4b6ee288c) (rev 4b6ee288c)
    OS: posix
    Python: 3.10.8
    Twisted: 21.7.0
    Django: 4.0.8

#### Additional context
None.

**Comment by InspectorCaracal** [comment] 2022-11-13 05:48
I reproduced this, although I'm getting more and longer delays. Both the account name and password entry steps take several seconds to process, and I've had the final node hang for multiple minutes before I finally killed the server.

Also, it hangs when you quit login as well, not just when you successfully log in, meaning it's `node_quit_or_login`.

After noting and typing the above line, I changed the quit/login node to return `"", None` instead of `"", {}` and that resolved the final long hang. However, I still have a couple seconds of apparent lag on each node.

**Comment by Antrare** [comment] 2022-11-13 08:09
Confirming that removed the big hang I was experiencing.  Leaving this open for additional reported lag issue

**Comment by Griatch** [comment] 2022-11-13 16:33
@InspectorCaracal Thanks for reproducing; looks like a regression then.

**Comment by Griatch** [comment] 2022-11-13 19:32
Fixed the issue (there was a general problem with closing the menu if the option was returned as `{}`) as well as improved speed for the menu-login by a lot.

**Closed by Griatch** 2022-11-13 19:32 UTC
Labels: bug, branch-develop
