### ISSUE TITLE
[Discussion] Adding a layer to support later CmdSet modifications

### ISSUE THREAD

**Issue by vlegoff** [evennia/evennia#1602] opened 2018-03-29 08:25 UTC
#### Summary of discussion

As it is, when we add a `CmdSet`, its `at_cmdset_creation` method is called which is expected to add commands.  However, adding or removing commands in this CmdSet afterward doesn't work very well.

#### Reason for the discussion

I imagine I'm one of the few people trying to dynamically create, add and remove commands to a CmdSet outside of its `at_cmdset_creation` method.  To some extent, it looks a lot like what the `EvMenu` does, but instead of having a simple command applied in the case of `NO_MATCH`, I have two menu-like structures with true Evennia commands that would need to be added and removed quite dynamically from the CmdSet.  This is the case with my app system (where a command is available in a given context) and my building menu system (where a command is dependent on the open menu at the time).

So far, what I'm doing is a bit cumbersome: I remove the CmdSet and add it again, being sure that my commands are added in the `at_cmdset_creation` method.  I suggest that we allow for more flexibility in adding and removing commands after the CmdSet has been created in a more efficient way.

#### Methods to add/modify

- `CmdHandler.get`: might take an optional argument to get a specific CmdSet (class or Python path).  It might not play well with the method however, but to get a specific `CmdSet`, one has to browse, which might not be the best option to dynamically add/remove commands in it.
- `CmdSet.add`: I suggest this would support adding commands after the `at_cmdset_creation` method has been called.
- `CmdSet.remove`: same thing here, as removing commands after the `at_cmdset_creation` method is not currently possible or rather, it doesn't remove the command from the caller's list.
- `CmdSet.at_cmdset_destroy`: to add automatic actions when the CmdSet is removed, mostly to clean things up.

**Comment by Griatch** [comment] 2018-03-29 08:37
The problem with this is that the CmdSet is an in-memory structure that is built in code. While the cmdset stack is stored, the cmdset itself is not (nor are any Commands). Instead the cmdset is rebuilt from its initialization when it is loaded into memory. In short, CommandSets are not meant to be modified after they have been initialized. Adding these kind of methods makes it seem like it's not an ugly hack but intended behavior. Consider this: You have modified your cmdset dynamically as you suggest (using the new methods, say). Now you `@reload` the server. This will wipe your custom cmdset modifications and people in the middle of doing things before the reload now suddenly cannot...  
Could you elaborate more on why you are trying to build a system that works like this?

**Comment by vlegoff** [comment] 2018-03-29 08:55
Yes, of course.  I'll take a basic example in my building menu, as this is intended for a PR and I want to do it right.

So when you open a menu, you see something like:

    Room building menu: Limbo(#2)
    [T]itle
    [Q]uit the menu

So here, the building menu creates two commands:

- `t` to access the room title.
- `q` to simply leave the menu.

If you enter `t`, then you get to edit the room title.

    -------------------------------------------------------------------------------
    Room title for: Limbo(#2)

    Enter the title of the room to change it.
    Or use @ to go back to the main menu.

    Current room title: Limbo

So at this point, it should remove the `t` and `q` commands, supporting only the special `NOMATCH`.  If this command is triggered, it will simply write into the room title.

If you enter `@`, you will go back to the main menu and the `t` and `q` commands will be created again.

And of course if you type `q`, the CmdSet will be removed.

This strategy allows for quick and intuitive separation: creating a menu choice might be as simple as creating an Evennia commands (it adds a layer but it's the same thing).  While having these cases directly checked in NOMATCH, like EvMenu, would be (in my opinion, anyway) less intuitive.

I'll add a note to answer your previous question: these commands are automatically added in `at_cmdset_creation` because my building menu CmdSet is optionally persistent.  So after a reload, when the CmdSet gets created again, it will check to see what commands it needs to dynamically create, and add them.  Since that's in `at_cmndset_creation`, Evennia will respond as expected.

In the case of my building menus, it doesn't really matter, since the user doesn't manually create the commands, the contrib automatically does it.  So, although I find it less nice, I could easily code it it NO_MATCH instead.  For my app system it's a bit different, but if you really think it's ugly to handle it with true Evennia commands, I can still come up with a solution.  I want to do something that aligns with Evennia rather than my ideas, but having separate commands seemed more intuitive and nice in the end.

**Comment by Griatch** [comment] 2018-03-29 16:31
@vlegoff 

I can only see one real advantage of dynamically creating Commands inside the EvMenu, and that would be to homogenize parsing of the options. Which is something which is only relevant in one case and that is when accepting arbitrary input from the user as part of the menu input (it has no purpose when you are selecting options - in that case there is no parsing at all). The arbitrary parsing is however much simpler than the normal command parsing since it works in a much more restrained environment (the node). So I think that making use of dynamic cmdsets for that is not only overkill, it will also create a layer of complexity to the cmdset system that is not necessary. 

I am just sitting with a menu like this in a local branch (I actually think I'm doing something similar as part my OLC effort as you are aiming for with your build menu, except I focus on prototypes and spawning). I found that one change to EvMenu made a lot of difference for the convenience of doing an EvMenu to edit objects: *If the `goto` callable given by an option returns `None`, re-run the current node.* This simple change (which I'll be merging into `develop` EvMenu) means that you can conveniently run operations on inputs without having to move between nodes. These are important features I found useful: 

- If the `goto` callable returns `None`, re-run the current node (new, not yet in develop)
- If the `goto` callable is given as a tuple `(callable, {kwargs})` you pass those kwargs into the `goto` callable.
- Those extra `kwargs` are also *passed on to the next node* if that node accepts `**kwargs`. 

With these additions I built a decorator for use with nodes. The one I made works so that it turns the node into a multi-page listing - you supply the decorator with the available options and callables for examining and selecting each option. You then just decorate a node in your menu and it turns into a complete listing of numbered options, including next/prev choices and the ability to examine a given option before selecting it. It's used like this: 

```python
from evennia.utils.evmenu import node_list

@node_list(available_typeclasses, examine_processor, goto_processor)
node_mylistnode(caller, raw_input, **kwargs):
    text =  "Set the parent Typeclass."
    return text, {}
```
That's all you need to produce the following output:

```
______________________________________________________________

Set the parent Typeclass.

(use 'look <option> or 'l<option>` to examine before making the selection)
______________________________________________________________
 1: evennia.accounts.accounts.DefaultAccount   7: evennia.objects.objects.DefaultCharacter  
 2: evennia.accounts.accounts.DefaultGuest     8: evennia.objects.objects.DefaultExit       
 3: evennia.accounts.models.AccountDB          9: evennia.objects.objects.DefaultObject     
 4: evennia.comms.comms.DefaultChannel         10: evennia.objects.objects.DefaultRoom      
 5: evennia.comms.models.ChannelDB             next                                         
 6: evennia.objects.models.ObjectDB            current: (1/2) 
```

You just need to make the processing `goto` callables that decides what processing happens when you examine an option (this will be given the actual chosen option as input along with the `caller`) as well as a callable to call when you select an option (since that is likely means heading to another node). 

I'll try to get this example out soon, but I think decorators could be a very useful concept for offering "custom nodes" for evmenus. Something similar could be done for your building menu.

**Comment by vlegoff** [comment] 2018-03-29 16:56
Yes, I see the point.  I will code my input handling inside of the `_CMD_NOMATCH`.  As for my app system I'll do the same, but I'll need some time to update it.  But it's not aimed to be merged anyway!

**Comment by Griatch** [comment] 2018-04-02 16:57
Thanks for the discussion though! Closing this now.

**Closed by Griatch** 2018-04-02 16:57 UTC
Labels: discussion, feature-request
