### ISSUE TITLE
Empty lines appearing in telnet clients after msg

### ISSUE THREAD

**Issue by Flabsy** [evennia/evennia#1395] opened 2017-08-15 10:22 UTC
#### Brief summary of issue / Description of requested feature:
In my telnet client (Mudlet), empty lines are appearing after every message sent to a player. The webclient provided by Evennia doesn't seem to have this issue.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect with Mudlet (or another telnet client)
2. Receive any line from the MUD
3. Empty space appears!

#### Error output / Expected result of feature
EX:
A nondescript room
This is a pretty boring looking room, yo.
You see a single exit leading northwest.

593h, 100s, 0m -flr>
*Note the empty line above the prompt

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Griatch suggests it could be an issue with the telnet protocols.

**Comment by Flabsy** [comment] 2017-08-15 11:40
I reverted to a telnet.py file from an old Evennia installation I had been using for a temporary solution.

GIT DIFF information here - https://pastebin.com/egXYgFvJ

**Comment by BlauFeuer** [comment] 2017-08-15 14:35
Mudlet has a known issue related to the Telnet Go Ahead. 
A work-around for this is to `@options NOGOAHEAD=True` after login.

If that works for you, then it's likely the issue is related to Telnet GA.

**Comment by vadi2** [comment] 2017-09-23 09:39
FYI Mudlet team isn't aware of any GA issues and it works across many implementations such as all IREs, MS2, and others.

GA was actually added per Mudlets request here: https://github.com/evennia/evennia/issues/1330 so I'd double-check that the implementation is correct.

**Comment by Griatch** [comment] 2017-09-23 09:56
This may well be an Evennia issue, have not had the time to look into it though - may be more time for it now that Evennia 0.7 has merged.

**Comment by Griatch** [comment] 2018-01-28 19:17
So the way I understand this, Mudlet expects IAC+GA *instead* of the last line break. Evennia adds the last line break *and* IAC+GA. This is what adds the extra line. This would be easy to fix if other clients did not expect this to work differently: For example tinyfugue will *not* add a line break of its own if Evennia doesn't do it - so when IAC+GA is send on its own every new line will be appended directly to the previous one.

**Comment by Griatch** [comment] 2018-01-28 22:19
@Flabsy So I had to resolve this with a new setting `FORCEDENDLINE` for clients like tinyfugue that needs a GA + endline. This resolves the empty-line issues with Mudlet while seemingly keeping things working as well as possible with other clients. If it pops up in other clients, flipping the `NOGOAHEAD` flag in `@options` should resolve it. Closing.

**Closed by Griatch** 2018-01-28 22:19 UTC
Labels: bug, master-branch
