### ISSUE TITLE
[BUG] evennia clearsessions fails

### ISSUE THREAD

**Issue by aMiss-aWry** [evennia/evennia#3109] opened 2023-02-09 15:36 UTC
#### Describe the bug
First mentioned by kosmobot on the discord, Lyrewyn and I reproduced it.

#### To Reproduce
1. `evennia clearsessions`
2. See `TypeError: NoneType takes no arguments`

#### Expected behavior
Should clear expired sessions.

#### Environment, Evennia version, OS etc
The default db, Evennia 1.1.1 (rev 559ee5ddf6)

#### Additional context
The traceback is all over the place: https://pastebin.com/raw/Ks7Qdsvt
Looks like a lot of website-related errors - maybe it's due to updating the website in 1.0?

**Comment by InspectorCaracal** [comment] 2023-02-09 17:40
Verified this happens to me on my local install of RoA, and does *not* happen to me on a clean install.

This looks a _lot_ like this (fixed) bug #3036 which makes me think it's an import order issue somewhere - possibly due to trying to import the web URLs too soon? I noticed my game also traces back to `from evennia.web.urls import url_patterns as default_url_patterns` before ending at a completely different failure point (CmdEvMenuNode for me).

**Comment by InspectorCaracal** [comment] 2023-02-09 17:59
The fact that it's happening on my local dev install and not on a freshly spun up test game (after migration -> start -> log in) on the same machine and environment makes me think that it's a side-effect of some sort of non-default settings configuration, but I have _so_ many non-default settings in RoA that it could be anything.

**Comment by Antrare** [comment] 2023-02-10 04:55
Adding my traceback from where it differs to the above one to hopefully help.  I don't override any of the default hooks/etc in my accounts typeclass, there are other additional functions though that all otherwise appear to work.

  File "/root/evriftmud/evennia/evennia/web/website/forms.py", line 39, in <module>
    class AccountForm(UserCreationForm):
  File "/root/evriftmud/evennia/evennia/web/website/forms.py", line 48, in AccountForm
    class Meta:
  File "/root/evriftmud/evennia/evennia/web/website/forms.py", line 56, in Meta
    model = class_from_module(
  File "/root/evriftmud/evennia/evennia/utils/utils.py", line 1612, in class_from_module
    mod = importlib.import_module(testpath, package="evennia")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/evriftmud/RiftMud/typeclasses/accounts.py", line 30, in <module>
    class Account(DefaultAccount):
TypeError: NoneType takes no arguments

**Comment by Griatch** [comment] 2023-02-25 23:23
I cannot reproduce this, so more information is needed. 
Most likely it's due to people having imports from `evennia` and when the `clearsessions` command is run, this causes an import situation where modules are loaded before the `evennia.__init_.py` package has had time to properly spin up. But so far I've not been able to reproduce this situation.

**Comment by Griatch** [comment] 2023-08-06 21:05
I can still not reproduce this, and I've seen no more information on how to do so. From the text, this may just be a side effect of wonky imports. Closing for now; ping here and I can reopen if there's more info to be had.

**Closed by Griatch** 2023-08-06 21:05 UTC
Labels: bug, more info needed, help wanted
