### ISSUE TITLE
[BUG] EvTables header skewed when using colors

### ISSUE THREAD

**Issue by mrseeker** [evennia/evennia#2532] opened 2021-09-16 11:04 UTC
#### Describe the bug
In certain cases, the evtables header can be skewed. This happens when the header has leading/trailing spaces. They get trimmed which causes the table to look skewed.

#### To Reproduce
1. Use the following example script:
```
from evennia.utils import evtable

table = evtable.EvTable("|cHeading1|n", "|cHeading2 |n", "|cHeading 3|n")
table.add_row("This","Test","test")
print(table)
```
2. Execute said script
3. See the error occur (as shown below)
```
+----------+-----------+-----------+
| Heading1 | Heading2 | Heading 3 |
+~~~~~~~~~~+~~~~~~~~~~~+~~~~~~~~~~~+
| This     | Test      | test      |
```

#### Expected behavior
The table should be straight without any indentations

#### Environment, Evennia version, OS etc
Evennia version: 1.0-dev (rev 54ebdb5ab)
        OS: nt
        Python: 3.9.7
        Twisted: 21.7.0
        Django: 3.2.7

#### Additional context
This only seems to occur when you are using colors and the space character, otherwise it looks fine.

**Comment by Griatch** [comment] 2021-09-16 11:06
Hm so if you clean up the header and removes the trailing whitespace beforehand, it's fine?

**Comment by mrseeker** [comment] 2021-09-16 11:22
If I clean up the trailing whitespaces, it works. However, I prefer to keep the whitespaces to make it a consistent header. For some reason, the trailing whitespaces automatically get removed.

**Comment by Griatch** [comment] 2021-09-16 18:26
I think you will have to expect the whitespace to be stripped - the table is auto-adjusting its width, so you introducing your own whitespace makes no sense. But that said, it should of course strip it without causing a visual glitch. :)

**Comment by Henddher** [comment] 2021-10-03 20:14
Hi,
I just tried to reproduce this issue using `evennia shell` and it seems to be working correctly, with colors and all.

```
(evennia) ~/Documents/github/evennia_game/game$ evennia shell
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from evennia.utils import evtable
>>> 
>>> table = evtable.EvTable("|cHeading1|n", "|cHeading2 |n", "|cHeading 3|n")
>>> table.add_row("This","Test","test")
>>> print(table)
+----------+-----------+-----------+
| Heading1 | Heading2  | Heading 3 |
+~~~~~~~~~~+~~~~~~~~~~~+~~~~~~~~~~~+
| This     | Test      | test      |
+----------+-----------+-----------+
>>> 
```


##### Baseline

```
commit cfac6a0fee0528d342e1975c7bf4397111b3d5e3 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Griatch <griatch@gmail.com>
Date:   Sat Oct 2 19:16:47 2021 +0200

    Lower maxnum of channel lines for web display
```

**Comment by Henddher** [comment] 2021-10-05 01:28
I just tried it on branch `develop` and I couldn't reproduce it either.

```
commit 28fae7af097d52b1ec5cfde4cdff491facd81378 (HEAD -> develop, origin/issue2506, origin/develop)
Author: Griatch <griatch@gmail.com>
Date:   Sun Sep 12 19:51:08 2021 +0200

    Fixes for $protkey protfunc implementation
```

**Comment by Griatch** [comment] 2021-10-05 20:27
@Henddher Thanks for investigating! I don't think this has magically been fixed in the 19 days since @mrseeker reported it though. I wonder if this is something that only shows in a particular client (or only in webclient for example) 
- @Henddher: Which client did you test in?
- @mrseeker: Which client(s) do you see this effect in?

**Comment by mrseeker** [comment] 2021-10-05 20:32
I am using the webclient with Google Chrome, and if it works without issues in the console, then I might suspect UTF-8 shenanigans and/or nbsp-like tokens. Is it reproducible with the commit I used? If not, then we can at least establish the fact that it does have issues on specific clients.

**Comment by Griatch** [comment] 2021-10-05 20:37
Rereading @Henddher's analysis, he used the `evennia shell` it seems. So maybe it's something webclient specific then, I've not tested it myself at this time.

**Comment by Henddher** [comment] 2021-10-19 03:56
FYI, I managed to reproduce the problem. Effectively, it was only visible on the web-client but the root cause is how text is converted to html.

**Comment by Griatch** [comment] 2022-02-15 22:37
Fixed in develop. Closing for book keeping.

**Closed by Griatch** 2022-02-15 22:37 UTC
Labels: bug, branch-develop, Hacktoberfest
