### ISSUE TITLE
Unexpected behaviour of a global script; triggered once after a server reload by using a command that reads a .db value from that script.

### ISSUE THREAD

**Issue by BP-Santo** [evennia/evennia#1862] opened 2019-07-07 02:19 UTC
CONTEXT:
1. I have a global, persistent script, added to the GLOBAL SCRIPTS dict in server settings; that script as part of it's at_repeat method writes to it's self.db a few variables and then ends with a `self.restart(interval=new_interval, start_delay=True)` where new_interval is calculated as part of the same at_repeat.
This script works as expected and survives a server reload properly on it's lonesome.
The new interval works as intended and the at_repeat fires again after new_interval afterwhich a different new_ineterval is calculated.
2. I also have a command, this command pulls values from the aforementioned script in this manner `my_variable = GLOBAL_SCRIPTS.my_script.db.my_variable` and uses some of those variables to perform it's function and message the player accordingly.
This command does not write anything to the variables stored on the script or otherwise call any methods on the script.

UNEXPECTED BEHAVIOUR:
Lets assume the script command is showing the interval as 5000 and the "Next" column shows 4500 and is slowly ticking down as intended.
If I then reload the server from ingame and run scripts again the "Next" column is displaying 4500 correctly and continuing to tick down.
**If however I use my command, the "Next" column resets back to square one and starts ticking back up from the lenght of the interval!**
**After this point I can use my command any number of times and it does not reset the value in that column and everything works as intended, the script cycles as intended etc.**

As part of my command I am displaying timestamps passed on from the script and they are out of sync as expected during the first time the command is run after a server reload and the interval resets.
After the interval elapses and my script gets to run it's at_repeat all is back in sync as expected.

I have observed this behaviour multiple times to confirm what is happening and reviewed the code multiple times and I can't see any problems with the code itself.
I plan to run a test where the script writes to .db values on a separate object and using the command to access values from that other object (some other script for instance without an interval component) but run out of time - I'll update the issue once I have more information.

**Comment by Griatch** [comment] 2019-07-07 08:41
@Volund would you have the time to take a look at this, you implemented the global container in the first place? I'm gone for a few weeks.

**Comment by BP-Santo** [comment] 2019-07-07 21:12
I created for my self an admin command for the purpose of starting global scripts from a predefined container and refactored everything else to use this instead of using the global scripts feature and all seems to be working as intended this way.

After a reload the scripts interval countsdown as intended and using the same command to pull a var from it does not result in it resetting and the timestamps going out of sync.

**So the problem seems to lie somewhere within the global scripts feature and not global scripts themselves.** If I notice something suspect though I will report back!

**Comment by Griatch** [comment] 2019-09-05 21:56
@BP-Santo: I cannot replicate this after latest changes. Please confirm. If the problem persists, please give an example of your `GLOBAL_SCRIPTS` structure and a simplified version of the script and actions taken as to help to reproduce it.

**Comment by Griatch** [comment] 2019-09-22 21:55
@BP-Santo Closing this since there have been no further updates. Please comment here if the error persists and I'll re-open.

**Closed by Griatch** 2019-09-22 21:55 UTC
Labels: branch-master, bug, more info needed
