### ISSUE TITLE
Looping through nested dict structure in Attribute is very slow

### ISSUE THREAD

**Issue by TehomCD** [evennia/evennia#1596] opened 2018-03-24 01:41 UTC
#### Brief summary of issue / Description of requested feature:
In IRC, Friarzen was asking for help figuring out why a loop he had in `return_appearance` was taking 10 minutes to work. In it, he had a map that was a nested dictionary structure, and after moving the attribute to a copy outside the loop, it returned more or less instantly. After confirming that `TYPECLASS_AGGRESSIVE_CACHE` was on, I tested it myself and was able to reproduce the effect.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Make a very large nested dictionary structure in an attribute. For myself, I did a dict of 200 numbered keys, and each one contained a dict of 200 numbered keys, storing an arbitrary number value.
2. After exiting and reentering shell to make sure it was not cached, I then did a nested for loop of looking up and assigning the nested value: `val = obj.db.hugeattribute[x][y]`
3. Although obj.attributes._cache will now show a match for hugeattribute, looping again will produce same very slow behavior.

#### Error output / Expected result of feature
The number of queries is modest when looking at django.db.connection.queries, what's expected, so caching does appear to be working. But I think that there might be some very slow repeated unpickling/deserializing going on with every iteration which is acting as the bottleneck. Doing a keyboard interrupt during the very slow loop produces a traceback that is in `process_tree` or `process_item` in `dbserialize.py`, so I think it's getting stuck there.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
I believe this is an issue on all branches. I was testing on master, Friarzen was on devel I believe. On the plus side, it's very easy to do a workaround for this issue - doing `hugemap = dict(obj.db.hugemap)` or whatever has no issues.

**Comment by Griatch** [comment] 2018-03-24 09:26
This is not surprising. Try this statement, which sets up a 60x60 2D grid in a dict and then reads it in a loop to create a list of tuples: 

```
    @py/time self.db.bigdict = {ix: {iy: (ix,iy) for iy in range(60)} for ix in range(60)};[self.db.bigdict[ix][iy] for ix in range(60) for iy in range(60)]
    Done (use self.msg() if you want to catch output) (runtime ~ 58416.9970 ms)
```

On my laptop this operation takes 58s to run. This includes the creation/storage of the grid too, but that's quick (about 36ms). Now contrast it to this variation which has the same end result:

```
    @py/time self.db.bigdict = {ix: {iy: (ix,iy) for iy in range(60)} for ix in range(60)};d1=dict(self.db.bigdict);[d1[ix][iy] for ix in range(60) for iy in range(60)]
    Done (use self.msg() if you want to catch output) (runtime ~ 94.2111 ms)
```
This version takes 91ms! The only difference is that before starting the readout-loop, I have extracted the dict from the Attribute into a temporary variable and converted it to a normal Python dict using `d1=dict(self.db.bigdict)`. I then loop over this temporary variable `d1` instead of the Attribute version.

So what is going on here? The first thing to note is what an `Attribute` is: It is a related table with a Foreign-relation to the Object in question. We cache this relation so you very quickly can get the Attribute(s) tied to a given object without more than the first lookup. However we *cannot* cache the *value* stored in that Attribute. We have to make sure this comes fresh from the database on every read. So when you loop over `self.db.bigdict[ix][iy]` in every iteration of a big loop, every call is making a database query for you (and maybe more than one).

Why is Evennia doing this? Consider if we *did* cache the value. Attributes support storing database-instances (like typeclass instances). These db-objects could sit anywhere in the dict, maybe deeply nested somewhere. Now assume some of those database object have been deleted from the database since last we accessed them in the Attribute. The *Python representation* of those deleted objects would be kept from being garbage-collected by their existence of our cached dict and we could still happily access them. It's *undefined* what would happen when trying to re-save them; they may be re-created or they could cause an exception depending on the state of the database. By re-loading the value on read (which, yes, means Evennia will have to loop over the dict, find all database-object serializations and fetch them from the database), we can be sure that we actually get a "real" representation of the current database state and deleted objects will become `None` in the dict. 

The ability to do `obj.db.mydict[ix][iy]` is a convenience to the user accomplished by wrapping the normal Python dict in a special Evennia version we call a `_SaverDict`. This writes/loads from the database as you edit it, as described in [Retrieving Mutable objects](https://github.com/evennia/evennia/wiki/Attributes#retrieving-mutable-objects) from the Attributes documentation. The way to turn this off is to "disconnect" the dict from the database, simply by converting it back to a normal dict with the `dict(...)` function. When you've done that you are operating solely on the current state of the Python structure and Evennia will no longer care about updating/fetching the database state on every change/read. If your intent was to update said dict in the database you just need to re-assign it to the Attribute afterwards, using `self.db.bigdict = updated_version_of_dict`.

So this is not a bug but a well known behavior of Attributes. I'll add a more verbose mention of what happens on load to the documentation though. Closing.

**Closed by Griatch** 2018-03-24 09:26 UTC
