### ISSUE TITLE
Webclient refresh leads to many sessions

### ISSUE THREAD

**Issue by chainsol** [evennia/evennia#1562] opened 2018-01-30 17:15 UTC
#### Brief summary of issue / Description of requested feature:
On the current Develop branch, refreshing while logged in on the webclient opens another session.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Connect to an instance of Evennia, for instance https://ainneve.evennia.com
2. Login via the webclient
3. Refresh the page

#### Error output / Expected result of feature
You will end up in a new session, but also still connected to the previous session. I was able to keep this going indefinitely. Commands that message all connected sessions will repeat the message per session - try, for instance, `sessions`.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
This is on the latest develop branch, and doesn't seem to cause any other issues.

**Comment by chainsol** [comment] 2018-01-30 17:16
Of note: Ainneve is currently running on the latest develop branch with my webclient patches, but this issue happens on develop itself as well - my changes to the webclient are purely UI changes.

**Comment by BlauFeuer** [comment] 2018-01-30 17:24
I have no changes to the webclient, and I get the same.
After doing so, it looks like this in `@sessions` command:
```
Your current session(s):
+--------+-----------+---------------+------------------+------------+
| sessid | protocol  | host          | puppet/character | location   |
+~~~~~~~~+~~~~~~~~~~~+~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~+
| 32     | websocket | 195.93.194.80 | BlauFeuer        | Atmosphere |
| 33     | websocket | 195.93.194.80 | BlauFeuer        | Atmosphere |
| 34     | websocket | 195.93.194.80 | BlauFeuer        | Atmosphere |
| 35     | websocket | 195.93.194.80 | BlauFeuer        | Atmosphere |
| 36     | websocket | 195.93.194.80 | BlauFeuer        | Atmosphere |
+--------+-----------+-------------+--------------------+------------+
```

**Comment by chainsol** [comment] 2018-01-30 17:28
Oh, worth mentioning - Ainneve is in `MULTISESSION_MODE = 2`.

**Comment by Griatch** [comment] 2018-01-30 17:39
How very curious. I've tried to reproduce this with latest development and master locally, as well as  `MULTISESSION_MODE`s 0, 1, 2 and 3 using both Firefox and Chrome - and I cannot. I reload, I force-reload the browser - I get an ever-climbing session id, but only one at a time when I do `sessions`.

**Comment by chainsol** [comment] 2018-01-30 17:51
I'm running Chrome on Linux - not sure if that has anything to do with it?

**Comment by Griatch** [comment] 2018-01-30 19:10
After some experimenting it seems the issue appears with the combination of AJAX-webclient + MULTISESSION_MODE>0 and the Chrome browser. 
We also saw a case of the protocoll `.address` getting mixed up between the Sessions, something which reminds of #1517 - but when examining the sessions they are *not* the same; not only are they different in memory, everything on them is unique to that session except for the address string. This may suggest that the address mixup happens at the protocol level (in the Portal) and is somehow mixed up or mis-represented there. 
The duplicate session is most likely some sort of incompatibility between our AJAX implementation and Chrome, such as how to detect the window reloading/closing having changed somehow.

**Comment by Griatch** [comment] 2018-02-14 20:34
If we have some web dev around here who knows the ins and out of why a browser would behave differently with ajax, do chip in!

**Comment by Griatch** [comment] 2019-03-31 19:38
This is still an open issue it seems.

**Comment by Griatch** [comment] 2019-06-10 06:16
I can not reproduce this in `develop` branch at the moment, but that may be due to another bug, #1851 which has to be resolved before checking this one.

**Closed** 2019-06-29 16:49 UTC
Labels: bug, develop-branch, help wanted, implemented, master-branch, web
