### ISSUE TITLE
Reload Boots

### ISSUE THREAD

**Issue by Tirit** [evennia/evennia#1590] opened 2018-03-15 18:50 UTC
#### Brief summary of issue / Description of requested feature:
Upon reloading the server, people are getting rather booted or forced @OOC. 

#### Steps to reproduce the issue / Reasons for adding feature:
'evennia reload' from command line, or @reload and @reset from in the game. 
 

#### Error output / Expected result of feature
Only errors I'm getting I don't know if they're related or not. 

> /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'accounts.AccountDB'

> /home/evennia/pyenv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py:157: django.utils.deprecation.RemovedInDjango20Warning: use_for_related_fields is deprecated, instead set Meta.base_manager_name on 'objects.ObjectDB'

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Evennia 0.7.0 (rev b3e97b5) (rev b3e97b5)
    OS: posix
    Python: 2.7.12
    Twisted: 16.0.0
    Django: 1.11.11
    Evennia MUD/MUX/MU* development system

**Comment by chainsol** [comment] 2018-03-15 18:56
How are you running the game? This might happen due to the console being closed.

**Comment by Tirit** [comment] 2018-03-15 19:25
I'm running it through screen

**Comment by Griatch** [comment] 2018-03-15 19:28
Is this also happening to the superuser?

**Comment by Tirit** [comment] 2018-03-15 19:48
It happens to any user. I don't find a pattern.

**Comment by Griatch** [comment] 2018-03-15 20:35
@tirit: This does not happen on a clean Evennia install (just tried), so you need to start analyzing the components.

1. First, make really sure you don't see any errors, neither in the server.log and portal.log related to this.
2. Has this worked well since upgrading to, say Evennia 0.7? That is, is it something that just happened one day or is it something that only started after some Evennia upgrade? If the latter (especially if it's upgrading from 0.6 to 0.7) it's likely something that has changed (look at the Evennia changes reported in the forum and in the commit history). 
3. If you have overloaded the hooks called when the server reloads, check if you are doing something unexlected there. Since you say that "people go OOC", it could be something with your `at_unpuppet` hook, for example. Objects and Accounts have hooks `at_server_reload` too. Comment out your custom code, try to figure out what is happening. 
4. Check your MULTSESSION_MODE. If you are at a mode higher than 0, try temporarily switching to mode 0 to see if the problem persists.
5. If this is something that just started happening, try seeing what you last changed. If you have your game code under version control, try checking out an older revision of it to see if things work better. Alternatively revert to an older Evennia version to see the same.

**Comment by Tirit** [comment] 2018-03-15 20:48
1. I am getting an
>  [AMPProtocol,client] [EE] AMP Error for AdminPortal2Server: 'NoneType' object is not iterable
 in portal.log now that you mention it. 

2. The errors posted above started when I migrated to .7, I probably didn't recognize them because I wasn't as busy and I'm getting more traffic now. We've been programming a lot so it has included a lot of reloads, and people started saying how they were getting pushed to @OOC or being booted. It does seem to happen when there is more people on, then when it's just myself. 

3. Haven't developed a single `at_server_reload` in my custom code. 

4. MULTISESSSION_MODE was left as default, I'll hard set to 0 now.

**Comment by Griatch** [comment] 2018-03-15 21:01
@tirit: I suppose you have stopped the server fully and then started it again (just checking the basics) just to make sure sessions are cleaned.

MULTISESSION_MODE=0 is default so you don't need to set it explicitly in that case. 

It's hard to tell what could be the issue. 
1. Just to test, create a new game dir/database etc and check so the error is not present there. 
2. Then you could try to test locally with your 'real' game dir code but with a fresh database (just backup/move away the old one). This way you can see if the issue is with your code or with something in the migrated database.
3. It can be a little harder to use an 'old' database (use a backup!) with a 'fresh' game dir (since you are likely having typeclass-paths in the database not existing by default). But for testing the `@reload` functionality might be possible if you just comment out things enough to be able to connect - so you can see if you get kicked out also in that state.

**Comment by Tirit** [comment] 2018-03-15 21:08
Yeah, I think I would suspect a fresh install would be best.

**Comment by Griatch** [comment] 2018-03-15 21:09
A completely fresh install should not be needed - these things can always be fixed. But it's useful to test to see just where the error is introduced (code, database, combination of the two)

**Comment by TehomCD** [comment] 2018-03-16 21:20
You may want to update to python 2.7.13 or 2.7.14 - it's possible there may be some obscure bug in a slightly earlier version of 2.7, which has happened before.

I've seen the validation error before in nicks but I'm not really sure what causes it, aside from it looking like a tuple is being used rather than a string for key or replacement - probably a mistake I made in the AttributeForm. I don't think that'd be related to people losing their sessions though. That seems more likely to be something in sessions. Whenever there's an error with the AMP bridge where the portal and server lose their connection to one another, players usually are knocked OOC.

**Comment by busbyra** [comment] 2018-03-17 01:01
We have updated python to 2.7.14.  The warnings persist, but are here because the warning was introduced in version 1.9 of Django and is more or less a "Hey, update these areas before 2.0".  2.0 also probably implies us moving over to Python 3.x (please!  can't wait!). 

The pushing of my bit (I believe I was the only one on the game being pushed) to @ooc is something I assume Bremen can comment on as to how he fixed it.

**Comment by Griatch** [comment] 2018-03-17 06:40
@busbyra: Django deprecation warnings are unrelated to any issues in the game yes. As for the plan for Python3, see here: https://groups.google.com/forum/#!category-topic/evennia/evennia-news/GbLh1GF-ZaY

> The pushing of my bit (I believe I was the only one on the game being pushed) to @ooc is something I assume Bremen can comment on as to how he fixed it.

So this is solved now? Also, only one player seeing this effect is not how this issue is presented, I understood it happening to everyone randomly?

**Comment by Tirit** [comment] 2018-03-19 01:38
Maybe. We had an issue with the channels awhile back, where we put color in the names it seamed to screw them up. I found it by examining the bit on busbryra's account. It appears there was some trace back to those channels, so I reset those variables. I don't know if that really was what fixed it. I am still getting the traceback I posted 2 days ago from when I was playing with the web-admin interface. 

Again, not sure at this point what is related and what is not related.

**Comment by Griatch** [comment] 2018-03-19 09:13
@Tirit Ok: This doesn't come across as an Evennia issue I don't think, so I'm closing this. If you can reliably reproduce it and feel there is something we can fix on the Evennia side, comment here and I'll open this thread again. For now, closing.

**Closed by Griatch** 2018-03-19 09:13 UTC
