### ISSUE TITLE
[DEVEL][BUG] Help command fails to find some default commands and topics

### ISSUE THREAD

**Issue by awranthyr** [evennia/evennia#2587] opened 2021-11-20 16:33 UTC
#### Describe the bug
The `help <target>` command fails to properly find/display help for the default `say` and `who` commands (if searched for by key), and the `building` topic (and possibly others not yet tested).

#### To Reproduce
1. Log into a newly created game instance.
2. Use the `help say`, `help who`, or `help building` command (or list topics with `help` and then click the command/topic name).
3. See error(s)

#### Expected behavior
Help for these commands/topic(s) should be consistent with others.

#### Environment, Evennia version, OS etc
```
    Evennia 1.0-dev (rev ffd6da2c5) (rev ffd6da2c5)
    OS: posix
    Python: 3.9.7
    Twisted: 21.7.0
    Django: 3.2.3
```
#### Additional context
Help for `say` and `who` can be found by searching for their aliases such as `help '` or `help doing`.  The list returned by `help` used by itself also displays the keys for all of these commands/topics without issue.

Also, while playing around to see if I could find a quick fix to suggest for this issue (sadly, no such luck), I noticed that, contrary to the comments in `CmdHelp`, setting `suggestion_maxnum = 0`, rather than just disabling suggestions, completely prevents the `help` command from returning any matches at all.  Either the functioning of the variable or the comment about how it works may need altering.

**Comment by Griatch** [comment] 2021-12-22 19:34
I don't remember if I didn't already fix this, but the cause for this error is because the `Lunr` search engine (which is what we now use for help searching in develop) has a lexicon of 'words to exclude'. Since `Lunr` is built for website searching, it tries to ignore 'common, short words' that would make little sense to look for in a website's text, like `the`. Other such short words would be `who` and `say`. These need to be removed from the exclude list for our usage.

**Comment by The-Archemist** [comment] 2021-12-26 01:16
> I don't remember if I didn't already fix this, but the cause for this error is because the `Lunr` search engine (which is what we now use for help searching in develop) has a lexicon of 'words to exclude'. Since `Lunr` is built for website searching, it tries to ignore 'common, short words' that would make little sense to look for in a website's text, like `the`. Other such short words would be `who` and `say`. These need to be removed from the exclude list for our usage.

Tested as of December 25th, 2021. `help say` and `help who` still do not correctly function. Screenshot included for reference.
![image](https://user-images.githubusercontent.com/73198594/147396472-f36db38b-faad-402c-bc9a-b151defc4528.png)

**Comment by Griatch** [comment] 2022-03-01 21:23
`help say` and `help who` does work in develop now. Closing.

**Closed by Griatch** 2022-03-01 21:23 UTC
Labels: bug
