### ISSUE TITLE
[BUG] Lockfuncs - Better handling of cases where `accessing_obj` is a Command instance

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#2227] opened 2020-10-11 21:38 UTC
#### Describe the bug
(Continuation of #1618; this really is starting to deviate from the scope of the original ticket.)

A side-issue arose from my observation that locks are not being consistently checked on the appropriate object for quelled users-- in some cases the locks are checked using the instance of the Command as the `accessing_obj`, instead of the actual caller or Object.

Given the following container Object and some commands to enter and leave it, `Enter` will always work (albeit incorrectly, since you can recursively enter the same object) and `Exit` is never added to the usable cmdset:

```
class CmdEnter(Command):
    
    key = 'enter'
    locks = 'cmd:not inside()'
    
    def func(self):
        self.msg("You enter.")
        self.caller.move_to(self.obj)
    
class CmdExit(Command):
    
    key = 'exit'
    locks = 'cmd:inside()'
    
    def func(self):
        self.msg("You leave.")
        self.caller.move_to(self.obj.location)

class ContainerCmdSet(CmdSet):
    
    key = "Container"

    def at_cmdset_creation(self):
        self.add(CmdEnter())
        self.add(CmdExit())

class Container(Object):
    
    def at_object_creation(self):
        super().at_object_creation()
        self.cmdset.add(ContainerCmdSet(), permanent=True)
```

Errors are raised in the log concerning the absence of a srcobj when the commands are invoked. Superusers simply bypass this and the lock-checking altogether.

```
20-10-06 23:27:08 [EE] objects.container#581: 'NoneType' object has no attribute 'access'
20-10-06 23:27:10 [EE] objects.room#108: 'NoneType' object has no attribute 'access'
```

In this case, the commands are being added to the usable command set based on whether `CmdExit` itself is inside the container-- instead of the caller.

To work around this, I redefined the `inside` lockfunc and added a check to look for delegate objects:

```
def inside(accessing_obj, accessed_obj, *args, **kwargs):
    """
    Usage:
       inside()
    Only true if accessing_obj is "inside" accessed_obj
    """
    if inherits_from(accessed_obj, 'evennia.commands.command.Command'):
        accessed_obj = getattr(accessed_obj, 'obj', accessed_obj)
            
    return accessing_obj.location == accessed_obj
```

And after looking at the code for other functions, other lockfuncs perform similar checks, though inconsistently:

https://github.com/evennia/evennia/blob/ea6f245f56b9b2b3bed7b588dd83650a529f0efd/evennia/locks/lockfuncs.py#L515-L530

https://github.com/evennia/evennia/blob/ea6f245f56b9b2b3bed7b588dd83650a529f0efd/evennia/locks/lockfuncs.py#L533-L544

Both functions deal with tag checking-- but notice that the check performed on L526-L527 is missing from the latter function (and most other functions as well).

#### Expected behavior
Seems like it would make more sense that all lockfuncs should check for `accessing_obj.obj` attribute by default and use that in place of `accessing_obj`. Trying to address this in every lockfunc currently implemented would leave all custom locks susceptible to the same bug.

#### Additional context
I think the best place to enforce this is here:

https://github.com/evennia/evennia/blob/ea6f245f56b9b2b3bed7b588dd83650a529f0efd/evennia/locks/lockhandler.py#L573-L585

Perhaps add a step that automatically replaces `accessing_obj` with `accessing_obj.obj` if available?

**Comment by strikaco** [comment] 2020-10-11 23:08
> Perhaps add a step that automatically replaces accessing_obj with accessing_obj.obj if available?

After messing around with this for a bit, one area this will cause issues is with Scripts. My proposed solution would make Scripts ineligible as values for any lockfunc.

**Comment by Griatch** [comment] 2020-10-12 17:41
We don't want to exclude Scripts or any typeclasses. Commands are really the odd ones out here, but the problem is that we can't generalize how they are handled either - a `perm` check used against the Command itself, not against its `.obj`, for example. This is something that must be handled per-lockfunc. With your merged PR, a buggy edge case was fixed. Similar need to happen if more are found. Closing this now.

**Closed by Griatch** 2020-10-12 17:41 UTC
Labels: bug

**Comment by strikaco** [comment] 2020-10-14 15:36
> We don't want to exclude Scripts or any typeclasses. Commands are really the odd ones out here, but the problem is that we can't generalize how they are handled either - a `perm` check used against the Command itself, not against its `.obj`, for example. This is something that must be handled per-lockfunc. With your merged PR, a buggy edge case was fixed. Similar need to happen if more are found. Closing this now.

@Griatch I agree with you, but someone else who worked on this code felt otherwise ;)

https://github.com/evennia/evennia/blob/3815bc72e96012a714448b9827b5bc7930234c2d/evennia/locks/lockfuncs.py#L377-L381

**Comment by Griatch** [comment] 2020-10-14 15:46
@strikaco The issue with Scripts "masquerading" as Commands is known. But your suggestion was to make the script _ineligible_ to pass as value to a lockfunc, which is what I answered no to. 
The comment in the code (which is specific to `attrs`) refers to the fact that it should hopefully be rare to want to target the script object itself over the thing it is attached to. But should there ever be such a need, a custom lockfunc would need to be added, and pre-assuming that `.obj` is always the target if it exists (by adding a pre-check in `_eval_access_type`) would exclude or at least complicate that possibility.
