### ISSUE TITLE
Batchcode doesn't appreciate utf-8 encoding in files

### ISSUE THREAD

**Issue by vincent-lg** [evennia/evennia#1575] opened 2018-02-25 11:14 UTC
#### Brief summary of issue / Description of requested feature:

When inserting special characters in utf-8 in a file that will be read by the batchcode parser, these characters are misinterpreted and stored inaccurately.

#### Steps to reproduce the issue / Reasons for adding feature:

1. Create a batchcode file, not forgetting to put `# -*- coding: utf-8 -*-` in the header.
2. Put some text with special characters (see demo below), making sure your editor is saving in utf-8.
3. Apply the batchcode.  The batchcode is applied but the characters are not stored properly in utf-8.

#### Demo file

```# -*- coding: utf-8 -*-

#HEADER

from typeclasses.rooms import Room
center = Room.objects.get(id=2)

#CODE

center.db.desc = "voilà"
```

#### Error output / Expected result of feature

The fifth character of the room description in this demonstration file isn't stored as proper encoding and will not be sent properly to clients afterward.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

* Evennia: develop.

**Comment by Griatch** [comment] 2018-02-26 18:21
@vlegoff I can't reproduce this. I tested your very example (also without the `# -*- coding: utf-8 -*-` header, it shouldn't be needed). I set the desc on myself and when I later look at myself (or use examine) I correctly see `voilá`. I also tried with some Swedish character with the same result. So this might maybe not be an Evennia issue but something with the terminal/client seeing the output?

**Comment by vlegoff** [comment] 2018-02-26 19:15
Hm, perhaps a combination of factors, since I was on the website but I changed encoding to latin-1 (though  it shouldn't affect the website). I'll try again.

**Comment by BlauFeuer** [comment] 2018-02-26 19:22
Switching to latin-1 encoding in options while using the webclient would be problematic.

**Comment by vlegoff** [comment] 2018-02-28 08:31
I'm not sure if it's a problem with the `@batchcod` utility at all, or even if it's a problem, but here's what I get.  Perhaps this issue should be simply closed, but if you can explain me the results, it might help!

I changed the default encoding in my settings:

```python
# Language options
USE_I18N = True
LANGUAGE_CODE = 'fr'
ENCODINGS = ["latin-1", "utf-8", "ISO-8859-1"]
```

The last setting will force the default encoding to be latin-1.  That applies to new Telnet clients (except for the webclient that hopefully overrides it to use utf-8).

I then examined the data stored in the database.  I expected it to remain in utf-8, which, for me, would have been good (I just want the Telnet output to be latin-1 by default, but I prefer utf-8 and I would appreciate it if all French users had it properly setup).  In the database, to my great surprise, it seems room descriptions for instance are stored in latin-1, not utf-8.  The byte strings look like this: `u'b\xe9ton'`, whereas utf-8 would spread the é on two bytes: `u'b\xc3\xa9ton'`.  That being said, perhaps I'm wrong and the data is indeed stored in utf-8 in the database.

Regardless, with batchcode processing a file: it seems in my case, should the file contain special characters, the file should be in latin-1 because it's my default output encoding.  I tried both.  I'm not exactly certain why, all I know is both my Telnet client (using latin-1) and the webclient (using utf-8) complain if the batchcode is in utf-8.

It's not a problem, really: I can change encoding just for batchcode files.  I'm just curious about why it is necessary.  Do you know, most importantly, if data is stored in utf-8 even when changing the default encoding, and if changing the default encoding affects batchcode processing?

Thanks!

**Comment by vlegoff** [comment] 2018-03-01 09:52
I found the issue and it's not really an issue, but I'll let you decide: the batch processor uses the default encodings as it should, in the order they have been placed.  Since I changed the said order, it means 'latin-1' is attempted before 'utf-8'.  And 'latin-1' can decode the UTF-8 file, though it will display a lot of nonsense.  So... on the one hand we're told to ALWAYS keep utf-8 as the first encoding.  On the other hand, I had to change the order to offer a different default encoding.  It's not a bug and it's a consistent choice but might be enhanced in some ways.  Still, it's your decision.

**Comment by vlegoff** [comment] 2018-03-01 10:47
I'm sorry, my last question was confusing and not really well-defined.  The database doesn't store "bytes" in its strings it seems, but the unicode if I understood properly (what Python 2 displays as `u"string"`).  I just have to remind myself that the batchcode files will be decoded using the first encoding in the settings (latin-1 in my case).  The rest of my code (including my special characters in messages) is in utf-8.  It's just (very slightly) confusing, but I can have my code files in utf-8 and batchcode files in latin-1.  I suppose this is a very infrequent situation, so I guess you can close that issue.

**Comment by Griatch** [comment] 2018-03-01 13:31
@vlegoff The database stores unicode yes. Sorry, I use utf-8 and unicode interchangeably sometimes. These things will hopefully be a little clearer when we move to py3. Do you think the docs should updated to reflect your case? If you have the time, maybe you have some idea of how to best explain it?

**Comment by vlegoff** [comment] 2018-03-01 13:57
Perhaps I could add a short note on the wiki page.  I don't think it deserves much more than that, most people just keep utf-8 as the first encoding in their setting if indeed they change it at all.

**Comment by Griatch** [comment] 2019-03-30 22:19
@vincent-lg I'm closing this; I can reproduce even less in py3. Let me know if the issue reappears.

**Closed by Griatch** 2019-03-30 22:19 UTC
Labels: bug, master-branch
