### ISSUE TITLE
[BUG] contrib: rpmodule force-capitalizes nicks

### ISSUE THREAD

**Issue by Oreolek** [evennia/evennia#3072] opened 2023-01-07 07:05 UTC
#### Describe the bug
After installing rpmodule, all `sdesc` nicks are capitalized unless they start with a color code.

#### Expected behavior
Do not change the nick or `sdesc` capitalization

#### Environment, Evennia version, OS etc
Evennia version: 1.0.2, python: 3.10.6

**Comment by InspectorCaracal** [comment] 2023-01-07 07:17
Could you give an example of the reference that's being used which results in the sdesc being capitalized? It should only capitalize it if the reference is also capitalized (e.g. /Me has the first letter capitalized and should output the sdesc the same way, but /me does not and should not.)

**Comment by Oreolek** [comment] 2023-01-07 07:33
(as guest1)
```
> sdesc lowercase
> say hi
guest says, "hi"
````

(as another player in same room)
```
Lowercase says, "hi"
```

**Comment by InspectorCaracal** [comment] 2023-01-07 07:38
This is working as intended; the at_pre_say hook that adds the "says" part uses initial capitalization, `/Me`

You can customize this with overloading hooks on your own class if you like or by modifying the commands to pass `case_sensitive=False` to `send_emote` to disable the auto-capitalizing function.

**Comment by Oreolek** [comment] 2023-01-07 07:49
btw, the capitalization doesn't work if the name starts with a special symbol, like a color code. But that's another matter.

**Comment by InspectorCaracal** [comment] 2023-01-07 07:50
> btw, the capitalization doesn't work if the name starts with a special symbol, like a color code. But that's another matter.

Yeah, the rpsystem doesn't currently support color codes in names at all.

**Comment by Griatch** [comment] 2023-01-07 09:20
This doesn't appear to be a bug, so closing.

**Closed by Griatch** 2023-01-07 09:20 UTC
Labels: bug, needs-triage
