### ISSUE TITLE
[BUG] Changes that require Shutdown and not Reload

### ISSUE THREAD

**Issue by TehFamine** [evennia/evennia#2159] opened 2020-07-06 17:12 UTC
#### Describe the bug
When editing one of the contributor modules located in evennia\evennia\contrib\rpsystem.py I ran into an issue where I had to shutdown the game and execute 'evennia start' to see a change I made. When removing the change, I could reload and see the change removed. But, if I tried to add back in the change and do another reload, the change would not show until I shutdown.

#### To Reproduce
1. Add the rpsystem.py module to your objects, rooms, character type classes.
2. Create a new typeclass for rooms called ChargenRoom that inherits ContribRPRoom.
3. dig a new room with the ChargenRoom typeclass
4. Teleport to that room
5. Note the room name and the object # number
6. Open rpsystem.py located in the contrib directory. Find def get_display_name()
7. Change idstr = "(#%s)" to idstr = "(1#%s)" in def get_display_name()
8. Reload the game
9. Note the change does not show.
10. Shutdown the game.
11. Execute evennia start within the game folder and in the console
12. Note the change now shows as (1# your room id)
13. Change idstr = "(1#%s)" back to idstr = "(#%s)"
14. Reload the game.
15. Note the change now shows as (# your room id)
16. Change idstr = "(#%s)" to idstr = "(1#%s)" in def get_display_name() again
17. Reload the game.
18. Note the change DOES NOT show
19. Repeat the steps to shutdown, evennia start again.
20. Note the change now shows as (1# your room id)

#### Expected behavior
I would expect the moment I changed get_display_name() that any reload would work. I shouldn't have to shutdown. I also wouldn't expect that after the game was started, that removing the change and then reloading would remove the change. Logically, I should have to shutdown again if you follow the pattern. But you don't. Yet, if you add the change back, reloading does not work. It's extremely odd.

#### Environment, Evennia version, OS etc
Windows 10, 64-bit, Intel i7 processor, PyCharm IDE

    Evennia 0.9.0 (rev ff11fbd8) (rev ff11fbd8)
    OS: nt
    Python: 3.7.4
    Twisted: 19.10.0
    Django: 2.2.13

**Comment by Griatch** [comment] 2020-07-18 19:46
@TehFamine I can't reproduce this. If I follow your instructions to make me a `ContribRPRooom` and then edit `ContribRPObject.get_display_name`, followed by `reload`, I see the change in the room's key(dbref) display immediately. Do you still see this effect?

**Comment by Griatch** [comment] 2020-09-03 06:44
Since there was no follow up to this, I'm closing as non-reproducible.

**Closed by Griatch** 2020-09-03 06:44 UTC
Labels: bug, more info needed

**Comment by strikaco** [comment] 2020-10-11 22:45
There is something to this, though I have no idea how to reproduce it-- I have an entirely different set of variables in play. When trying to edit the core codebase in a new git branch (same virtualenv I've been using for the last year on a Ubuntu Linux 16 box), none of my changes were being detected **at all**.

Pip has been upgraded a few times though, current is `pip 20.2.3`.

Eventually I got frustrated enough to try a `pip install -e evennia` altogether. After reinstalling, my changes are being detected properly after reloads, even across git branches. Maybe some sort of stale cache issue?

**Comment by pruuk** [comment] 2021-08-19 01:31
I've seen this bug show up a few times as well. In my case, it happened when I was doing a bunch of quick formatting changes to my character sheet and reloading quite a few times in a row in a short period of time.
