### ISSUE TITLE
Feature Request: automatic sdesc articles in rpsystem contrib

### ISSUE THREAD

**Issue by feend78** [evennia/evennia#1028] opened 2016-08-30 18:37 UTC
#### Brief summary of issue / Description of requested feature:

Currently, the `rpsystem` contrib module allows us to set an `sdesc` on an object. In Ainneve, we have been setting our sdescs to "a brown, tired-looking rat", with the "a" hard-coded into the object's sdesc.

It would be handy if sdescs could be modified so that they could be set without "a", "an", or "the" at the start, and have the sdesc handler or other rpsystem commands automatically handle adding the proper article (and possibly capitalization, as spotted in a request on the google group).

#### Steps to reproduce the issue / Reasons for adding feature:

1. More grammatically correct messaging from the rpsystem module.

#### Error output / Expected result of feature

Something like:

```:python
@spawn 'RAT'
@py rat = me.search('rat');rat.sdesc.add('brown rat'); rat.execute_cmd('say squeak')

# In-game, other characters would see:
A brown rat says, "squeak"
```

**Comment by BlauFeuer** [comment] 2016-08-31 07:35
What could be more grammatically correct than the article you supplied when you set the object's sdesc? Perhaps you want

**Comment by Griatch** [comment] 2016-08-31 21:34
A problem that comes to mind with a dynamic allocation of a/an is that since the original sdesc does not contain the a/an, using the prefix in a search becomes invalid. So someone writing their reference as `/a tall man` will not match `tall man` the way the code is written now. 

Now, I can solve this by adding regex exceptions that make a/an/the optional at the beginning of the sdesc, but it's a complication I had not considered, making this less of a quick addition than expected.

**Comment by stefanludlow** [comment] 2016-08-31 22:03
Just use a special character to represent the a/an? I don't think that will solve the below, but I think the moment someone tries to do a/an {} replacement in the longer description this will be needed. Variables with variable articles will be elsewhere than just the first word of a simple sdesc, in my estimate.

**Comment by Griatch** [comment] 2016-08-31 22:21
@stefanludlow

I don't quite follow what you mean. Where would that special character be used? Internally? Or should one use a custom character when creating the sdesc?

Also,
>  Variables with variable articles will be elsewhere than just the first word of a simple sdesc, in my estimate.

Could you elaborate on this? If the goal is to support multiple, arbitrary grammatical replacements this is quite a different issue than the one presented here.

**Comment by BlauFeuer** [comment] 2016-09-01 06:11
@feend78 I'm not sure why the specific need for the a/an article to be auto-added when the human can do that.  What you gain by enforcing a mandatory article is more complication and loss of flexibility for the inclusion of foreign articles (La rata marrón, Die braune Ratte), or lack of an article (Brown rat), or simply "the" as an article (The brown rat). Such an enhancement to avoid "hard coding" takes the choice away from us and enforces a game-specific rule or game-language-specific limit of "a or an" as the only options for a mandatory article.  Just capitalize the first word of the sdesc when displaying it as the first part of a sentence and that will probably fulfill most of the need without being overly game-specific.  

Perhaps you can "feature up" Ainneve with the mandatory auto-article "a" or "an" on all objects with an sdesc, in fact, why stop there?  Let's imagine a more game-specific construction of a relational preposition and gerund that expresses how any given character relates to the object, and auto-construct an English sentence:

@stefanludlow If this _had_ to be done, then storing the object's default article in another attribute is probably the best way to deal with it for use in other circumstances.  In fact, I do this for rooms where people tend to want prepositions, as well.  "In the river of life", "On a library shelf", "Behind an apple tree" would store `in`, `on` and `behind` on its room object as the preposition, and `the`, `a` and `an` as the articles - the room names would just be "river of life", "library shelf" and "apple tree" - thus if someone's location is being reported, it involves the room's preposition and article.  If the character wishes to be positioned within the room in a way similar to the RP System's room pose, then a gerund stored on the character and selected by the player is also added - thus you have "Swimming in the river of life", "Sitting on a library shelf", "Hiding behind an apple tree" - all that's left is to append "<character> is" for a valid sentence.

**Comment by feend78** [comment] 2016-09-01 16:11
@BlauFeuer, I appreciate your arguments against this feature request. However, I don't really have strong opinions on it. I essentially forwarded the request which was initially created as an Issue for Ainneve by @stefanludlow, 

Griatch suggested it would be better as a feature request against the contrib in Evennia than in Ainneve. 

If it's decided that this isn't something to pursue, I'm fine with that. It is an interesting idea, but not central to the Ainneve implementation. I imagine, as we build more and start to have folks building more and more content and actually "playing" the game, that it will become clear whether this type of feature would be useful or necessary.

**Comment by BlauFeuer** [comment] 2016-09-01 16:26
I think it's a cool feature, and I think the main issue is "should emote capitalize the anonymous emotes" (they lead with the emoter's sdesc), and I am arguing for it. 

I'd even argue for separating the article out for Evennia, much less Ainneve, because then the object's name is its name, and the object's article is whatever the article is set as, etc.

What I'm arguing against is some scheme where the article for an object is determined by an algorithm instead of the person creating or editing the object.   If an article isn't supplied, either as part of the sdesc or as part of another attribute for articles, then the least surprise would be that the name was displayed with what information was given, language independent,

I just turned on this RPSystem thing and users are getting used to it; of course I'd love to see it extended, but I think setting the article for the object for us as a feature is actually taking away some control from us.

**Comment by Griatch** [comment] 2016-09-01 16:48
@BlauFeuer et al.

I see this feature working in the following way: 

Assume these possible sdescs:

A. *tall man*
B. *a tall man* (explicit a)

Here are some alternative emotes and how I figure this would operate under the hood:

1. `emote /me looks at /tall and smiles. -> Griatch looks at a tall man and smiles.`. In the case of A), this happens because of the automatic algorithm, in the case of B) because the system recognizes the prefix being put explicitly and just leaves it be (so if it had been *the*, *an* or *a* it would not do anything). This is the only case an automatic algorithm is used.
2. `emote /me looks at a /tall and smiles. -> Griatch looks at a tall man and smiles.`. Same outcome, but here the system notices that `a` is given explicitly in the emote and will not add it in the case of A) and strip it out in the case of B). If one entered "an" here, the system would buy that and allow the wrong grammar.
3. `emote /me looks at the /tall and smiles. -> Griatch looks at the tall man and smiles.`. In this case, the system recognizes "the" preceeding the desc and will use that explicitly in the case of A) and by stripping the article in the case of B) - "the a tall man" looks ugly after all. 
4. `emote /me looks at /Tom and smiles. -> Griatch looks at Tom the carpenter and smiles.` This is the case of a recog being invoked. A recog string is assumed to be specific to a given person (a proper noun) and no clever replacements are done - if one wanted an article one would need to put it explicitly (like recog:ing as "The Carpenter").

How does that sound?

I agree this is making things more English-focused, but the commands are English as it is, and it's not too hard to make this replacement a function that could easily be overloaded by someone wanting another behavior.
.
Griatch

**Comment by BlauFeuer** [comment] 2016-09-01 17:03
Oh, the issue is that people writing emotes are supplying an article?  Emoting `the /tall`  assumes "tall man" or "a tall man" is "the" tall man, e.g. the only tall man, or the only tall man in the room.

I thought the issue was "More grammatically correct messaging from the rpsystem module."  What you're actually talking about is trying to make the emote text that was supplied more grammatically correct. 

If "the a tall man" looks ugly, then A) don't emote with a "the" or B) set the sdesc for "a tall man"  to just "tall man" - after all, the person emoting does see the sdescs in the room and should emote accordingly.

Yes, I'd still rather see the sdesc as-is without auto-article, unless the article was explicitly given in an attribute.  

The fact that the sentence doesn't begin with a capital letter is much more obvious a consideration, and much more universal.

**Comment by andrei-pmbcn** [comment] 2016-09-01 17:10
On the possibility of using this idea in emotes: I know that in the games that use the Dark Isles codebase, they do not put an article explicitly in object names, so that when you emote "@ eats #apple", and apple points to an object named "shiny red apple", you would get "John eats shiny red apple". There is a reason for this: sometimes you want to write "@ eats his #apple", sometimes "@ eats the last remaining #apple", and sometimes "@ eats that #apple", based on personal preference. Forcing an article into the name, either because it was hard-written into the name or because the code put it in, would take away from the player's literary freedom when using shorthand refences to objects in their emotes.

Character names are a different matter: it ~has~ to be "a tall man" from the start, because when people use recog, they replace the full "a tall man" with "John". You can't write "the /tall", because people who have recogged /tall as /John will see "the John".

Implementing coded articles the way Dark Isles does it, i.e. automatically adding the "a/an" at the beginning of an object's description when players use certain commands like "look" but not when they emote, seems useful. One particular place where MUD coders would want to take advantage of it is in the echo to the "get" command: when a container has multiple instances of the same object, say 5 berries, the echo could be "you get a berry" when you get berries 1 to 4, then when you get the 5th and final berry, the echo could be "you get the berry". This would notify you that you have gotten the only berry remaining in the container and that any further uses of the "get" command would fail. It would be a nice way of giving feedback.

**Comment by BlauFeuer** [comment] 2016-09-01 17:15
@andrei-pmbcn  Well written.  I'm not against a/an (or supplied articles in the given language) being used for constructing grammatically correct messages; I'm just against it altering the text I supplied as a emote.

It's kinda like fighting with auto-correct; I'd rather just turn it off and eventually learn to type better.

**Comment by Griatch** [comment] 2016-09-01 17:18
> Character names are a different matter: it ~has~ to be "a tall man" from the start, because when people use recog, they replace the full "a tall man" with "John". You can't write "the /tall", because people who have recogged /tall as /John will see "the John".

This is a fair point. Integrating with containers and piles is something up to each implementation, it's not something to add to the rpsystem contrib. 

So "capitalization of the sdesc if used at the beginning of an emote" seems to be the only thing people actually want? Well, less work for me.

**Comment by Griatch** [comment] 2016-09-01 17:23
So if this is the way to go for most flexibility, maybe the sdesc command should actively block the use of a/an/the as the beginning of sdescs (or at least give a warning)?

**Comment by Griatch** [comment] 2016-09-01 20:15
So, after clarification in IRC, the original reason for this request had more to do with the generation of sdescs in the prototype than anything that should be handled by the rpsystem. Closing.

**Closed by Griatch** 2016-09-01 20:15 UTC
Labels: feature-request
