### ISSUE TITLE
[BUG] Stacking RPSystemCmdSet in Stored Commands for Characters

### ISSUE THREAD

**Issue by DianaPeterson** [evennia/evennia#3452] opened 2024-03-28 22:38 UTC
When updating a character that inherits the RPSystemCmdSet, this stacks up endlessly in the Stored Commands.

1. Update a character inheriting this command set
2. Examine character and look at the Stored Commands list

It should only have one instance of the most recent updated RP command set

Evennia 4.0.0, using the RP system.

![image](https://github.com/evennia/evennia/assets/25781556/46f1817b-38dc-4d97-a1c9-b7cc1f1a5611)

**Comment by Griatch** [comment] 2024-04-01 09:17
When you say 'update', is this literally the `update <char>` command in-game? 
I have tested to name the RPSystemCmdSet to see if that helps.

**Comment by Griatch** [comment] 2024-10-23 18:57
Couldn't reproduce this, and no further replies from the ticket creator. Closing. Feel free to ping again and we can reopen if the issue still remains.

**Closed by Griatch** 2024-10-23 18:57 UTC
Labels: bug, more info needed
