### ISSUE TITLE
[BUG - Develop] Deleted script being restarted

### ISSUE THREAD

**Issue by owllex** [evennia/evennia#2645] opened 2022-02-09 21:41 UTC
#### Describe the bug

I've encountered several situations where a script that stops and deletes itself somehow manages to get automatically restarted and have its `at_start()` and `is_valid()` methods called. As it's been deleted, it's likely to raise an exception if code in those functions checks any attributes (very likely).

#### To Reproduce

The following test case demonstrates the error.

```py
from evennia.utils.test_resources import EvenniaTest
from evennia.utils.create import create_script

class DegenerateScript(Script):
    def at_script_creation(self):
        super().at_script_creation()
        self.repeats = 0
        self.interval = 1
        self.persistent = True
        self.start_delay = False
        print("Creating script")

    def at_stop(self):
        print("at_stop")
        self.delete(stop_task=False)
        print("deleted")

    def at_start(self):
        print("at_start")
        # logic...
        if self._is_deleted:
            raise AttributeError()

    def is_valid(self):
        # Auto-stop as soon as it starts.
        return not self.is_active

    def at_repeat(self, **kwargs):
        # Reset wait interval if necessary.
        self.interval = 1
        self.resolve()

class TestDegenerateScript(EvenniaTest):
    def test(self):
        script = create_script(DegenerateScript, obj=self.char1, autostart=False)
        self.assertTrue(script.is_valid())
        script.start()
```

1. Put above code into a test file.
2. Run the above test case
3. Observe output log print sequence:
```
Creating script
at_stop
deleted
at_start
```
4. Observe test failure with exception `AttributeError`, manually raised in `at_start()` after deletion. The `self._is_deleted` check is a stand-in for script-specific logic, as attempting to access a script attribute raises (for example): `django.core.exceptions.ObjectDoesNotExist: Cannot access db_is_active: Hosting object was already deleted.`

#### Expected behavior

`at_start()` is not called after deletion.

#### Develop-branch commit

    Evennia 1.0-dev (rev c2f4f8568) (rev c2f4f8568)
    OS: posix
    Python: 3.10.2
    Twisted: 21.7.0
    Django: 4.0.2

#### Additional context

The situation presented by this test case is admittedly a little contrived. The script stops itself immediately as soon as it starts. But this edge case I think might point to a bigger problem with start/stop handling as I see a similar flavor of problem even if the script repeats itself a few times before stopping (but it's harder to capture in a test).

**Comment by Griatch** [comment] 2022-09-22 20:32
@owllex I cannot reproduce your issue. I run the unittest and code provided in this issue and get an OK result from the test. Possibly other changes to the Script logic has resolved this. Could you check if this now works for you?

**Comment by Griatch** [comment] 2022-10-13 21:25
@owllex Ping? Or should I close this?

**Comment by owllex** [comment] 2022-10-14 02:26
I can't repro anymore either. I suspect it was fixed as a side effect of another change. Feel free to close.

**Closed** 2022-10-14 06:13 UTC
Labels: bug, branch-develop, more info needed
