### ISSUE TITLE
[Documentation] Documentation search is unusable in Firefox Mobile

### ISSUE THREAD

**Issue by InspectorCaracal** [evennia/evennia#2741] opened 2022-05-17 17:16 UTC
#### Documentation issue
The Mobile view rendering of the search results page is effectively unusable, for both versions of the documentation. (I assume they use the same site framework.) I don't have any other mobile browsers available to test if this is specific to Firefox or a general mobile layout issue.

![Screenshot_20220517-110600](https://user-images.githubusercontent.com/51038201/168872117-32aec089-731b-49ca-8b1b-f96ffc780ed1.png)

Also, while non-search pages are legible and look normal, the menu sidebar that's normally on the left in desktop view is just _gone_ in mobile view - so you can't e.g. switch between 1.0 and 0.9.5 or anything else that the link is only over there.

**Comment by Griatch** [comment] 2022-05-18 07:19
Seems to be reproducible for Chrome as well - it's only messed up for the search page, as you say.

Good point about the version swapper for mobile; the sidebar is hidden entirely for mobile, but while the search bar is moved to the top and TOC is not strictly necessary to have, the version swapper do need to be shifted.

**Comment by audiodude** [comment] 2022-10-03 02:34
From the [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/theming.html):

> Note that from these themes only the Alabaster and Scrolls themes are mobile-optimated, the other themes resort to horizontal scrolling if the screen is too narrow.

Any interest in switching to one of these themes? I can build example sites with them if it helps.

**Comment by audiodude** [comment] 2022-10-03 02:48
Okay just realized that `nature.css` exists in the `docs/source/_static` directory and contains a bunch of customizations, so I'm not sure it would be feasible to switch themes?

**Comment by audiodude** [comment] 2022-10-03 03:13
Looks like the search results were given `position: absolute` but confusingly, only when the screen size was under 960px. Removing this makes things generally better but not perfect. PR incoming.

**Comment by Griatch** [comment] 2022-10-06 21:21
Closed in #2894.

**Closed by Griatch** 2022-10-06 21:21 UTC
Labels: documentation, Hacktoberfest
