### ISSUE TITLE
Non-Room objects being counted as Rooms by `@objects` and web context

### ISSUE THREAD

**Issue by strikaco** [evennia/evennia#1845] opened 2019-05-17 18:26 UTC
#### Brief summary of issue / Description of requested feature:
Might be related to #251.

Objects that are not actual Rooms are being counted as such by the `@objects` command as well as the Django web context.

https://github.com/evennia/evennia/blob/5c521313d48ea7e5df72e8c1101d4ddcaae44a35/evennia/commands/default/system.py#L441-L442

https://github.com/evennia/evennia/blob/5c521313d48ea7e5df72e8c1101d4ddcaae44a35/evennia/web/website/views.py#L50-L51

This leads to very skewed object counts; intangible typeclassed "objects" such as economic/transaction handlers or temporary jobs/tasks are counted as Rooms.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
It looks like this happens because the aggregations assume Room objects are anything without a location on the grid. But in the case of intangibles, such objects do not require or use an on-grid location, yet they are classified as Rooms.

It might make more sense to count the number of Rooms as the number of all objects descended from DefaultRoom, or simply count the destinations of all Exit objects?

**Comment by Griatch** [comment] 2019-05-17 18:31
Intangibles should never be Objects. If they need a database existence they should be Scripts (which are like OOC Objects). 

But yeah, this logic is age-old, from a time before typeclasses, even. As you say, it assumes a 'room' is anything without a location. Using the DefaultRoom base would be more generally relevant today.

**Comment by Griatch** [comment] 2019-06-03 19:47
Fixed in develop branch

**Comment by strikaco** [comment] 2019-06-11 19:32
Thanks for the fix on this. 

The verbiage is now correct on the website, but the ingame `@objects` command raises a traceback for me due to an invalid date comparison. Not sure if related. Does it work for you?

````raceback (most recent call last):                        File "/home/ubuntu/workspace/evennia/evennia/             commands/cmdhandler.py", line 591, in _run_command      ret = cmd.func()
  File "/home/ubuntu/workspace/evennia/evennia/
    commands/default/system.py", line 472, in func
    latesttable.add_row(utils.datetime_format(obj.date_     created),                                             File "/home/ubuntu/workspace/evennia/evennia/utils/       utils.py", line 576, in datetime_format
    if dtobj.year < now.year:
AttributeError: 'str' object has no attribute 'year'
````

**Comment by Griatch** [comment] 2019-06-12 05:00
@strikaco Your traceback looks a bit cropped (it appears to be missing some part of the stack in the middle), but  `@objects` works for me. Maybe you could dig down to see if one object has gotten a weird datetime for some reason, maybe?

**Comment by strikaco** [comment] 2019-06-17 19:58
Odd, sorry. Here's a complete traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/evennia/evennia/commands/cmdhandler.py", line 591, in _run_command
    ret = cmd.func()
  File "/home/ubuntu/workspace/evennia/evennia/commands/default/system.py", line 472, in func
    latesttable.add_row(utils.datetime_format(obj.date_created),
  File "/home/ubuntu/workspace/evennia/evennia/utils/utils.py", line 576, in datetime_format
    if dtobj.year < now.year:
AttributeError: 'str' object has no attribute 'year'
```

**Comment by Griatch** [comment] 2019-06-18 17:01
@strikaco Still can't reproduce that, sorry.

**Comment by strikaco** [comment] 2019-06-18 18:04
> @strikaco Still can't reproduce that, sorry.
> Maybe you could dig down to see if one object has gotten a weird datetime for some reason, maybe?

```
19-06-18 17:43:32 [EE] Bad timestamp: 2019-06-19 18:40:23+00:00
19-06-18 17:43:32 [EE] Bad timestamp: 2019-06-19 12:27:38
```

There are quite a few of these; they were introduced by a database migration on my part.

Evennia accepted them as valid values despite being unable to parse/deserialize them. But that is really a separate issue; once I reset those times I could not reproduce the problem anymore either so #1845 is complete.

**Closed** 2019-06-29 16:49 UTC
Labels: bug, develop-branch, good first issue, implemented

**Comment by strikaco** [comment] 2019-07-02 21:10
>  If they need a database existence they should be Scripts (which are like OOC Objects). 

@Griatch I see your logic and am trying to refactor some of my code to follow it, but isn't using Script objects in this manner very risky? There are multiple non-obvious ways to accidentally trigger a lock-bypassing self-deletion of a Script object. Calling the base `stop()` function will do it, as will `start()` if `stop()` hasn't been explicitly overwritten, or if `is_valid()` returns False for any reason. There may be others I'm unaware of.

Objects aren't this volatile. Is there a better/meta class to inherit from that doesn't implement the full Script interface while also being off-grid? (Or should there be? Using plain Objects has been working for me without these concerns. The in-game manifestation of an economic engine could just as well be one or more "Server" or "Accountant" objects in a locked room somewhere, just like in real life...)

**Comment by Griatch** [comment] 2019-07-03 06:31
@strikaco: If you create a script without a timer component (for use as an "OOCObject" type), why would you ever start to mess with its `stop()` method? 

I have used Scripts extensively and never encountered a situation where they were "volatile" to the extent you describe. That said, the original purpose of Scripts were for time-keeping and over time their role has expanded since they are now typeclasses and there are other and probably better timer mechanism available (like the TickerHandler). So it makes sens to have their timer components more decoupled from their existence than today. There is a feature request (#1715) to change how Scripts work in order to make its stops and deletions fully explicit and decoupled.

**Comment by strikaco** [comment] 2019-07-04 19:48
Some of my objects in question coincidentally implement a "playable" interface via start() and stop() mixin methods. If I don't pay close attention to where those methods are getting inherited from and how super() gets called when inheriting from Script, I am concerned about what the default failure mode might become.

Good to know about the future plans for decoupling timing from Scripts. Generic Scripts without the timer/self-deletion mechanics would be very useful!

Thanks!
