### ISSUE TITLE
More than one match for '<object>': 4 matches listed for the same object

### ISSUE THREAD

**Issue by dmreichard** [evennia/evennia#1823] opened 2019-04-14 04:38 UTC
#### Brief summary of issue / Description of requested feature:
When attempting to look at an object by alias after it has been looked at using get_numbered_name(), the same object shows up 4 times on a multi-match string.

#### Steps to reproduce the issue / Reasons for adding feature:
For simplicity, I will create an object and add the aliases manually.

@create/drop utensil;a pencil;two pencils
You create a new Object: utensil (aliases: a pencil, two pencils).
look pencil
More than one match for 'pencil' (please narrow target):
 1-utensil(#3) [a pencil;a utensil(#3);one utensil(#3)s;two pencils]
 2-utensil(#3) [a pencil;a utensil(#3);one utensil(#3)s;two pencils]
 3-utensil(#3) [a pencil;a utensil(#3);one utensil(#3)s;two pencils]
 4-utensil(#3) [a pencil;a utensil(#3);one utensil(#3)s;two pencils]

####  Expected result of feature
This should work without showing a multi-match 4 times for the same object.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Running on Evennia 0.9.0-dev (rev 841b07fc)

**Comment by Griatch** [comment] 2019-06-03 16:29
Issue resolved in `develop branch`; will be fixed once it merges.

**Comment by thedandroid** [comment] 2019-06-06 00:08
I have a very similar problem still on the develop branch so I'm going to comment here, but if it's unrelated just let me know and I'll create a new issue.

Two identical objects in room: weapon rack;weapon;rack

```
You see: a stone column and two weapon racks
>look rack
More than one match for 'rack' (please narrow target):
 1-weapon rack [a weapon rack;rack;two weapon racks;weapon]
 2-weapon rack [a weapon rack;rack;two weapon racks;weapon]
 3-weapon rack [a weapon rack;rack;two weapon racks;weapon]
 4-weapon rack [a weapon rack;rack;two weapon racks;weapon]
```

It seems to be listing each item twice and I'm not sure why.

**Comment by chason** [comment] 2019-06-06 03:23
@thedandroid The issue seems to be fixed for me, can you give steps to reproduce? I tried reproducing with the following steps:
```
> @create/drop utensil;a pencil;two pencils
You create a new Object: utensil (aliases: a pencil, two pencils).
> @create/drop utensil;a pencil;two pencils
You create a new Object: utensil (aliases: a pencil, two pencils).
> l pencil
More than one match for 'pencil' (please narrow target):
 1-utensil(#84) [a pencil;two pencils]
 2-utensil(#85) [a pencil;two pencils]
```

**Comment by Griatch** [comment] 2019-06-07 07:04
@thedandroid Hm, i cannot reproduce that issue either (on `develop`): 

    > @create/drop weapon rack;weapon;rack
    You create a new Object: weapon rack (aliases: weapon, rack).

    > @create/drop weapon rack;weapon;rack
    You create a new Object: weapon rack (aliases: weapon, rack).

    > look rack 
    More than one match for 'rack' (please narrow target):
     1-weapon rack(#14) [rack;weapon]
     2-weapon rack(#15) [rack;weapon]

**Comment by thedandroid** [comment] 2019-06-07 16:29
Very strange, it must be on my end. I wonder if it has something to do with the rpsystem contrib, as I am using that. I'll have to take a look into it when I get home. Sorry for the false alarm!

**Comment by Griatch** [comment] 2019-06-08 14:18
@thedandroid For RPSystem, yes that's an important point. See this: https://github.com/evennia/evennia/issues/1757

**Closed** 2019-06-29 16:49 UTC
Labels: bug, develop-branch, implemented
