### ISSUE TITLE
Contrib: DefaultRPCharacter Search function not working for non-superusers

### ISSUE THREAD

**Issue by helix-0311** [evennia/evennia#987] opened 2016-05-31 22:14 UTC
This item is reproduced from the Ainneve issue tracker, item 69.

-------------------------------------------------------------------------------------------------------------------

https://github.com/evennia/ainneve/blob/master/commands/equip.py#L92

After initial character generation (with a purchase of equipment):

> equip lance
There is no 'lance' here.
You have nothing in your equipment.

>inv
You are carrying:
 a lance polearm  A sturdy wooden rod fitted with a menacing spike,   (Damage:  4)    
                  this lance polearm threatens even enemies at a                      
                  distance.  

                                                                                         
-------------------------------------------------------------------------------------------------------------------

When looking at the code, this seems to be the issue:

equip.py line 92:

    def func(self):
        caller = self.caller
        args = self.args.strip()
        swap = any(s.startswith('s') for s in self.switches)

        if hasattr(self, "item"):
            obj = self.item
            del self.item
        else:
            **obj = self.caller.search(args) if args else None**
-----------------------------------------------------------------------------------------------------

This else statement always seems to fire, but is not able to find anything in the character's inventory. Tested this (without full debug) by doing:

print args
print obj (after assignment, always None)
print caller
print caller.contents

This verifies that the args are as expected, the obj object is None, the caller is as expected, and the caller.contents contains the object that args should reference. Additionally, tested via the find command with the args string and was able to locate the object with no issue.

-------------------------------------------------------------------------------------------------------

Further debugging steps (takes place in Ainneve code):

Some additional testing of this item:

    def func(self):
        caller = self.caller
        args = self.args.strip()
        swap = any(s.startswith('s') for s in self.switches)

        obj = caller.search(args, location=caller)
        print type(caller.contents)
        stuff = caller.contents[0].aliases.all()
        if stuff.__contains__(args):
            print True
        else:
            print False

This evaluates to True in the console, making it appear that the caller.search() method is just not inspecting the aliases.

-------------------------------------------------------------------------------------------------------

https://github.com/evennia/evennia/blob/477391b5df650d06b358f1e8587813319a77d120/evennia/contrib/rpsystem.py#L1058

This appears to be the source of the issue.

Superusers are able to access the original search method, while non-superusers are unable to. Not sure the intended purpose of this block, as it would appear to block searches unless certain permission levels are met.

**Comment by Griatch** [comment] 2016-05-31 22:29
The reason for the search - permission check is because of the recog/sdesc system introduced in the rpsystem contrib. The contrib is based around the idea that all objects will have an sdesc and be searchable that way. 

If you however allow free access to the normal search whenever there is no match, then the sdesc system is pointless - for example say you have the "Masked Man" in the room, but you suspect that it's actually Tommy in a silly mask.
 If you then do "look Tommy", the sdesc-search will not match and will then move on to the normal search - which searches on `key` and will happily return Tommy's object (and description) if you guessed right - a meta way to bypass everything. So for this reason, the normal search is limited to Builders, who can peek at people's stats anyway. 

I suspect the problem here is that the Ainneve system does not define sdescs for its items. If that is not desired, then some sort of change is needed here. I'm open to suggestions, but at least that if statement is just where it needs to be as far as I can tell.

**Comment by feend78** [comment] 2016-06-01 01:17
I incorporated the rpsystem contrib functionality into Ainneve after the starter equipment had been created, and I missed this. @Griatch is right that sdescs need to be defined for Ainneve's items to fix this.

**Comment by Griatch** [comment] 2016-06-01 06:05
@feend

The need for item sdescs does produce a rather unexpected behavior if using the contrib with other objects. Regardless of how Ainneve resolves this I would be open to a simple PR that deactivates the permission check for objects without sdesc (so theur key would need to be used anyway).

**Comment by Griatch** [comment] 2016-06-01 22:38
@feend, @helix-0311 

I added a patch to the rpsystem contrib that should bypass the lock-check if it has candidate objects that lack an sdesc. You might still want to add sdescs to objects in Ainneve, but it would be great if you could check if this patch helps things in the interim since I don't have  Ainneve set up at the moment.

**Comment by feend78** [comment] 2016-06-01 23:11
@Griatch 

I grabbed your latest commit, and it doesn't seem to have solved the issue. With "a buckler" in inventory, I attempted to issue `equip a buckler` and I get the following:
```
Could not find 'a buckler'.
Could not find 'a buckler'.
You have nothing in your equipment.
```
Also, while my character's typeclass is correctly `typeclasses.characters.Character`, it appears that the rpsystem command `recog` is no longer available to me.

**Comment by Griatch** [comment] 2016-06-02 06:23
@feend78 

Oh, I know what the problem is I think ... if you have the buckler on the ground, will you find it then?

**Comment by feend78** [comment] 2016-06-02 14:02
@Griatch 

I believe I do... The output I get is
```
You don't have a buckler in your inventory.
```
Which is messaging from the equip command after an explicit check that the found object is in your inventory.

**Comment by Griatch** [comment] 2016-06-02 15:04
@feend78 

Not sure I follow - the equip command is irrelevant to core Evennia. If you use `@py` to access `self.search` and the buckler is on the ground, will the search mechanism find it or not?

**Comment by feend78** [comment] 2016-06-02 15:37
@Griatch 

Yes, the search mechanism finds it. Sorry for muddying the waters by relying on the Ainneve command that revealed this issue to test it. I only meant to say that for that error message to appear, `caller.search` had to have succeeded for the buckler on the ground. I confirmed it just now using `@py`.

As for the command thing. when I ran `ex self` after deleting the database and restarting the server, I wasn't seeing the entire RPSystemCmdSet on my superuser's automatically created character. This was fixed by running `@typeclass/force me = typeclasses.characters.Character`.

**Comment by Griatch** [comment] 2016-06-02 15:42
@feend78 

Ok, I think the error is then the scope or the custom search function - it does the sdesc query on the contents of the room, not including the inventory. 

I won't have time to look at this today, but if you want to check it, you can look at https://github.com/evennia/evennia/blob/master/evennia/contrib/rpsystem.py#L1044 and see if adding the inventory to the search candidates will fix the problem. You can also see my patch at the end of that method.

**Comment by Griatch** [comment] 2016-06-03 08:17
@feend: To answer your question in IRC, yes it looks like the error is in only the search function and not in the lack of an Object sdesc handler. The search method should handle Objects both with and without.

**Closed** 2016-06-04 11:07 UTC
Labels: bug, ongoing

**Comment by Griatch** [comment] 2016-06-04 11:12
I removed my first patch since that only hid the problem didn't fix it. The recog/sdesc systems will now correctly handle an object without an sdesc/recog handler of its own. It will then build the regex off the combination of the object's key and alias. 

With this there is no need for normal objects to have an sdesc handler, although the system expects them to inherit ContribRPObject so they can at least be posed. 

Closed.
